param_error="Erro de parâmetro"
component_num_limit="Você está temporariamente impossibilitado de criar mais grupos."
friend_num_limit="Você está temporariamente impossibilitado de adicionar mais amigos."
operation_error="Operação falhou. Por favor, tente novamente mais tarde!"
char_limit="Os caracteres inseridos excedem o limite máximo de comprimento. O máximo :number caracteres."
first_name_limit="O \"Sobrenome\" digitado excede o limite máximo de comprimento. O máximo :number caracteres."
last_name_limit="O \"Nome\" inserido excede o limite máximo de comprimento. O máximo :number caracteres."
first_name_required="O \"Sobrenome\" não pode ficar vazio."
last_name_required="O \"Nome\" não pode ficar vazio."
mobile_error="Erro de formato do número de telefone"
mobile_required="O número de telefone não pode estar vazio."
country_code_error="Erro de código de país"
search_key="Insira um ID de usuário ou número de celular válido."
is_add_friend="A solicitação de adição de amizade foi enviada."
system_error="Erro no sistema"
msg_code_error="Erro no formato do código de verificação"
first_name_length="O \"Sobrenome\" é muito longo."
friends_exist="Usuário não encontrado"
last_name_length="O \"Nome\" é muito longo."
content_length="O máximo de 200 caracteres"
he_friend_num_limit="O número de amigos seu ou do usuário atingiu o limite."
sign_error="Falha na verificação de assinatura"
is_friends="El usuario ha sido tu amigo."
sms_friend_tips="Adicione-me no JustUs."
photo_tips="Enviado com sucesso! Adicione mais amigos para compartilhar a vida real juntos"
message_limit="Você envia mensagens de texto com muita frequência. Por favor, tente novamente mais tarde."
copy_friend_tips="Adicione-me no JustUs."
no_add_friend_self="Você não pode adicionar a si mesmo como amigo."
justus_slogan="Vamos gravar a vida real juntos!"
justus_helper="Guia JustUs"
bind_mobile_error="O número de telefone foi vinculado a outra conta."
bound_mobile="Falha na vinculação. Por favor, tente novamente mais tarde."
not_add_self_friend="Você não pode adicionar a si mesmo como amigo."
address_book_tips="Sincronize seus contatos para encontrar amigos que já estão no JustUs. Seus dados de contatos serão enviados ao JustUs para melhorar sua experiência e permitir que você e outras pessoas encontrem amigos."
follow_user="seguiu você!"
notification_friends=":name tornou-se seu amigo \"JustUs\"! Tente enviar fotos para eles!"
notification_like=":name apenas gostei de você!"
notification_comment=":name acabou de comentar sobre você, confira!"
notification_friend_apply=":name enviou-lhe um pedido de amizade."
notification_friend_send_picture=":name postou uma nova foto."
notification_user_register="Venha tirar uma foto! Grave a vida real com seus amigos juntos!"
notification_friend_register=":name também está em JustUs. Adicionar?"
notification_memory=":name, você tem uma nova memória."
notification_wait_add_friend=":name, seus amigos estão esperando!"
notification_touch=":name tocou na sua foto💓"
notification_follow_user=":name seguiu você!"
photo_copy_1="Eu adicionei você em (JustUs). Baixe este aplicativo para permitir meu pedido de amizade.Minha identidade:"
photo_tips_1="Enviado com sucesso! Adicione mais amigos para compartilhar a vida real juntos"
photo_end_1="Não há mais momentos de amigos. Tire uma foto ou adicione mais amigos."
photo_copy_2="Adicione-me no JustUs. Minha identidade:"
photo_tips_2="Enviado com sucesso! Adicione mais amigos para compartilhar a vida real juntos"
photo_end_2="Não há mais momentos de amigos. Tire uma foto ou adicione mais amigos."
photo_copy_3="Adicione-me no JustUs para que possamos compartilhar fotos em nossa tela inicial. Minha identidade:"
photo_tips_3="Enviado para suas telas iniciais! Adicione mais amigos para compartilhar suas vidas reais em suas telas iniciais."
photo_end_3="Não há mais fotos. Adicione mais amigos para compartilhar suas vidas reais em suas telas iniciais."
photo_copy_4="Adicione-me no JustUs, tenho fotos para enviar para sua tela inicial. Minha identidade:"
photo_tips_4="Enviado para suas telas iniciais! Adicione mais amigos para compartilhar suas vidas reais em suas telas iniciais."
photo_end_4="Não há mais fotos. Adicione mais amigos para compartilhar suas vidas reais em suas telas iniciais."
photo_copy_5="Adicione-me no JustUs, a nova rede social de widgets! Minha identidade:"
photo_tips_5="Enviado para suas telas iniciais! Adicione mais amigos para compartilhar suas vidas reais em suas telas iniciais."
photo_end_5="Não há mais fotos. Convide mais amigos para compartilhar suas vidas reais em suas telas iniciais."
photo_copy_6="Adicione-me no JustUs - Widget Social Network, está tudo pronto menos você!"
photo_tips_6="Enviado para suas telas iniciais! Convide mais amigos para compartilhar suas vidas reais com eles."
photo_end_6="Não há mais fotos. Adicione mais amigos para compartilhar suas vidas reais com eles."
photo_copy_7="Me adicione no JustUs, tudo está pronto exceto você! Minha identidade:"
photo_tips_7="Enviado para suas telas iniciais! Convide mais amigos para compartilhar suas vidas reais com eles."
photo_end_7="Não há mais fotos. Adicione mais amigos para compartilhar suas vidas reais com eles."
photo_copy_8="Adicione-me no JustUs - Widget Social Network, compartilhe a vida real comigo! Minha identidade:"
photo_tips_8="Enviado para suas telas iniciais! Convide mais amigos para compartilhar suas vidas reais com eles."
photo_end_8="Não há mais fotos. Adicione mais amigos para compartilhar suas vidas reais com eles."
photo_copy_9="Aceite o desafio de fotos da vida real, adicione-me no JustUs. Minha identidade:"
photo_tips_9="Enviado para suas telas iniciais! Convide mais amigos para compartilhar suas vidas reais com eles."
photo_end_9="Não há mais fotos. Adicione mais amigos para compartilhar suas vidas reais com eles."
photo_copy_10="Eu quero que você esteja na minha tela inicial, me adicione no JustUs. Minha identidade:"
photo_tips_10="Enviado para suas telas iniciais! Seria mais divertido se você adicionasse mais amigos."
photo_end_10="Não há mais fotos. Adicione mais amigos para compartilhar suas vidas reais juntos."
photo_copy_11="Eu quero que você esteja na minha tela inicial, me adicione no JustUs. Minha identidade:"
photo_tips_11="Enviado para suas telas iniciais! Adicione mais amigos para enviar suas fotos para as telas iniciais deles."
photo_end_11="Parece que você ficou sem fotos de amigos! Adicione mais amigos para gravar suas vidas reais juntos."
photo_copy_12="Seja meu amigo da tela inicial, me adicione no JustUs. Minha identidade:"
photo_tips_12="Enviado para suas telas iniciais! Convide mais amigos para sua tela inicial e envie fotos divertidas para eles!"
photo_end_12="Parece que você ficou sem fotos de amigos! Convide mais amigos para sua tela inicial e envie fotos divertidas."
photo_copy_13="Seja meu amigo da tela inicial, me adicione no JustUs. Minha identidade:"
photo_tips_13="Enviado para suas telas iniciais! Seria mais divertido se você adicionasse mais amigos na tela inicial."
photo_end_13="Parece que você precisa de mais amigos! Convide mais amigos para sua tela inicial e envie fotos divertidas."
your_self_visible="Apenas visível para mim"
update_new_version="Nova função de dueto, venha atualizar e experimente!"
