param_error="Pogreška parametra"
component_num_limit="Privremeno ne možete stvoriti više grupa."
friend_num_limit="Privremeno ne možete dodati više prijatelja."
operation_error="Operacija nije uspjela. Molimo pokušajte ponovo kasnije!"
char_limit="Znakovi koje ste unijeli premašuju ograničenje maksimalne duljine. Maksimalno :number znakova."
first_name_limit="Prezime koje ste unijeli premašuje ograničenje maksimalne duljine. Maksimalno :number znakova."
last_name_limit="Ime koje ste unijeli premašuje ograničenje maksimalne duljine. Maksimalno :number znakova."
first_name_required="Polje \"Prezime\" ne može biti prazno."
last_name_required="Polje \"Ime\" ne može biti prazno."
mobile_error="Pogreška formata telefonskog broja"
mobile_required="Telefonski broj ne može biti prazan."
country_code_error="Pogreška koda zemlje"
search_key="Unesite važeći korisnički ID ili broj mobitela."
is_add_friend="Zahtjev za dodavanje prijatelja je poslan."
system_error="Pogreška sustava"
msg_code_error="Pogreška formata kontrolnog koda"
first_name_length="Prezime je predugačko."
friends_exist="Korisnik nije pronađen"
last_name_length="Ime je predugačko."
content_length="Maksimalno 200 znakova"
he_friend_num_limit="Vaš ili korisnikov broj prijatelja dosegao je ograničenje."
sign_error="Provjera potpisa nije uspjela"
is_friends="Korisnik vam je bio prijatelj."
sms_friend_tips="Dodaj me na gin-default."
photo_tips="Uspješno preneseno! Dodajte još prijatelja da zajedno dijelite stvarni život"
message_limit="Prečesto šaljete tekstualne poruke. Molimo pokušajte ponovo kasnije."
copy_friend_tips="Dodaj me na gin-default."
no_add_friend_self="Ne možete se dodati kao prijatelja."
gin-default_slogan="Snimimo stvarni život zajedno!"
gin-default_helper="gin-default vodič"
bind_mobile_error="Telefonski broj je vezan za drugi račun."
bound_mobile="Povezivanje nije uspjelo. Molimo pokušajte ponovo kasnije."
not_add_self_friend="Ne možete se dodati kao prijatelja."
address_book_tips="Sinkronizirajte svoje kontakte da biste pronašli prijatelje koji su već na gin-defaultu. Podaci o vašim kontaktima bit će poslani gin-defaultu kako bismo poboljšali vaše iskustvo i omogućili vama i drugima da pronađu prijatelje."
follow_user="pratio te!"
notification_friends=":name je postao vaš prijatelj \"Samo mi\"! Pokušajte im poslati fotografije!"
notification_like=":name ti se upravo svidio!"
notification_comment=":name vas je upravo komentirao, pogledajte!"
notification_friend_apply=":name vam je poslao zahtjev za prijateljstvo."
notification_friend_send_picture=":name je objavio novu fotografiju."
notification_user_register="Dođite i slikajte se! Snimite stvarni život sa svojim prijateljima zajedno!"
notification_friend_register=":name je također na gin-defaultu. Dodati?"
notification_memory=":name, imaš novu uspomenu."
notification_wait_add_friend=":name, tvoji prijatelji čekaju!"
notification_touch=":name je dodirnuo vašu fotografiju💓"
notification_follow_user=":name pratio te!"
photo_copy_1="Dodao sam vas na (gin-default). Preuzmite ovu aplikaciju da biste dopustili moj zahtjev za prijateljstvo.Moj ID:"
photo_tips_1="Uspješno preneseno! Dodajte još prijatelja da zajedno dijelite stvarni život"
photo_end_1="Nema više trenutaka prijatelja. Snimite fotografiju ili dodajte još prijatelja."
photo_copy_2="Dodaj me na gin-default.Moj ID:"
photo_tips_2="Uspješno preneseno! Dodajte još prijatelja da zajedno dijelite stvarni život"
photo_end_2="Nema više trenutaka prijatelja. Snimite fotografiju ili dodajte još prijatelja."
photo_copy_3="Dodajte me na gin-default kako bismo mogli dijeliti fotografije na našem početnom zaslonu. Moj ID:"
photo_tips_3="Poslano na njihove početne zaslone! Dodajte još prijatelja da podijelite svoje stvarne živote na svojim početnim zaslonima."
photo_end_3="Nema više fotografija. Dodajte još prijatelja da podijelite svoje stvarne živote na svojim početnim zaslonima."
photo_copy_4="Dodajte me na gin-default, imam fotografije za slanje na vaš početni zaslon. Moj ID:"
photo_tips_4="Poslano na njihove početne zaslone! Dodajte još prijatelja da podijelite svoje stvarne živote na svojim početnim zaslonima."
photo_end_4="Nema više fotografija. Dodajte još prijatelja da podijelite svoje stvarne živote na svojim početnim zaslonima."
photo_copy_5="Dodaj me na gin-default, novu widget društvenu mrežu! Moj ID:"
photo_tips_5="Poslano na njihove početne zaslone! Dodajte još prijatelja da podijelite svoje stvarne živote na svojim početnim zaslonima."
photo_end_5="Nema više fotografija. Pozovite više prijatelja da podijele svoje stvarne živote na vašim početnim zaslonima."
photo_copy_6="Dodaj me na gin-default - Widget Social Network, sve je spremno osim tebe!"
photo_tips_6="Poslano na njihove početne zaslone! Pozovite više prijatelja da s njima podijelite svoje stvarne živote."
photo_end_6="Nema više fotografija. Dodajte još prijatelja da s njima podijelite svoje stvarne živote."
photo_copy_7="Dodaj me na gin-default, sve je spremno osim tebe! Moj ID:"
photo_tips_7="Poslano na njihove početne zaslone! Pozovite više prijatelja da s njima podijelite svoje stvarne živote."
photo_end_7="Nema više fotografija. Dodajte još prijatelja da s njima podijelite svoje stvarne živote."
photo_copy_8="Dodajte me na gin-default - Widget Social Network, podijelite stvarni život sa mnom! Moj ID:"
photo_tips_8="Poslano na njihove početne zaslone! Pozovite više prijatelja da s njima podijelite svoje stvarne živote."
photo_end_8="Nema više fotografija. Dodajte još prijatelja da s njima podijelite svoje stvarne živote."
photo_copy_9="Prihvatite izazov iz stvarnog života, dodajte me na gin-default. Moj ID:"
photo_tips_9="Poslano na njihove početne zaslone! Pozovite više prijatelja da s njima podijelite svoje stvarne živote."
photo_end_9="Nema više fotografija. Dodajte još prijatelja da s njima podijelite svoje stvarne živote."
photo_copy_10="Želim da budeš na mom početnom zaslonu, dodaj me na gin-default. Moj ID:"
photo_tips_10="Poslano na njihove početne zaslone! Bilo bi zabavnije ako dodate još prijatelja."
photo_end_10="Nema više fotografija. Dodajte još prijatelja da zajedno podijelite svoje stvarne živote."
photo_copy_11="Želim da budeš na mom početnom zaslonu, dodaj me na gin-default. Moj ID:"
photo_tips_11="Poslano na njihove početne zaslone! Dodajte još prijatelja da pošaljete svoje fotografije na njihove početne zaslone."
photo_end_11="Čini se da ste ostali bez fotografija prijatelja! Dodajte još prijatelja kako biste zajedno snimili svoje stvarne živote."
photo_copy_12="Budi moj prijatelj na početnom zaslonu, dodaj me na gin-default. Moj ID:"
photo_tips_12="Poslano na njihove početne zaslone! Pozovite više prijatelja na svoj početni zaslon i pošaljite im zabavne fotografije!"
photo_end_12="Čini se da ste ostali bez fotografija prijatelja! Pozovite više prijatelja na početni zaslon i pošaljite im zabavne fotografije."
photo_copy_13="Budi moj prijatelj na početnom zaslonu, dodaj me na gin-default. Moj ID:"
photo_tips_13="Poslano na njihove početne zaslone! Bilo bi zabavnije ako dodate više prijatelja na početni zaslon."
photo_end_13="Čini se da trebate više prijatelja! Pozovite više prijatelja na početni zaslon i pošaljite im zabavne fotografije."
your_self_visible="Vidljivo samo meni"
update_new_version="Nova funkcija dueta, dođite na nadogradnju i doživite je!"
