param_error="parametre hatası"
component_num_limit="Geçici olarak daha fazla grup oluşturamazsınız."
friend_num_limit="Geçici olarak daha fazla arkadaş ekleyemezsiniz."
operation_error="Operasyon başarısız. Lütfen daha sonra tekrar deneyiniz!"
char_limit="Girdiğiniz karakterler maksimum uzunluk sınırını aşıyor. Maksimum :number karakter."
first_name_limit="Girdiğiniz \"Soyadı\" maksimum uzunluk sınırını aşıyor. Maksimum :number karakter."
last_name_limit="Girdiğiniz \"Ad\" maksimum uzunluk sınırını aşıyor. Maksimum :number karakter."
first_name_required="Soyadı boş olamaz."
last_name_required="Ad boş olamaz."
mobile_error="Telefon numarası biçimlendirme hatası"
mobile_required="Telefon numarası boş olamaz."
country_code_error="Ülke kodu hatası"
search_key="Lütfen geçerli bir kullanıcı kimliği veya cep telefonu numarası girin."
is_add_friend="Arkadaşlık ekleme isteği gönderildi."
system_error="Sistem hatası"
msg_code_error="Doğrulama kodu biçimi hatası"
first_name_length="Soyadı çok uzun."
friends_exist="Kullanıcı bulunamadı"
last_name_length="Ad çok uzun."
content_length="Maksimum 200 karakter"
he_friend_num_limit="Sizin veya kullanıcının arkadaş sayısı sınıra ulaştı."
sign_error="İmza doğrulama başarısız"
is_friends="Kullanıcı senin arkadaşın oldu."
sms_friend_tips="Beni JustUs'a ekle."
photo_tips="Başarıyla yüklendi! Gerçek hayatı birlikte paylaşmak için daha fazla arkadaş ekleyin"
message_limit="Çok sık kısa mesaj gönderiyorsunuz. Lütfen daha sonra tekrar deneyiniz."
copy_friend_tips="Beni JustUs'a ekle."
no_add_friend_self="Bir arkadaş olarak kendinizi ekleyemezsiniz."
justus_slogan="Gerçek hayatı birlikte kaydedelim!"
justus_helper="JustUs Kılavuzu"
bind_mobile_error="Telefon numarası başka bir hesaba bağlandı."
bound_mobile="Bağlanamadı. Lütfen daha sonra tekrar deneyiniz."
not_add_self_friend="Kendini arkadaş olarak ekleyemezsin."
address_book_tips="JustUs'ta zaten arkadaş bulmak için kişilerinizi senkronize edin. Kişi verileriniz, deneyiminizi geliştirmek ve sizin ve diğerlerinin arkadaş bulmanızı sağlamak için JustUs'a gönderilecek."
follow_user="Seni takip!"
notification_friends=":name \"Sadece Biz\" arkadaşınız oldu! Onlara fotoğraf göndermeyi deneyin!"
notification_like=":name senden hoşlandı!"
notification_comment=":name az önce sana yorum yaptı, şuna bir bak!"
notification_friend_apply=":name size bir arkadaşlık isteği gönderdi."
notification_friend_send_picture=":name yeni bir fotoğraf gönderdi."
notification_user_register="Gel ve bir fotoğraf çek! Arkadaşlarınızla birlikte gerçek hayatı kaydedin!"
notification_friend_register=":name ayrıca JustUs'ta. Ekle?"
notification_memory=":name, yeni bir hafızan var."
notification_wait_add_friend=":name, arkadaşların seni bekliyor!"
notification_touch=":name fotoğrafına dokundu 💓"
notification_follow_user=":name Seni takip!"
photo_copy_1="Seni (JustUs) ekledim. Arkadaşlık isteğime izin vermek için bu uygulamayı indirin.Benim kimliğim:"
photo_tips_1="Başarıyla yüklendi! Gerçek hayatı birlikte paylaşmak için daha fazla arkadaş ekleyin"
photo_end_1="Artık arkadaş anları yok. Bir fotoğraf çekin veya daha fazla arkadaş ekleyin."
photo_copy_2="Beni JustUs'a ekle. Benim kimliğim:"
photo_tips_2="Başarıyla yüklendi! Gerçek hayatı birlikte paylaşmak için daha fazla arkadaş ekleyin"
photo_end_2="Artık arkadaş anları yok. Bir fotoğraf çekin veya daha fazla arkadaş ekleyin."
photo_copy_3="Fotoğrafları ana ekranımızda paylaşabilmemiz için beni JustUs'a ekleyin. Benim kimliğim:"
photo_tips_3="Ana ekranlarına gönderildi! Gerçek yaşamlarınızı ana ekranlarınızda paylaşmak için daha fazla arkadaş ekleyin."
photo_end_3="Artık fotoğraf yok. Gerçek yaşamlarınızı ana ekranlarınızda paylaşmak için daha fazla arkadaş ekleyin."
photo_copy_4="Beni JustUs'a ekle, ana ekranınıza göndereceğim fotoğraflarım var. Benim kimliğim:"
photo_tips_4="Ana ekranlarına gönderildi! Gerçek yaşamlarınızı ana ekranlarınızda paylaşmak için daha fazla arkadaş ekleyin."
photo_end_4="Artık fotoğraf yok. Gerçek yaşamlarınızı ana ekranlarınızda paylaşmak için daha fazla arkadaş ekleyin."
photo_copy_5="Beni yeni widget sosyal ağı JustUs'a ekle! Benim kimliğim:"
photo_tips_5="Ana ekranlarına gönderildi! Gerçek yaşamlarınızı ana ekranlarınızda paylaşmak için daha fazla arkadaş ekleyin."
photo_end_5="Artık fotoğraf yok. Gerçek hayatlarınızı ana ekranlarınızda paylaşmaları için daha fazla arkadaşınızı davet edin."
photo_copy_6="Beni JustUs - Widget Social Network'e ekle, sen hariç her şey hazır!"
photo_tips_6="Ana ekranlarına gönderildi! Gerçek hayatınızı onlarla paylaşmak için daha fazla arkadaşınızı davet edin."
photo_end_6="Artık fotoğraf yok. Gerçek hayatınızı onlarla paylaşmak için daha fazla arkadaş ekleyin."
photo_copy_7="Beni JustUs'a ekle, senin dışında her şey hazır! Benim kimliğim:"
photo_tips_7="Ana ekranlarına gönderildi! Gerçek hayatınızı onlarla paylaşmak için daha fazla arkadaşınızı davet edin."
photo_end_7="Artık fotoğraf yok. Gerçek hayatınızı onlarla paylaşmak için daha fazla arkadaş ekleyin."
photo_copy_8="Beni JustUs - Widget Social Network'e ekle, benimle gerçek hayatı paylaş! Benim kimliğim:"
photo_tips_8="Ana ekranlarına gönderildi! Gerçek hayatınızı onlarla paylaşmak için daha fazla arkadaşınızı davet edin."
photo_end_8="Artık fotoğraf yok. Gerçek hayatınızı onlarla paylaşmak için daha fazla arkadaş ekleyin."
photo_copy_9="Gerçek hayattaki fotoğraf yarışmasını kabul edin, Beni JustUs'a ekleyin. Benim kimliğim:"
photo_tips_9="Ana ekranlarına gönderildi! Gerçek hayatınızı onlarla paylaşmak için daha fazla arkadaşınızı davet edin."
photo_end_9="Artık fotoğraf yok. Gerçek hayatınızı onlarla paylaşmak için daha fazla arkadaş ekleyin."
photo_copy_10="Ana ekranımda olmanı istiyorum, beni JustUs'a ekle. Benim kimliğim:"
photo_tips_10="Ana ekranlarına gönderildi! Daha fazla arkadaş eklersen daha eğlenceli olur."
photo_end_10="Artık fotoğraf yok. Gerçek yaşamlarınızı birlikte paylaşmak için daha fazla arkadaş ekleyin."
photo_copy_11="Ana ekranımda olmanı istiyorum, beni JustUs'a ekle. Benim kimliğim:"
photo_tips_11="Ana ekranlarına gönderildi! Fotoğraflarınızı ana ekranlarına göndermek için daha fazla arkadaş ekleyin."
photo_end_11="Görünüşe göre arkadaşlarının fotoğrafları tükendi! Birlikte gerçek yaşamlarınızı kaydetmek için daha fazla arkadaş ekleyin."
photo_copy_12="Ana ekran arkadaşım ol, beni JustUs'a ekle. Benim kimliğim:"
photo_tips_12="Ana ekranlarına gönderildi! Ana ekranınıza daha fazla arkadaşınızı davet edin ve onlara eğlenceli fotoğraflar gönderin!"
photo_end_12="Görünüşe göre arkadaşlarının fotoğrafları tükendi! Ana ekranınıza daha fazla arkadaşınızı davet edin ve onlara eğlenceli fotoğraflar gönderin."
photo_copy_13="Ana ekran arkadaşım ol, beni JustUs'a ekle. Benim kimliğim:"
photo_tips_13="Ana ekranlarına gönderildi! Daha fazla ana ekran arkadaşı eklerseniz daha eğlenceli olur."
photo_end_13="Görünüşe göre daha fazla arkadaşa ihtiyacın var! Ana ekranınıza daha fazla arkadaşınızı davet edin ve onlara eğlenceli fotoğraflar gönderin."
your_self_visible="sadece bana görünür"
update_new_version="Yeni düet işlevi, lütfen yükseltmeye ve deneyimlemeye gelin!"
