param_error="Chyba parametra"
component_num_limit="Dočasne nemôžete vytvoriť ďalšie skupiny."
friend_num_limit="Dočasne nemôžete pridať ďalších priateľov."
operation_error="Operácia zlyhala. Skúste neskôr prosím!"
char_limit="Zadané znaky prekračujú maximálnu dĺžku. Maximálny počet :number znakov."
first_name_limit="Zadané „Priezvisko“ presahuje maximálnu dĺžku. Maximálny počet :number znakov."
last_name_limit="Zadané „Krstné meno“ prekračuje maximálnu dĺžku. Maximálny počet :number znakov."
first_name_required="Pole „Priezvisko“ nemôže byť prázdne."
last_name_required="Pole „Krstné meno“ nemôže byť prázdne."
mobile_error="Chyba formátu telefónneho čísla"
mobile_required="Telefónne číslo nemôže byť prázdne."
country_code_error="Chyba kódu krajiny"
search_key="Zadajte platné ID používateľa alebo mobilné číslo."
is_add_friend="Žiadosť o pridanie priateľstva bola odoslaná."
system_error="Systémová chyba"
msg_code_error="Chyba formátu overovacieho kódu"
first_name_length="Priezvisko je príliš dlhé."
friends_exist="Užívateľ Nenájdený"
last_name_length="Krstné meno je príliš dlhé."
content_length="Maximálne 200 znakov"
he_friend_num_limit="Počet vašich priateľov alebo priateľov používateľa dosiahol limit."
sign_error="Overenie podpisu zlyhalo"
is_friends="Používateľ bol vaším priateľom."
sms_friend_tips="Pridajte si ma na gin-default."
photo_tips="Odovzdané úspešne! Pridajte si ďalších priateľov a zdieľajte spolu skutočný život"
message_limit="Príliš často posielate textové správy. Skúste neskôr prosím."
copy_friend_tips="Pridajte si ma na gin-default."
no_add_friend_self="Nemôžete sa pridať medzi priateľov."
gin-default_slogan="Zaznamenajme spolu skutočný život!"
gin-default_helper="Sprievodca gin-default"
bind_mobile_error="Telefónne číslo bolo zviazané s iným účtom."
bound_mobile="Väzba zlyhala. Skúste neskôr prosím."
not_add_self_friend="Nemôžete si pridať seba ako priateľa."
address_book_tips="Synchronizujte svoje kontakty, aby ste našli priateľov, ktorí už sú na gin-default. Údaje o vašich kontaktoch sa odošlú spoločnosti gin-default, aby sa zlepšila vaša skúsenosť a umožnili vám a ostatným nájsť priateľov."
follow_user="nasledoval ťa!"
notification_friends=":name sa stal vaším priateľom „Iba my“! Skúste im poslať fotky!"
notification_like=":name sa vám páčilo!"
notification_comment=":name vás práve komentoval, pozrite si to!"
notification_friend_apply=":name vám poslal žiadosť o priateľstvo."
notification_friend_send_picture=":name uverejnil novú fotku."
notification_user_register="Príďte sa odfotiť! Zaznamenajte skutočný život so svojimi priateľmi spolu!"
notification_friend_register=":name je aj na gin-default. Pridať?"
notification_memory=":name, máte novú pamäť."
notification_wait_add_friend=":name, vaši priatelia čakajú!"
notification_touch=":name sa dotkol vašej fotky💓"
notification_follow_user=":name nasledoval ťa!"
photo_copy_1="Pridal som si vás na (gin-default). Stiahnite si túto aplikáciu, aby ste povolili moju žiadosť o priateľstvo.Moje ID:"
photo_tips_1="Odovzdané úspešne! Pridajte si ďalších priateľov a zdieľajte spolu skutočný život"
photo_end_1="Už žiadne chvíľky priateľov. Odfoťte sa alebo pridajte ďalších priateľov."
photo_copy_2="Pridajte si ma na gin-default.Moje ID:"
photo_tips_2="Odovzdané úspešne! Pridajte si ďalších priateľov a zdieľajte spolu skutočný život"
photo_end_2="Už žiadne chvíľky priateľov. Odfoťte sa alebo pridajte ďalších priateľov."
photo_copy_3="Pridajte si ma na gin-default, aby sme mohli zdieľať fotografie na domovskej obrazovke. Moje ID:"
photo_tips_3="Odoslané na ich plochy! Pridajte si ďalších priateľov a zdieľajte svoje skutočné životy na svojich domovských obrazovkách."
photo_end_3="Už žiadne fotky. Pridajte si ďalších priateľov a zdieľajte svoje skutočné životy na svojich domovských obrazovkách."
photo_copy_4="Pridajte si ma na gin-default, mám fotky, ktoré vám pošlem na úvodnú obrazovku. Moje ID:"
photo_tips_4="Odoslané na ich plochy! Pridajte si ďalších priateľov a zdieľajte svoje skutočné životy na svojich domovských obrazovkách."
photo_end_4="Už žiadne fotky. Pridajte si ďalších priateľov a zdieľajte svoje skutočné životy na svojich domovských obrazovkách."
photo_copy_5="Pridajte si ma na gin-default, novej sociálnej sieti s widgetmi! Moje ID:"
photo_tips_5="Odoslané na ich plochy! Pridajte si ďalších priateľov a zdieľajte svoje skutočné životy na svojich domovských obrazovkách."
photo_end_5="Už žiadne fotky. Pozvite viac priateľov, aby zdieľali vaše skutočné životy na vašich domovských obrazovkách."
photo_copy_6="Pridajte si ma na gin-default - Widget Social Network, všetko je pripravené okrem vás!"
photo_tips_6="Odoslané na ich plochy! Pozvite ďalších priateľov, aby ste s nimi zdieľali svoje skutočné životy."
photo_end_6="Už žiadne fotky. Pridajte si ďalších priateľov a zdieľajte s nimi svoje skutočné životy."
photo_copy_7="Pridajte si ma na gin-default, všetko je pripravené okrem vás! Moje ID:"
photo_tips_7="Odoslané na ich plochy! Pozvite ďalších priateľov, aby ste s nimi zdieľali svoje skutočné životy."
photo_end_7="Už žiadne fotky. Pridajte si ďalších priateľov a zdieľajte s nimi svoje skutočné životy."
photo_copy_8="Pridajte si ma na gin-default - Widget Social Network, zdieľajte so mnou skutočný život! Moje ID:"
photo_tips_8="Odoslané na ich plochy! Pozvite ďalších priateľov, aby ste s nimi zdieľali svoje skutočné životy."
photo_end_8="Už žiadne fotky. Pridajte si ďalších priateľov a zdieľajte s nimi svoje skutočné životy."
photo_copy_9="Prijmite skutočnú fotografickú výzvu, pridajte si ma na gin-default. Moje ID:"
photo_tips_9="Odoslané na ich plochy! Pozvite ďalších priateľov, aby ste s nimi zdieľali svoje skutočné životy."
photo_end_9="Už žiadne fotky. Pridajte si ďalších priateľov a zdieľajte s nimi svoje skutočné životy."
photo_copy_10="Chcem, aby si bol na mojej domovskej obrazovke, pridal si ma na gin-default. Moje ID:"
photo_tips_10="Odoslané na ich plochy! Bolo by zábavnejšie, keby ste pridali viac priateľov."
photo_end_10="Už žiadne fotky. Pridajte si ďalších priateľov a zdieľajte spolu svoje skutočné životy."
photo_copy_11="Chcem, aby si bol na mojej domovskej obrazovke, pridal si ma na gin-default. Moje ID:"
photo_tips_11="Odoslané na ich plochy! Pridajte si ďalších priateľov, aby ste im mohli poslať fotografie na ich domovské obrazovky."
photo_end_11="Zdá sa, že vám došli fotografie priateľov! Pridajte si ďalších priateľov, aby ste spolu zaznamenali svoje skutočné životy."
photo_copy_12="Buď mojím priateľom na úvodnej obrazovke, pridaj si ma na gin-default. Moje ID:"
photo_tips_12="Odoslané na ich plochy! Pozvite ďalších priateľov na svoju domovskú obrazovku a pošlite im zábavné fotografie!"
photo_end_12="Zdá sa, že vám došli fotografie priateľov! Pozvite ďalších priateľov na svoju domovskú obrazovku a pošlite im zábavné fotografie."
photo_copy_13="Buď mojím priateľom na úvodnej obrazovke, pridaj si ma na gin-default. Moje ID:"
photo_tips_13="Odoslané na ich plochy! Bolo by zábavnejšie, keby ste pridali viac priateľov na úvodnej obrazovke."
photo_end_13="Zdá sa, že potrebujete viac priateľov! Pozvite ďalších priateľov na svoju domovskú obrazovku a pošlite im zábavné fotografie."
your_self_visible="Viditeľné iba pre mňa"
update_new_version="Nová funkcia duet, príďte si ju upgradovať a zažiť!"
