param_error="Parameterfeil"
component_num_limit="Du kan midlertidig ikke opprette flere grupper."
friend_num_limit="Du kan midlertidig ikke legge til flere venner."
operation_error="Operasjonen feilet. Pr칮v igjen senere!"
char_limit="Tegnene du skrev inn overskrider grensen for maksimal lengde. Maksimalt :number tegn."
first_name_limit="Etternavnet du skrev inn overskrider maksimal lengdegrense. Maksimalt :number tegn."
last_name_limit="Fornavnet du skrev inn overskrider den maksimale lengdegrensen. Maksimalt :number tegn."
first_name_required="Etternavn kan ikke v칝re tomt."
last_name_required="Fornavn kan ikke v칝re tomt."
mobile_error="Telefonnummerformatfeil"
mobile_required="Telefonnummeret kan ikke v칝re tomt."
country_code_error="Landskodefeil"
search_key="Vennligst skriv inn en gyldig bruker-ID eller mobilnummer."
is_add_friend="Legg til venneforesp칮rsel er sendt."
system_error="Systemfeil"
msg_code_error="Verifikasjonskodeformatfeil"
first_name_length="Etternavnet er for langt."
friends_exist="Bruker ikke funnet"
last_name_length="Fornavn er for langt."
content_length="Maksimalt 200 tegn"
he_friend_num_limit="Ditt eller brukerens antall venner har n친dd grensen."
sign_error="Signaturverifisering mislyktes"
is_friends="Brukeren har v칝rt din venn."
sms_friend_tips="Legg meg til p친 JustUs."
photo_tips="Lastet opp! Legg til flere venner for 친 dele det virkelige livet sammen"
message_limit="Du sender tekstmeldinger for ofte. Pr칮v igjen senere."
copy_friend_tips="Legg meg til p친 JustUs."
no_add_friend_self="Du kan ikke legge deg selv til som venn."
justus_slogan="La oss spille inn det virkelige livet sammen!"
justus_helper="JustUs guide"
bind_mobile_error="Telefonnummeret er knyttet til en annen konto."
bound_mobile="Innbinding mislyktes. Pr칮v igjen senere."
not_add_self_friend="Du kan ikke legge deg selv til som venn."
address_book_tips="Synkroniser kontaktene dine for 친 finne venner som allerede er p친 JustUs. Dine kontaktdata vil bli sendt til JustUs for 친 forbedre opplevelsen din og la deg og andre finne venner."
follow_user="fulgte deg!"
notification_friends=":name har blitt din \"Bare oss\"-venn! Pr칮v 친 sende dem bilder!"
notification_like=":name likte deg akkurat!"
notification_comment=":name kommenterte deg nettopp, sjekk det ut!"
notification_friend_apply=":name sendte deg en venneforesp칮rsel."
notification_friend_send_picture=":name har lagt ut et nytt bilde."
notification_user_register="Kom og ta et bilde! Ta opp det virkelige liv med vennene dine sammen!"
notification_friend_register=":name er ogs친 p친 JustUs. Legge til?"
notification_memory=":name, du har et nytt minne."
notification_wait_add_friend=":name, vennene dine venter!"
notification_touch=":name trykket p친 bildet ditt游눕"
notification_follow_user=":name fulgte deg!"
photo_copy_1="Jeg har lagt deg til p친 (JustUs). Last ned denne appen for 친 tillate venneforesp칮rselen min.Min ID:"
photo_tips_1="Lastet opp! Legg til flere venner for 친 dele det virkelige livet sammen"
photo_end_1="Ingen flere venners 칮yeblikk. Ta et bilde eller legg til flere venner."
photo_copy_2="Legg meg til p친 JustUs. Min ID:"
photo_tips_2="Lastet opp! Legg til flere venner for 친 dele det virkelige livet sammen"
photo_end_2="Ingen flere venners 칮yeblikk. Ta et bilde eller legg til flere venner."
photo_copy_3="Legg meg til p친 JustUs slik at vi kan dele bilder p친 startskjermen v친r. Min ID:"
photo_tips_3="Sendt til hjemmeskjermene deres! Legg til flere venner for 친 dele dine virkelige liv p친 startskjermene dine."
photo_end_3="Ingen flere bilder. Legg til flere venner for 친 dele dine virkelige liv p친 startskjermene dine."
photo_copy_4="Legg meg til p친 JustUs, jeg har bilder 친 sende til startskjermen din. Min ID:"
photo_tips_4="Sendt til hjemmeskjermene deres! Legg til flere venner for 친 dele dine virkelige liv p친 startskjermene dine."
photo_end_4="Ingen flere bilder. Legg til flere venner for 친 dele dine virkelige liv p친 startskjermene dine."
photo_copy_5="Legg meg til p친 JustUs, det nye widget sosiale nettverket! Min ID:"
photo_tips_5="Sendt til hjemmeskjermene deres! Legg til flere venner for 친 dele dine virkelige liv p친 startskjermene dine."
photo_end_5="Ingen flere bilder. Inviter flere venner til 친 dele det virkelige livet ditt p친 hjemmeskjermene dine."
photo_copy_6="Legg meg til p친 JustUs - Widget Social Network, alt er klart bortsett fra deg!"
photo_tips_6="Sendt til hjemmeskjermene deres! Inviter flere venner til 친 dele dine virkelige liv med dem."
photo_end_6="Ingen flere bilder. Legg til flere venner for 친 dele dine virkelige liv med dem."
photo_copy_7="Legg meg til p친 JustUs, alt er klart bortsett fra deg! Min ID:"
photo_tips_7="Sendt til hjemmeskjermene deres! Inviter flere venner til 친 dele dine virkelige liv med dem."
photo_end_7="Ingen flere bilder. Legg til flere venner for 친 dele dine virkelige liv med dem."
photo_copy_8="Legg meg til p친 JustUs - Widget Social Network, del det virkelige livet med meg! Min ID:"
photo_tips_8="Sendt til hjemmeskjermene deres! Inviter flere venner til 친 dele dine virkelige liv med dem."
photo_end_8="Ingen flere bilder. Legg til flere venner for 친 dele dine virkelige liv med dem."
photo_copy_9="Godta den virkelige fotoutfordringen, legg til meg p친 JustUs. Min ID:"
photo_tips_9="Sendt til hjemmeskjermene deres! Inviter flere venner til 친 dele dine virkelige liv med dem."
photo_end_9="Ingen flere bilder. Legg til flere venner for 친 dele dine virkelige liv med dem."
photo_copy_10="Jeg vil at du skal v칝re p친 startskjermen min, legg meg til p친 JustUs. Min ID:"
photo_tips_10="Sendt til hjemmeskjermene deres! Det ville v칝rt morsommere om du legger til flere venner."
photo_end_10="Ingen flere bilder. Legg til flere venner for 친 dele dine virkelige liv sammen."
photo_copy_11="Jeg vil at du skal v칝re p친 startskjermen min, legg meg til p친 JustUs. Min ID:"
photo_tips_11="Sendt til hjemmeskjermene deres! Legg til flere venner for 친 sende bildene dine til startskjermen deres."
photo_end_11="Ser ut til at du har g친tt tom for venners bilder! Legg til flere venner for 친 spille inn de virkelige livene dine sammen."
photo_copy_12="V칝r min hjemmeskjermvenn, legg meg til p친 JustUs. Min ID:"
photo_tips_12="Sendt til hjemmeskjermene deres! Inviter flere venner til startskjermen og send dem morsomme bilder!"
photo_end_12="Ser ut til at du har g친tt tom for venners bilder! Inviter flere venner til startskjermen og send dem morsomme bilder."
photo_copy_13="V칝r min hjemmeskjermvenn, legg meg til p친 JustUs. Min ID:"
photo_tips_13="Sendt til hjemmeskjermene deres! Det ville v칝rt morsommere hvis du legger til flere hjemmeskjermvenner."
photo_end_13="Ser ut til at du trenger flere venner! Inviter flere venner til startskjermen og send dem morsomme bilder."
your_self_visible="Bare synlig for meg"
update_new_version="Ny duettfunksjon, kom for 친 oppgradere og opplev den!"
