param_error="Parameterfout"
component_num_limit="Jy kan tydelik nie meer groepe skep nie."
friend_num_limit="Jy kan tydelik nie meer vriende byvoeg nie."
operation_error="Operasie het misluk. Probeer asseblief weer later!"
char_limit="Die karakters wat jy ingevoer het, oorskry die maksimum lengtelimiet. Die maksimum :number karakters."
first_name_limit="Die \"Vannaam\" wat jy ingevoer het, oorskry die maksimum lengtelimiet. Die maksimum :number karakters."
last_name_limit="Die \"Voornaam\" wat jy ingevoer het, oorskry die maksimum lengtelimiet. Die maksimum :number karakters."
first_name_required="Die \"Van\" kan nie leeg wees nie."
last_name_required="Die \"Voornaam\" kan nie leeg wees nie."
mobile_error="Telefoonnommerformaatfout"
mobile_required="Die telefoonnommer kan nie leeg wees nie."
country_code_error="Landkodefout"
search_key="Voer asseblief 'n geldige gebruiker-ID of selfoonnommer in."
is_add_friend="Voeg vriendskapsversoek is gestuur."
system_error="Sisteemfout"
msg_code_error="Verifikasiekode-formaatfout"
first_name_length="Die \"Vannaam\" is te lank."
friends_exist="Gebruiker nie gevind nie"
last_name_length="Die \"Voornaam\" is te lank."
content_length="Die maksimum 200 karakters"
he_friend_num_limit="Jou of die gebruiker se aantal vriende het die limiet bereik."
sign_error="Handtekeningverifikasie het misluk"
is_friends="Die gebruiker was jou vriend."
sms_friend_tips="Voeg my by JustUs."
photo_tips="Suksesvol opgelaai! Voeg meer vriende by om die werklike lewe saam te deel"
message_limit="Jy stuur te gereeld teksboodskappe. Probeer asseblief weer later."
copy_friend_tips="Voeg my by JustUs."
no_add_friend_self="Jy kan nie jouself as 'n vriend byvoeg nie."
justus_slogan="Kom ons teken die werklike lewe saam op!"
justus_helper="JustUs Gids"
bind_mobile_error="Die telefoonnommer is aan 'n ander rekening gekoppel."
bound_mobile="Kon nie bind nie. Probeer asseblief weer later."
not_add_self_friend="Jy kan jouself nie as 'n vriend byvoeg nie."
address_book_tips="Sinkroniseer jou kontakte om vriende te vind wat reeds op JustUs is. Jou kontaktedata sal na JustUs gestuur word om jou ervaring te verbeter en jou en ander toe te laat om vriende te vind."
follow_user="jou gevolg!"
notification_friends=":name het jou \"Net Ons\"-vriend geword! Probeer om vir hulle foto's te stuur!"
notification_like=":name het net van jou gehou!"
notification_comment=":name het sopas op jou kommentaar gelewer, kyk daarna!"
notification_friend_apply=":name het vir jou 'n vriendskapsversoek gestuur."
notification_friend_send_picture=":name het 'n nuwe foto geplaas."
notification_user_register="Kom neem 'n foto! Teken die werklike lewe saam met jou vriende op!"
notification_friend_register=":name is ook op JustUs. Voeg by?"
notification_memory=":name, jy het 'n nuwe geheue."
notification_wait_add_friend=":name, jou vriende wag!"
notification_touch=":name het jou foto getik💓"
notification_follow_user=":name jou gevolg!"
photo_copy_1="Ek het jou bygevoeg op (JustUs). Laai hierdie toepassing af om my vriendskapsversoek toe te laat.My ID:"
photo_tips_1="Suksesvol opgelaai! Voeg meer vriende by om die werklike lewe saam te deel"
photo_end_1="Nie meer vriende se oomblikke nie. Neem 'n foto of voeg meer vriende by."
photo_copy_2="Voeg my by JustUs. My ID:"
photo_tips_2="Suksesvol opgelaai! Voeg meer vriende by om die werklike lewe saam te deel"
photo_end_2="Nie meer vriende se oomblikke nie. Neem 'n foto of voeg meer vriende by."
photo_copy_3="Voeg my by JustUs sodat ons foto's op ons tuisskerm kan deel. My ID:"
photo_tips_3="Gestuur na hul tuisskerms! Voeg meer vriende by om jou regte lewens op jou tuisskerms te deel."
photo_end_3="Geen foto's meer nie. Voeg meer vriende by om jou regte lewens op jou tuisskerms te deel."
photo_copy_4="Voeg my by JustUs, ek het foto's om na jou tuisskerm te stuur. My ID:"
photo_tips_4="Gestuur na hul tuisskerms! Voeg meer vriende by om jou regte lewens op jou tuisskerms te deel."
photo_end_4="Geen foto's meer nie. Voeg meer vriende by om jou regte lewens op jou tuisskerms te deel."
photo_copy_5="Voeg my by JustUs, die nuwe widget sosiale netwerk! My ID:"
photo_tips_5="Gestuur na hul tuisskerms! Voeg meer vriende by om jou regte lewens op jou tuisskerms te deel."
photo_end_5="Geen foto's meer nie. Nooi meer vriende om jou regte lewens op jou tuisskerms te deel."
photo_copy_6="Voeg my by JustUs - Widget Social Network, alles is gereed behalwe jy!"
photo_tips_6="Gestuur na hul tuisskerms! Nooi meer vriende om jou regte lewens met hulle te deel."
photo_end_6="Geen foto's meer nie. Voeg meer vriende by om jou regte lewens met hulle te deel."
photo_copy_7="Voeg my by JustUs, alles is gereed behalwe jy! My ID:"
photo_tips_7="Gestuur na hul tuisskerms! Nooi meer vriende om jou regte lewens met hulle te deel."
photo_end_7="Geen foto's meer nie. Voeg meer vriende by om jou regte lewens met hulle te deel."
photo_copy_8="Voeg my by JustUs - Widget Social Network, deel die regte lewe met my! My ID:"
photo_tips_8="Gestuur na hul tuisskerms! Nooi meer vriende om jou regte lewens met hulle te deel."
photo_end_8="Geen foto's meer nie. Voeg meer vriende by om jou regte lewens met hulle te deel."
photo_copy_9="Aanvaar die werklike foto-uitdaging, Voeg my by JustUs. My ID:"
photo_tips_9="Gestuur na hul tuisskerms! Nooi meer vriende om jou regte lewens met hulle te deel."
photo_end_9="Geen foto's meer nie. Voeg meer vriende by om jou regte lewens met hulle te deel."
photo_copy_10="Ek wil hê jy moet op my tuisskerm wees, voeg my by JustUs. My ID:"
photo_tips_10="Gestuur na hul tuisskerms! Dit sal lekkerder wees as jy meer vriende byvoeg."
photo_end_10="Geen foto's meer nie. Voeg meer vriende by om jou regte lewens saam te deel."
photo_copy_11="Ek wil hê jy moet op my tuisskerm wees, voeg my by JustUs. My ID:"
photo_tips_11="Gestuur na hul tuisskerms! Voeg meer vriende by om jou foto's na hul tuisskerms te stuur."
photo_end_11="Dit lyk asof jy nie meer vriende se foto's het nie! Voeg meer vriende by om jou regte lewens saam op te neem."
photo_copy_12="Wees my tuisskermvriend, voeg my by JustUs. My ID:"
photo_tips_12="Gestuur na hul tuisskerms! Nooi meer vriende na jou tuisskerm en stuur vir hulle prettige foto's!"
photo_end_12="Dit lyk asof jy nie meer vriende se foto's het nie! Nooi meer vriende na jou tuisskerm en stuur vir hulle prettige foto's."
photo_copy_13="Wees my tuisskermvriend, voeg my by JustUs. My ID:"
photo_tips_13="Gestuur na hul tuisskerms! Dit sal lekkerder wees as jy meer tuisskermvriende byvoeg."
photo_end_13="Dit lyk of jy meer vriende nodig het! Nooi meer vriende na jou tuisskerm en stuur vir hulle prettige foto's."
your_self_visible="Net vir my sigbaar"
update_new_version="Nuwe duetfunksie, kom asseblief opgradeer en ervaar dit!"
