param_error="Hitilafu ya kigezo"
component_num_limit="Huwezi kuunda vikundi zaidi kwa sasa."
friend_num_limit="Huwezi kuongeza marafiki zaidi kwa sasa."
operation_error="Uendeshaji haukufaulu. Tafadhali jaribu tena baadae!"
char_limit="Herufi ulizoweka zinazidi kikomo cha urefu wa juu zaidi. Idadi ya juu zaidi :number herufi."
first_name_limit="Jina la ukoo uliloweka linazidi kikomo cha urefu wa juu zaidi. Upeo :number herufi."
last_name_limit="Jina la kwanza uliloweka linazidi kikomo cha urefu wa juu zaidi. Upeo :number herufi."
first_name_required="Jina la mwisho haliwezi kuwa tupu."
last_name_required="Jina la kwanza haliwezi kuwa tupu."
mobile_error="Hitilafu ya umbizo la nambari ya simu"
mobile_required="Nambari ya simu haiwezi kuwa tupu."
country_code_error="Hitilafu ya msimbo wa nchi"
search_key="Tafadhali weka kitambulisho halali cha mtumiaji au nambari ya simu."
is_add_friend="Ombi la kuongeza urafiki limetumwa."
system_error="Hitilafu ya mfumo"
msg_code_error="Hitilafu ya umbizo la msimbo wa uthibitishaji"
first_name_length="Jina la ukoo ni refu sana."
friends_exist="Mtumiaji Hajapatikana"
last_name_length="Jina la kwanza ni refu sana."
content_length="Isizidi herufi 200"
he_friend_num_limit="Idadi yako au ya mtumiaji ya marafiki imefikia kikomo."
sign_error="Uthibitishaji wa saini umeshindwa"
is_friends="Mtumiaji amekuwa rafiki yako."
sms_friend_tips="Niongeze kwenye JustUs."
photo_tips="Imepakiwa! Ongeza marafiki zaidi ili kushiriki maisha halisi pamoja"
message_limit="Unatuma SMS mara nyingi sana. Tafadhali jaribu tena baadae."
copy_friend_tips="Niongeze kwenye JustUs."
no_add_friend_self="Huwezi kujiongeza kama rafiki."
justus_slogan="Hebu turekodi maisha halisi pamoja!"
justus_helper="Mwongozo wa JustUs"
bind_mobile_error="Nambari ya simu imefungwa kwa akaunti nyingine."
bound_mobile="Kufunga kumeshindwa. Tafadhali jaribu tena baadae."
not_add_self_friend="Huwezi kujiongeza kama rafiki."
address_book_tips="Sawazisha anwani zako ili kupata marafiki tayari kwenye JustUs. Data ya anwani zako itatumwa kwa JustUs ili kuboresha matumizi yako na kukuruhusu wewe na wengine kupata marafiki."
follow_user="alikufuata!"
notification_friends=":name amekuwa rafiki yako wa \"Sisi Tu\"! Jaribu kuwatumia picha!"
notification_like=":name nimekupenda tu!"
notification_comment=":name ametoa maoni kuhusu wewe, iangalie!"
notification_friend_apply=":name alikutumia ombi la urafiki."
notification_friend_send_picture=":name alichapisha picha mpya."
notification_user_register="Njoo na upige picha! Rekodi maisha halisi na marafiki zako pamoja!"
notification_friend_register=":name jina pia liko kwenye JustUs. Ongeza?"
notification_memory=":name, una kumbukumbu mpya."
notification_wait_add_friend=":name, marafiki zako wanasubiri!"
notification_touch=":name imegusa picha yako💓"
notification_follow_user=":name alikufuata!"
photo_copy_1="Nimekuongeza juu ya (JustUs). Pakua programu hii ili kuruhusu ombi langu la urafiki.Kitambulisho changu:"
photo_tips_1="Imepakiwa! Ongeza marafiki zaidi ili kushiriki maisha halisi pamoja"
photo_end_1="Hakuna matukio ya marafiki tena. Piga picha au ongeza marafiki zaidi."
photo_copy_2="Niongeze kwenye JustUs. Kitambulisho changu:"
photo_tips_2="Imepakiwa! Ongeza marafiki zaidi ili kushiriki maisha halisi pamoja"
photo_end_2="Hakuna matukio ya marafiki tena. Piga picha au ongeza marafiki zaidi."
photo_copy_3="Niongeze kwenye JustUs ili tuweze kushiriki picha kwenye skrini yetu ya kwanza. Kitambulisho changu:"
photo_tips_3="Imetumwa kwa skrini zao za nyumbani! Ongeza marafiki zaidi ili kushiriki maisha yako halisi kwenye skrini zako za nyumbani."
photo_end_3="Hakuna picha zaidi. Ongeza marafiki zaidi ili kushiriki maisha yako halisi kwenye skrini zako za nyumbani."
photo_copy_4="Niongeze kwenye JustUs, nina picha za kutuma kwenye skrini yako ya kwanza. Kitambulisho changu:"
photo_tips_4="Imetumwa kwa skrini zao za nyumbani! Ongeza marafiki zaidi ili kushiriki maisha yako halisi kwenye skrini zako za nyumbani."
photo_end_4="Hakuna picha zaidi. Ongeza marafiki zaidi ili kushiriki maisha yako halisi kwenye skrini zako za nyumbani."
photo_copy_5="Niongeze kwenye JustUs, wijeti mpya ya mtandao wa kijamii! Kitambulisho changu:"
photo_tips_5="Imetumwa kwa skrini zao za nyumbani! Ongeza marafiki zaidi ili kushiriki maisha yako halisi kwenye skrini zako za nyumbani."
photo_end_5="Hakuna picha zaidi. Alika marafiki zaidi kushiriki maisha yako halisi kwenye skrini zako za nyumbani."
photo_copy_6="Niongeze kwenye JustUs - Widget Social Network, zote ziko tayari isipokuwa wewe!"
photo_tips_6="Imetumwa kwa skrini zao za nyumbani! Alika marafiki zaidi kushiriki maisha yako halisi nao."
photo_end_6="Hakuna picha zaidi. Ongeza marafiki zaidi ili kushiriki nao maisha yako halisi."
photo_copy_7="Niongeze kwenye JustUs, yote yako tayari isipokuwa wewe! Kitambulisho changu:"
photo_tips_7="Imetumwa kwa skrini zao za nyumbani! Alika marafiki zaidi kushiriki maisha yako halisi nao."
photo_end_7="Hakuna picha zaidi. Ongeza marafiki zaidi ili kushiriki nao maisha yako halisi."
photo_copy_8="Niongeze kwenye JustUs - Widget Social Network, shiriki maisha halisi nami! Kitambulisho changu:"
photo_tips_8="Imetumwa kwa skrini zao za nyumbani! Alika marafiki zaidi kushiriki maisha yako halisi nao."
photo_end_8="Hakuna picha zaidi. Ongeza marafiki zaidi ili kushiriki nao maisha yako halisi."
photo_copy_9="Kubali changamoto ya picha ya maisha halisi, Niongeze kwenye JustUs. Kitambulisho changu:"
photo_tips_9="Imetumwa kwa skrini zao za nyumbani! Alika marafiki zaidi kushiriki maisha yako halisi nao."
photo_end_9="Hakuna picha zaidi. Ongeza marafiki zaidi ili kushiriki nao maisha yako halisi."
photo_copy_10="Ninataka uwe kwenye skrini yangu ya nyumbani, uniongeze kwenye JustUs. Kitambulisho changu:"
photo_tips_10="Imetumwa kwa skrini zao za nyumbani! Itakuwa ya kufurahisha zaidi ikiwa utaongeza marafiki zaidi."
photo_end_10="Hakuna picha zaidi. Ongeza marafiki zaidi ili kushiriki maisha yako halisi pamoja."
photo_copy_11="Ninataka uwe kwenye skrini yangu ya nyumbani, uniongeze kwenye JustUs. Kitambulisho changu:"
photo_tips_11="Imetumwa kwa skrini zao za nyumbani! Ongeza marafiki zaidi ili kutuma picha zako kwenye skrini zao za nyumbani."
photo_end_11="Inaonekana umeishiwa na picha za marafiki! Ongeza marafiki zaidi ili kurekodi maisha yako halisi pamoja."
photo_copy_12="Kuwa rafiki yangu wa skrini ya kwanza, niongeze kwenye JustUs. Kitambulisho changu:"
photo_tips_12="Imetumwa kwa skrini zao za nyumbani! Alika marafiki zaidi kwenye skrini yako ya nyumbani na uwatumie picha za kufurahisha!"
photo_end_12="Inaonekana umeishiwa na picha za marafiki! Alika marafiki zaidi kwenye skrini yako ya nyumbani na uwatumie picha za kufurahisha."
photo_copy_13="Kuwa rafiki yangu wa skrini ya kwanza, niongeze kwenye JustUs. Kitambulisho changu:"
photo_tips_13="Imetumwa kwa skrini zao za nyumbani! Itakuwa ya kufurahisha zaidi ikiwa utaongeza marafiki zaidi wa skrini ya kwanza."
photo_end_13="Inaonekana unahitaji marafiki zaidi! Alika marafiki zaidi kwenye skrini yako ya nyumbani na uwatumie picha za kufurahisha."
your_self_visible="Inaonekana kwangu tu"
update_new_version="Kitendaji kipya cha duet, tafadhali njoo ili kusasisha na upate uzoefu!"
