param_error="የመለኪያ ስህተት"
component_num_limit="ለጊዜው ተጨማሪ ቡድኖችን መፍጠር አትችልም።"
friend_num_limit="ለጊዜው ተጨማሪ ጓደኞችን ማከል አትችልም።"
operation_error="ክወና አልተሳካም። እባክዎ ቆየት ብለው ይሞክሩ!"
char_limit="ያስገቧቸው ቁምፊዎች ከከፍተኛው የርዝመት ገደብ አልፈዋል። ከፍተኛው :number ቁምፊዎች።"
first_name_limit="ያስገቡት \"የአያት ስም\" ከከፍተኛው የርዝመት ገደብ አልፏል። ከፍተኛው :number ቁምፊዎች።"
last_name_limit="ያስገቡት \"የመጀመሪያ ስም\" ከከፍተኛው የርዝመት ገደብ አልፏል። ከፍተኛው :number ቁምፊዎች።"
first_name_required="የአያት ስም ባዶ ሊሆን አይችልም።"
last_name_required="የመጀመሪያ ስም ባዶ ሊሆን አይችልም."
mobile_error="የስልክ ቁጥር ቅርጸት ስህተት"
mobile_required="ስልክ ቁጥሩ ባዶ ሊሆን አይችልም።"
country_code_error="የአገር ኮድ ስህተት"
search_key="እባክዎ ትክክለኛ የተጠቃሚ መታወቂያ ወይም የሞባይል ቁጥር ያስገቡ።"
is_add_friend="የጓደኝነት አክል ጥያቄ ተልኳል።"
system_error="የስርዓት ስህተት"
msg_code_error="የማረጋገጫ ኮድ ቅርጸት ስህተት"
first_name_length="የአያት ስም በጣም ረጅም ነው።"
friends_exist="ተጠቃሚ አልተገኘም።"
last_name_length="የመጀመሪያ ስም በጣም ረጅም ነው።"
content_length="ከፍተኛው 200 ቁምፊዎች"
he_friend_num_limit="የእርስዎ ወይም የተጠቃሚው የጓደኞች ብዛት ገደቡ ላይ ደርሷል።"
sign_error="ፊርማ ማረጋገጥ አልተሳካም።"
is_friends="ተጠቃሚው ጓደኛህ ነበር።"
sms_friend_tips="በ gin-default ላይ ጨምሩኝ። የ"
photo_tips="በተሳካ ሁኔታ ተጭኗል! የእውነተኛ ህይወት አብረው ለመጋራት ተጨማሪ ጓደኞችን ያክሉ"
message_limit="ብዙ ጊዜ የጽሑፍ መልእክት ትልካለህ። እባክዎ ቆየት ብለው ይሞክሩ."
copy_friend_tips="በ gin-default ላይ ጨምሩኝ። የ"
no_add_friend_self="እራስዎን እንደ ጓደኛ ማከል አይችሉም."
gin-default_slogan="እውነተኛ ህይወትን አብረን እንመዘግብ!"
gin-default_helper="gin-default መመሪያ"
bind_mobile_error="ስልክ ቁጥሩ ከሌላ መለያ ጋር ተያይዟል።"
bound_mobile="ማሰር አልተሳካም። እባክዎ ቆየት ብለው ይሞክሩ."
not_add_self_friend="እራስዎን እንደ ጓደኛ ማከል አይችሉም."
address_book_tips="ቀድሞውኑ በ gin-default ላይ ጓደኞችን ለማግኘት እውቂያዎችዎን ያመሳስሉ። ተሞክሮዎን ለማሻሻል እና እርስዎ እና ሌሎች ጓደኞችን እንዲያገኙ ለመፍቀድ የእውቂያዎችዎ ውሂብ ወደ gin-default ይላካል።"
follow_user="ተከተለህ!"
notification_friends=":name የ«እኛ ብቻ» ጓደኛዎ ሆኗል! ፎቶዎችን ለመላክ ይሞክሩ!"
notification_like=":name ወደድኳችሁ!"
notification_comment=":name በአንተ ላይ አስተያየት ሰጥቷል፣ ተመልከት!"
notification_friend_apply=":name የጓደኝነት ጥያቄ ልኮልዎታል።"
notification_friend_send_picture=":name አዲስ ፎቶ አውጥቷል።"
notification_user_register="ይምጡና ፎቶ አንሳ! አብረው ከጓደኞችዎ ጋር እውነተኛ ሕይወት ይመዝግቡ!"
notification_friend_register=":name አሁን gin-default ተመዝግቧል። እንደ ጓደኛ ያክሉት?"
notification_memory=":name፣ አዲስ ትውስታ አለህ።"
notification_wait_add_friend=":name, ጓደኞችዎ እየጠበቁ ናቸው!"
notification_touch=":name ፎቶህን መታ 💓"
notification_follow_user=":nameተከተለህ!"
photo_copy_1="በ (gin-default) ላይ ጨምሬሃለሁ። የጓደኛዬን ጥያቄ ለመፍቀድ ይህን መተግበሪያ አውርድ።የእኔ መታወቂያ:"
photo_tips_1="በተሳካ ሁኔታ ተጭኗል! የእውነተኛ ህይወት አብረው ለመጋራት ተጨማሪ ጓደኞችን ያክሉ"
photo_end_1="ከእንግዲህ የጓደኞች አፍታዎች የሉም። ፎቶ አንሳ ወይም ተጨማሪ ጓደኞችን ጨምር።"
photo_copy_2="በ gin-default ላይ ጨምሩኝ። የ የእኔ መታወቂያ:"
photo_tips_2="በተሳካ ሁኔታ ተጭኗል! የእውነተኛ ህይወት አብረው ለመጋራት ተጨማሪ ጓደኞችን ያክሉ"
photo_end_2="ከእንግዲህ የጓደኞች አፍታዎች የሉም። ፎቶ አንሳ ወይም ተጨማሪ ጓደኞችን ጨምር።"
photo_copy_3="ፎቶዎችን ወደ መነሻ ስክሪናችን ማጋራት እንድንችል gin-default ላይ ጨምሩኝ። የእኔ መታወቂያ፡-"
photo_tips_3="ወደ መነሻ ስክሪናቸው ተልኳል! በመነሻ ማያዎችዎ ላይ እውነተኛ ህይወትዎን ለማጋራት ተጨማሪ ጓደኞችን ያክሉ።"
photo_end_3="ምንም ተጨማሪ ፎቶዎች የሉም። በመነሻ ማያዎችዎ ላይ እውነተኛ ህይወትዎን ለማጋራት ተጨማሪ ጓደኞችን ያክሉ።"
photo_copy_4="በ gin-default ላይ ጨምሩኝ፣ ወደ መነሻ ስክሪን የምልክላቸው ፎቶዎች አሉኝ። የእኔ መታወቂያ፡-"
photo_tips_4="ወደ መነሻ ስክሪናቸው ተልኳል! በመነሻ ማያዎችዎ ላይ እውነተኛ ህይወትዎን ለማጋራት ተጨማሪ ጓደኞችን ያክሉ።"
photo_end_4="ምንም ተጨማሪ ፎቶዎች የሉም። በመነሻ ማያዎችዎ ላይ እውነተኛ ህይወትዎን ለማጋራት ተጨማሪ ጓደኞችን ያክሉ።"
photo_copy_5="አዲሱ መግብር ማህበራዊ አውታረ መረብ በሆነው gin-default ላይ ጨምሩኝ! የእኔ መታወቂያ፡-"
photo_tips_5="ወደ መነሻ ስክሪናቸው ተልኳል! በመነሻ ማያዎችዎ ላይ እውነተኛ ህይወትዎን ለማጋራት ተጨማሪ ጓደኞችን ያክሉ።"
photo_end_5="ምንም ተጨማሪ ፎቶዎች የሉም። በመነሻ ስክሪኖችዎ ላይ እውነተኛ ህይወትዎን እንዲያካፍሉ ተጨማሪ ጓደኞችን ይጋብዙ።"
photo_copy_6="በ gin-default ላይ ጨምሩኝ - መግብር ማህበራዊ አውታረ መረብ ፣ ከእርስዎ በስተቀር ሁሉም ዝግጁ ነው!"
photo_tips_6="ወደ መነሻ ስክሪናቸው ተልኳል! እውነተኛ ህይወትዎን ለእነሱ እንዲያካፍሉ ተጨማሪ ጓደኞችን ይጋብዙ።"
photo_end_6="ምንም ተጨማሪ ፎቶዎች የሉም። እውነተኛ ህይወትዎን ከእነሱ ጋር ለመጋራት ተጨማሪ ጓደኞችን ያክሉ።"
photo_copy_7="በ gin-default ላይ ጨምሩኝ ፣ ካንተ በስተቀር ሁሉም ዝግጁ ነው! የእኔ መታወቂያ፡-"
photo_tips_7="ወደ መነሻ ስክሪናቸው ተልኳል! እውነተኛ ህይወትዎን ለእነሱ እንዲያካፍሉ ተጨማሪ ጓደኞችን ይጋብዙ።"
photo_end_7="ምንም ተጨማሪ ፎቶዎች የሉም። እውነተኛ ህይወትዎን ከእነሱ ጋር ለመጋራት ተጨማሪ ጓደኞችን ያክሉ።"
photo_copy_8="በ gin-default - Widget ማህበራዊ አውታረ መረብ ላይ ጨምሩኝ ፣ እውነተኛ ህይወት ከእኔ ጋር ይጋሩ! የእኔ መታወቂያ፡-"
photo_tips_8="ወደ መነሻ ስክሪናቸው ተልኳል! እውነተኛ ህይወትዎን ለእነሱ እንዲያካፍሉ ተጨማሪ ጓደኞችን ይጋብዙ።"
photo_end_8="ምንም ተጨማሪ ፎቶዎች የሉም። እውነተኛ ህይወትዎን ከእነሱ ጋር ለመጋራት ተጨማሪ ጓደኞችን ያክሉ።"
photo_copy_9="የእውነተኛ ህይወት ፎቶ ፈተናን ተቀበል፣ በ gin-default ላይ ጨምርኝ። የእኔ መታወቂያ፡-"
photo_tips_9="ወደ መነሻ ስክሪናቸው ተልኳል! እውነተኛ ህይወትዎን ለእነሱ እንዲያካፍሉ ተጨማሪ ጓደኞችን ይጋብዙ።"
photo_end_9="ምንም ተጨማሪ ፎቶዎች የሉም። እውነተኛ ህይወትዎን ከእነሱ ጋር ለመጋራት ተጨማሪ ጓደኞችን ያክሉ።"
photo_copy_10="በመነሻ ስክሪን ላይ እንድትሆኑ እፈልጋለሁ፣ በ gin-default ላይ ጨምሩኝ። የእኔ መታወቂያ፡-"
photo_tips_10="ወደ መነሻ ስክሪናቸው ተልኳል! ብዙ ጓደኞች ካከሉ የበለጠ አስደሳች ይሆናል።"
photo_end_10="ምንም ተጨማሪ ፎቶዎች የሉም። እውነተኛ ህይወቶቻችሁን አብረው ለማጋራት ተጨማሪ ጓደኞችን ያክሉ።"
photo_copy_11="በመነሻ ስክሪን ላይ እንድትሆኑ እፈልጋለሁ፣ በ gin-default ላይ ጨምሩኝ። የእኔ መታወቂያ፡-"
photo_tips_11="ወደ መነሻ ስክሪናቸው ተልኳል! ፎቶዎችዎን ወደ መነሻ ማያዎቻቸው ለመላክ ተጨማሪ ጓደኞችን ያክሉ።"
photo_end_11="የጓደኞች ፎቶዎች ያለቀብዎት ይመስላል! እውነተኛ ህይወቶቻችሁን አብራችሁ ለመመዝገብ ተጨማሪ ጓደኞችን ያክሉ።"
photo_copy_12="የመነሻ ማያ ጓደኛዬ ሁን፣ በ gin-default ላይ ጨምርኝ። የእኔ መታወቂያ፡-"
photo_tips_12="ወደ መነሻ ስክሪናቸው ተልኳል! ተጨማሪ ጓደኞችን ወደ መነሻ ማያ ገጽዎ ይጋብዙ እና አስደሳች ፎቶዎችን ይላኩላቸው!"
photo_end_12="የጓደኞች ፎቶዎች ያለቀብዎት ይመስላል! ተጨማሪ ጓደኞችን ወደ መነሻ ማያ ገጽዎ ይጋብዙ እና አስደሳች ፎቶዎችን ይላኩ።"
photo_copy_13="የመነሻ ማያ ጓደኛዬ ሁን፣ በ gin-default ላይ ጨምርኝ። የእኔ መታወቂያ፡-"
photo_tips_13="ወደ መነሻ ስክሪናቸው ተልኳል! ተጨማሪ የመነሻ ማያ ጓደኞችን ካከሉ ​​የበለጠ አስደሳች ይሆናል።"
photo_end_13="ተጨማሪ ጓደኞች የሚያስፈልግህ ይመስላል! ተጨማሪ ጓደኞችን ወደ መነሻ ማያ ገጽዎ ይጋብዙ እና አስደሳች ፎቶዎችን ይላኩ።"
your_self_visible="ለእኔ ብቻ የሚታይ"
update_new_version="አዲስ duet ተግባር፣ እባክዎን ለማሻሻል ይምጡ እና ይለማመዱት!"
