param_error="Parameterfehler"
component_num_limit="Sie können vorübergehend keine weiteren Gruppen erstellen."
friend_num_limit="Sie können vorübergehend keine weiteren Freunde hinzufügen."
operation_error="Operation fehlgeschlagen. Bitte versuchen Sie es später noch einmal!"
char_limit="Die eingegebenen Zeichen überschreiten die maximale Länge. Das Maximum :number Zeichen."
first_name_limit="Der von Ihnen eingegebene \"Nachname\" überschreitet die maximale Länge. Das Maximum :number Zeichen."
last_name_limit="Der von Ihnen eingegebene \"Vorname\" überschreitet die maximale Länge. Das Maximum :number Zeichen."
first_name_required="Der \"Nachname\" darf nicht leer sein."
last_name_required="Der „Vorname“ darf nicht leer sein."
mobile_error="Fehler im Telefonnummernformat"
mobile_required="Die Telefonnummer darf nicht leer sein."
country_code_error="Ländercodefehler"
search_key="Bitte geben Sie eine gültige Benutzer-ID oder Handynummer ein."
is_add_friend="Freundschaftsanfrage wurde gesendet."
system_error="Systemfehler"
msg_code_error="Formatfehler des Bestätigungscodes"
first_name_length="Der \"Nachname\" ist zu lang."
friends_exist="Benutzer nicht gefunden"
last_name_length="Der \"Vorname\" ist zu lang."
content_length="Die maximal 200 Zeichen"
he_friend_num_limit="Ihre oder die Anzahl der Freunde des Benutzers hat das Limit erreicht."
sign_error="Signaturprüfung gescheitert"
is_friends="Der Benutzer war dein Freund."
sms_friend_tips="Füge mich auf gin-default hinzu."
photo_tips="Erfolgreich hochgeladen! Fügen Sie weitere Freunde hinzu, um das echte Leben miteinander zu teilen"
message_limit="Sie senden zu oft Textnachrichten. Bitte versuchen Sie es später erneut."
copy_friend_tips="Füge mich auf gin-default hinzu."
no_add_friend_self="Sie können sich nicht selbst als Freund hinzufügen."
gin-default_slogan="Lass uns gemeinsam das wahre Leben aufnehmen!"
gin-default_helper="gin-default-Leitfaden"
bind_mobile_error="Die Telefonnummer wurde an ein anderes Konto gebunden."
bound_mobile="Bindung fehlgeschlagen. Bitte versuchen Sie es später erneut."
not_add_self_friend="Du kannst dich selbst nicht als Freund hinzufügen."
address_book_tips="Synchronisieren Sie Ihre Kontakte, um Freunde zu finden, die bereits bei gin-default sind. Ihre Kontaktdaten werden an gin-default gesendet, um Ihre Erfahrung zu verbessern und es Ihnen und anderen zu ermöglichen, Freunde zu finden."
follow_user="dir gefolgt!"
notification_friends=":name ist Ihr „gin-default“-Freund geworden! Versuchen Sie, ihnen Fotos zu schicken!"
notification_like=":name mochte dich einfach!"
notification_comment=":name hat dich gerade kommentiert, schau es dir an!"
notification_friend_apply=":name hat dir eine Freundschaftsanfrage gesendet."
notification_friend_send_picture=":name hat ein neues Foto gepostet."
notification_user_register="Kommen Sie und machen Sie ein Foto! Nehmen Sie das echte Leben mit Ihren Freunden zusammen auf!"
notification_friend_register=":name ist auch auf gin-default. Hinzufügen?"
notification_memory=":name, du hast eine neue Erinnerung."
notification_wait_add_friend=":name, deine Freunde warten!"
notification_touch=":name hat auf dein Foto getippt💓"
notification_follow_user=":name dir gefolgt!"
photo_copy_1="Ich habe dich auf (gin-default) hinzugefügt. Laden Sie diese App herunter, um meine Freundschaftsanfrage zuzulassen.Meine ID:"
photo_tips_1="Erfolgreich hochgeladen! Fügen Sie weitere Freunde hinzu, um das echte Leben miteinander zu teilen"
photo_end_1="Keine Freundesmomente mehr. Machen Sie ein Foto oder fügen Sie weitere Freunde hinzu."
photo_copy_2="Füge mich auf gin-default hinzu.Meine ID:"
photo_tips_2="Erfolgreich hochgeladen! Fügen Sie weitere Freunde hinzu, um das echte Leben miteinander zu teilen"
photo_end_2="Keine Freundesmomente mehr. Machen Sie ein Foto oder fügen Sie weitere Freunde hinzu."
photo_copy_3="Füge mich auf gin-default hinzu, damit wir Fotos auf unserem Homescreen teilen können. Meine ID:"
photo_tips_3="An ihre Homescreens gesendet! Fügen Sie weitere Freunde hinzu, um Ihr echtes Leben auf Ihren Homescreens zu teilen."
photo_end_3="Keine Fotos mehr. Fügen Sie weitere Freunde hinzu, um Ihr echtes Leben auf Ihren Homescreens zu teilen."
photo_copy_4="Fügen Sie mich auf gin-default hinzu, ich habe Fotos, die Sie an Ihren Homescreen senden können. Meine ID:"
photo_tips_4="An ihre Homescreens gesendet! Fügen Sie weitere Freunde hinzu, um Ihr echtes Leben auf Ihren Homescreens zu teilen."
photo_end_4="Keine Fotos mehr. Fügen Sie weitere Freunde hinzu, um Ihr echtes Leben auf Ihren Homescreens zu teilen."
photo_copy_5="Fügen Sie mich zu gin-default hinzu, dem neuen sozialen Widget-Netzwerk! Meine ID:"
photo_tips_5="An ihre Homescreens gesendet! Fügen Sie weitere Freunde hinzu, um Ihr echtes Leben auf Ihren Homescreens zu teilen."
photo_end_5="Keine Fotos mehr. Laden Sie mehr Freunde ein, Ihr wahres Leben auf Ihren Homescreens zu teilen."
photo_copy_6="Fügen Sie mich zu gin-default - Widget Social Network hinzu, alles ist bereit, außer Ihnen!"
photo_tips_6="An ihre Homescreens gesendet! Laden Sie mehr Freunde ein, Ihr wahres Leben mit ihnen zu teilen."
photo_end_6="Keine Fotos mehr. Fügen Sie weitere Freunde hinzu, um Ihr wahres Leben mit ihnen zu teilen."
photo_copy_7="Füge mich auf gin-default hinzu, alles ist bereit außer dir! Meine ID:"
photo_tips_7="An ihre Homescreens gesendet! Laden Sie mehr Freunde ein, Ihr wahres Leben mit ihnen zu teilen."
photo_end_7="Keine Fotos mehr. Fügen Sie weitere Freunde hinzu, um Ihr wahres Leben mit ihnen zu teilen."
photo_copy_8="Fügen Sie mich zu gin-default - Widget Social Network hinzu, teilen Sie das wahre Leben mit mir! Meine ID:"
photo_tips_8="An ihre Homescreens gesendet! Laden Sie mehr Freunde ein, Ihr wahres Leben mit ihnen zu teilen."
photo_end_8="Keine Fotos mehr. Fügen Sie weitere Freunde hinzu, um Ihr wahres Leben mit ihnen zu teilen."
photo_copy_9="Nehmen Sie die Fotoherausforderung aus dem wirklichen Leben an, fügen Sie mich zu gin-default hinzu. Meine ID:"
photo_tips_9="An ihre Homescreens gesendet! Laden Sie mehr Freunde ein, Ihr wahres Leben mit ihnen zu teilen."
photo_end_9="Keine Fotos mehr. Fügen Sie weitere Freunde hinzu, um Ihr wahres Leben mit ihnen zu teilen."
photo_copy_10="Ich möchte, dass du auf meinem Homescreen bist, füge mich auf gin-default hinzu. Meine ID:"
photo_tips_10="An ihre Homescreens gesendet! Es würde mehr Spaß machen, wenn Sie mehr Freunde hinzufügen."
photo_end_10="Keine Fotos mehr. Fügen Sie weitere Freunde hinzu, um Ihr wahres Leben miteinander zu teilen."
photo_copy_11="Ich möchte, dass du auf meinem Homescreen bist, füge mich auf gin-default hinzu. Meine ID:"
photo_tips_11="An ihre Homescreens gesendet! Fügen Sie weitere Freunde hinzu, um Ihre Fotos an deren Homescreens zu senden."
photo_end_11="Anscheinend sind dir die Fotos deiner Freunde ausgegangen! Fügen Sie weitere Freunde hinzu, um Ihr wahres Leben zusammen aufzunehmen."
photo_copy_12="Sei mein Homescreen-Freund, füge mich auf gin-default hinzu. Meine ID:"
photo_tips_12="An ihre Homescreens gesendet! Lade mehr Freunde zu deinem Homescreen ein und sende ihnen lustige Fotos!"
photo_end_12="Anscheinend sind dir die Fotos deiner Freunde ausgegangen! Lade mehr Freunde zu deinem Homescreen ein und schicke ihnen lustige Fotos."
photo_copy_13="Sei mein Homescreen-Freund, füge mich auf gin-default hinzu. Meine ID:"
photo_tips_13="An ihre Homescreens gesendet! Es würde mehr Spaß machen, wenn Sie mehr Homescreen-Freunde hinzufügen."
photo_end_13="Scheint, du brauchst mehr Freunde! Lade mehr Freunde zu deinem Homescreen ein und schicke ihnen lustige Fotos."
your_self_visible="Nur für mich sichtbar"
update_new_version="Neue Duett-Funktion, bitte kommen Sie zum Upgrade und erleben Sie es!"
