param_error="Parameterfel"
component_num_limit="Du kan tillfälligt inte skapa fler grupper."
friend_num_limit="Du kan tillfälligt inte lägga till fler vänner."
operation_error="Operationen misslyckades. Vänligen försök igen senare!"
char_limit="Tecknen du angav överskrider den maximala längden. Maximalt :number tecken."
first_name_limit="Efternamnet du angav överskrider den maximala längdgränsen. Max :number tecken."
last_name_limit="Förnamnet du angav överskrider den maximala längdgränsen. Max :number tecken."
first_name_required="Efternamn får inte vara tomt."
last_name_required="Förnamn får inte vara tomt."
mobile_error="Formateringsfel för telefonnummer"
mobile_required="Telefonnumret får inte vara tomt."
country_code_error="Landskodsfel"
search_key="Ange ett giltigt användar-ID eller mobilnummer."
is_add_friend="Lägg till vänförfrågan har skickats."
system_error="Systemfel"
msg_code_error="Verifieringskodsformatfel"
first_name_length="Efternamn är för långt."
friends_exist="Användaren hittades inte"
last_name_length="Förnamn är för långt."
content_length="Högst 200 tecken"
he_friend_num_limit="Ditt eller användarens antal vänner har nått gränsen."
sign_error="Signaturverifiering misslyckades"
is_friends="Användaren har varit din vän."
sms_friend_tips="Lägg till mig på gin-default."
photo_tips="Laddades upp! Lägg till fler vänner för att dela det verkliga livet tillsammans"
message_limit="Du skickar sms för ofta. Vänligen försök igen senare."
copy_friend_tips="Lägg till mig på gin-default."
no_add_friend_self="Du kan inte lägga till dig själv som vän."
gin-default_slogan="Låt oss spela in det verkliga livet tillsammans!"
gin-default_helper="gin-default guide"
bind_mobile_error="Telefonnumret har kopplats till ett annat konto."
bound_mobile="Bindningen misslyckades. Vänligen försök igen senare."
not_add_self_friend="Du kan inte lägga till dig själv som vän."
address_book_tips="Synkronisera dina kontakter för att hitta vänner som redan finns på gin-default. Dina kontaktuppgifter kommer att skickas till gin-default för att förbättra din upplevelse och låta dig och andra hitta vänner."
follow_user="följde dig!"
notification_friends=":name har blivit din \"Bara oss\"-vän! Prova att skicka bilder till dem!"
notification_like=":name gillade dig bara!"
notification_comment=":name kommenterade dig precis, kolla in det!"
notification_friend_apply=":name skickade en vänförfrågan till dig."
notification_friend_send_picture=":name har lagt upp ett nytt foto."
notification_user_register="Kom och ta ett foto! Spela in det verkliga livet med dina vänner tillsammans!"
notification_friend_register=":name finns också på gin-default. Lägg till?"
notification_memory=":name, du har ett nytt minne."
notification_wait_add_friend=":name, dina vänner väntar!"
notification_touch=":name rörde vid ditt foto💓"
notification_follow_user=":name följde dig!"
photo_copy_1="Jag har lagt till dig på (gin-default). Ladda ner den här appen för att tillåta min vänförfrågan.Mitt ID:"
photo_tips_1="Laddades upp! Lägg till fler vänner för att dela det verkliga livet tillsammans"
photo_end_1="Inga fler vänners stunder. Ta ett foto eller lägg till fler vänner."
photo_copy_2="Lägg till mig på gin-default. Mitt ID:"
photo_tips_2="Laddades upp! Lägg till fler vänner för att dela det verkliga livet tillsammans"
photo_end_2="Inga fler vänners stunder. Ta ett foto eller lägg till fler vänner."
photo_copy_3="Lägg till mig på gin-default så att vi kan dela bilder på vår startskärm. Mitt ID:"
photo_tips_3="Skickat till deras hemskärmar! Lägg till fler vänner för att dela dina verkliga liv på dina hemskärmar."
photo_end_3="Inga fler bilder. Lägg till fler vänner för att dela dina verkliga liv på dina hemskärmar."
photo_copy_4="Lägg till mig på gin-default, jag har bilder att skicka till din startskärm. Mitt ID:"
photo_tips_4="Skickat till deras hemskärmar! Lägg till fler vänner för att dela dina verkliga liv på dina hemskärmar."
photo_end_4="Inga fler bilder. Lägg till fler vänner för att dela dina verkliga liv på dina hemskärmar."
photo_copy_5="Lägg till mig på gin-default, det nya sociala nätverket för widgeten! Mitt ID:"
photo_tips_5="Skickat till deras hemskärmar! Lägg till fler vänner för att dela dina verkliga liv på dina hemskärmar."
photo_end_5="Inga fler bilder. Bjud in fler vänner att dela dina verkliga liv på dina hemskärmar."
photo_copy_6="Lägg till mig på gin-default - Widget Social Network, allt är klart utom du!"
photo_tips_6="Skickat till deras hemskärmar! Bjud in fler vänner att dela ditt verkliga liv med dem."
photo_end_6="Inga fler bilder. Lägg till fler vänner för att dela ditt verkliga liv med dem."
photo_copy_7="Lägg till mig på gin-default, allt är klart utom du! Mitt ID:"
photo_tips_7="Skickat till deras hemskärmar! Bjud in fler vänner att dela ditt verkliga liv med dem."
photo_end_7="Inga fler bilder. Lägg till fler vänner för att dela ditt verkliga liv med dem."
photo_copy_8="Lägg till mig på gin-default - Widget Social Network, dela det verkliga livet med mig! Mitt ID:"
photo_tips_8="Skickat till deras hemskärmar! Bjud in fler vänner att dela ditt verkliga liv med dem."
photo_end_8="Inga fler bilder. Lägg till fler vänner för att dela ditt verkliga liv med dem."
photo_copy_9="Acceptera den verkliga fotoutmaningen, Lägg till mig på gin-default. Mitt ID:"
photo_tips_9="Skickat till deras hemskärmar! Bjud in fler vänner att dela ditt verkliga liv med dem."
photo_end_9="Inga fler bilder. Lägg till fler vänner för att dela ditt verkliga liv med dem."
photo_copy_10="Jag vill att du ska vara på min startskärm, lägg till mig på gin-default. Mitt ID:"
photo_tips_10="Skickat till deras hemskärmar! Det skulle vara roligare om du lägger till fler vänner."
photo_end_10="Inga fler bilder. Lägg till fler vänner för att dela era verkliga liv tillsammans."
photo_copy_11="Jag vill att du ska vara på min startskärm, lägg till mig på gin-default. Mitt ID:"
photo_tips_11="Skickat till deras hemskärmar! Lägg till fler vänner för att skicka dina foton till deras hemskärmar."
photo_end_11="Du verkar ha slut på vänners bilder! Lägg till fler vänner för att spela in era verkliga liv tillsammans."
photo_copy_12="Var min hemskärmsvän, lägg till mig på gin-default. Mitt ID:"
photo_tips_12="Skickat till deras hemskärmar! Bjud in fler vänner till din startskärm och skicka roliga bilder till dem!"
photo_end_12="Du verkar ha slut på vänners bilder! Bjud in fler vänner till din startskärm och skicka roliga bilder till dem."
photo_copy_13="Var min hemskärmsvän, lägg till mig på gin-default. Mitt ID:"
photo_tips_13="Skickat till deras hemskärmar! Det skulle vara roligare om du lägger till fler hemskärmsvänner."
photo_end_13="Du verkar behöva fler vänner! Bjud in fler vänner till din startskärm och skicka roliga bilder till dem."
your_self_visible="Bara synlig för mig"
update_new_version="Ny duettfunktion, kom gärna för att uppgradera och uppleva den!"
