param_error="Iphutha lepharamitha"
component_num_limit="Okwamanje awukwazi ukudala amaqembu engeziwe."
friend_num_limit="Okwamanje awukwazi ukwengeza abangani abengeziwe."
operation_error="Ukusebenza kuhlulekile. Sicela uzame futhi ngemva kwesikhashana!"
char_limit="Izinhlamvu ozifakile zeqa umkhawulo wobude obuphelele. Ubuningi :number izinhlamvu."
first_name_limit="Isibongo osifakile singaphezu komkhawulo wobude obubekiwe. Ubuningi :number izinhlamvu."
last_name_limit="Igama lokuqala olifakile lingaphezu komkhawulo wobude obuningi. Ubuningi :number izinhlamvu."
first_name_required="Isibongo asikwazi ukungabi nalutho."
last_name_required="Igama lokuqala alikwazi ukungabi nalutho."
mobile_error="Iphutha lefomethi yenombolo yocingo"
mobile_required="Inombolo yocingo ayikwazi ukungabi nalutho."
country_code_error="Iphutha lekhodi yezwe"
search_key="Sicela ufake i-id yomsebenzisi evumelekile noma inombolo yeselula."
is_add_friend="Faka isicelo sobungani sithunyelwe."
system_error="Iphutha lesistimu"
msg_code_error="Iphutha lefomethi yekhodi yokuqinisekisa"
first_name_length="Isibongo side kakhulu."
friends_exist="Umsebenzisi Akatholakali"
last_name_length="Igama Lokuqala lide kakhulu."
content_length="Ubuningi bezinhlamvu ezingu-200"
he_friend_num_limit="Inombolo yakho noma yomsebenzisi yabangane ifinyelele umkhawulo."
sign_error="Ukuqinisekisa isiginesha kuhlulekile"
is_friends="Umsebenzisi ube ngumngane wakho."
sms_friend_tips="Ngingeze ku-JustUs."
photo_tips="Ilayishwe ngempumelelo! Engeza abangani abengeziwe ukuze nihlanganyele ukuphila kwangempela ndawonye"
message_limit="Uthumela imiyalezo kaningi kakhulu. Sicela uzame futhi emuva kwesikhathi."
copy_friend_tips="Ngingeze ku-JustUs."
no_add_friend_self="Awukwazi ukuzingeza wena njengomngane."
justus_slogan="Masiqophe impilo yangempela ndawonye!"
justus_helper="I-JustUs Guide"
bind_mobile_error="Inombolo yocingo iboshelwe kwenye i-akhawunti."
bound_mobile="Ukubophezela kuhlulekile. Sicela uzame futhi emuva kwesikhathi."
not_add_self_friend="Awukwazi ukuzengeza wena njengomngane."
address_book_tips="Vumelanisa abathintwayo bakho ukuze uthole abangani asebevele baku-JustUs. Idatha yoxhumana nabo izothunyelwa ku-JustUs ukuze uthuthukise ulwazi lwakho futhi ikuvumele wena nabanye ukuthi nithole abangani."
follow_user="ngikulandele!"
notification_friends="U-:name usephenduke umngane wakho othi \"JustUs\"! Zama ukubathumelela izithombe!"
notification_like=":name ukuthandile nje!"
notification_comment="U-:name usanda kubeka amazwana ngawe, kuhlole!"
notification_friend_apply="U-:name ukuthumelele isicelo sobungani."
notification_friend_send_picture="U-:name uthumele isithombe esisha."
notification_user_register="Woza uthathe isithombe! Qopha impilo yangempela nabangani bakho ndawonye!"
notification_friend_register=":name igama liku-JustUs. Engeza?"
notification_memory=":name, unenkumbulo entsha."
notification_wait_add_friend=":name, abangani bakho balindile!"
notification_touch="i-:name ithinte isithombe sakho💓"
notification_follow_user=":name ngikulandele!"
photo_copy_1="Ngikwengeze ku (JustUs). Landa lolu hlelo lokusebenza ukuze uvumele isicelo sami sobungani.I-ID yami:"
photo_tips_1="Ilayishwe ngempumelelo! Engeza abangani abengeziwe ukuze nihlanganyele ukuphila kwangempela ndawonye"
photo_end_1="Azisekho izikhathi zabangane. Thatha isithombe noma engeza abangani abengeziwe."
photo_copy_2="Ngingeze ku-JustUs.I-ID yami:"
photo_tips_2="Ilayishwe ngempumelelo! Engeza abangani abengeziwe ukuze nihlanganyele ukuphila kwangempela ndawonye"
photo_end_2="Azisekho izikhathi zabangane. Thatha isithombe noma engeza abangani abengeziwe."
photo_copy_3="Ngingeze ku-JustUs ukuze sabelane ngezithombe esikrinini sethu sasekhaya. I-ID yami:"
photo_tips_3="Ithunyelwe kuzikrini zabo zasekhaya! Engeza abangani abengeziwe ukuze wabelane ngezimpilo zakho zangempela kuzikrini zakho zasekhaya."
photo_end_3="Azisekho izithombe. Engeza abangani abengeziwe ukuze wabelane ngezimpilo zakho zangempela kuzikrini zakho zasekhaya."
photo_copy_4="Ngingeze ku-JustUs, nginezithombe engingazithumela esikrinini sakho sasekhaya. I-ID yami:"
photo_tips_4="Ithunyelwe kuzikrini zabo zasekhaya! Engeza abangani abengeziwe ukuze wabelane ngezimpilo zakho zangempela kuzikrini zakho zasekhaya."
photo_end_4="Azisekho izithombe. Engeza abangani abengeziwe ukuze wabelane ngezimpilo zakho zangempela kuzikrini zakho zasekhaya."
photo_copy_5="Ngingeze ku-JustUs, inkundla yokuxhumana yewijethi entsha! I-ID yami:"
photo_tips_5="Ithunyelwe kuzikrini zabo zasekhaya! Engeza abangani abengeziwe ukuze wabelane ngezimpilo zakho zangempela kuzikrini zakho zasekhaya."
photo_end_5="Azisekho izithombe. Mema abangani abengeziwe ukuze wabelane ngezimpilo zakho zangempela kuzikrini zakho zasekhaya."
photo_copy_6="Ngingeze ku-JustUs - Widget Social Network, konke kumi ngomumo ngaphandle kwakho!"
photo_tips_6="Ithunyelwe kuzikrini zabo zasekhaya! Mema abangani abaningi ukuze wabelane ngezimpilo zakho zangempela nabo."
photo_end_6="Azisekho izithombe. Engeza abangani abengeziwe ukuze wabelane ngezimpilo zakho zangempela nabo."
photo_copy_7="Ngingeze ku-JustUs, konke sekulungile ngaphandle kwakho! I-ID yami:"
photo_tips_7="Ithunyelwe kuzikrini zabo zasekhaya! Mema abangani abaningi ukuze wabelane ngezimpilo zakho zangempela nabo."
photo_end_7="Azisekho izithombe. Engeza abangani abengeziwe ukuze wabelane ngezimpilo zakho zangempela nabo."
photo_copy_8="Ngingeze ku-JustUs - Widget Social Network, wabelane nami ngempilo yangempela! I-ID yami:"
photo_tips_8="Ithunyelwe kuzikrini zabo zasekhaya! Mema abangani abaningi ukuze wabelane ngezimpilo zakho zangempela nabo."
photo_end_8="Azisekho izithombe. Engeza abangani abengeziwe ukuze wabelane ngezimpilo zakho zangempela nabo."
photo_copy_9="Yamukela inselele yesithombe sempilo yangempela, Ngingeze ku-JustUs. I-ID yami:"
photo_tips_9="Ithunyelwe kuzikrini zabo zasekhaya! Mema abangani abaningi ukuze wabelane ngezimpilo zakho zangempela nabo."
photo_end_9="Azisekho izithombe. Engeza abangani abengeziwe ukuze wabelane ngezimpilo zakho zangempela nabo."
photo_copy_10="Ngifuna ukuthi ube kusikrini sami sasekhaya, ungingeze ku-JustUs. I-ID yami:"
photo_tips_10="Ithunyelwe kuzikrini zabo zasekhaya! Kungaba mnandi kakhulu uma ungeza abangani abaningi."
photo_end_10="Azisekho izithombe. Engeza abangani abengeziwe ukuze nabelane ngezimpilo zenu zangempela ndawonye."
photo_copy_11="Ngifuna ukuthi ube kusikrini sami sasekhaya, ungingeze ku-JustUs. I-ID yami:"
photo_tips_11="Ithunyelwe kuzikrini zabo zasekhaya! Engeza abangani abengeziwe ukuze uthumele izithombe zakho kuzikrini zabo zasekhaya."
photo_end_11="Kubonakala sengathi uphelelwe izithombe zabangane! Engeza abangani abengeziwe ukuze uqophe izimpilo zenu zangempela ndawonye."
photo_copy_12="Yiba umngane wami wesikrini sasekhaya, ngingeze ku-JustUs. I-ID yami:"
photo_tips_12="Ithunyelwe kuzikrini zabo zasekhaya! Mema abangani abengeziwe esikrinini sakho sasekhaya futhi ubathumele izithombe ezijabulisayo!"
photo_end_12="Kubonakala sengathi uphelelwe izithombe zabangane! Mema abangani abengeziwe esikrinini sakho sasekhaya futhi ubathumele izithombe ezijabulisayo."
photo_copy_13="Yiba umngane wami wesikrini sasekhaya, ngingeze ku-JustUs. I-ID yami:"
photo_tips_13="Ithunyelwe kuzikrini zabo zasekhaya! Kungaba mnandi kakhulu uma ungeza abangani abengeziwe besikrini sasekhaya."
photo_end_13="Kubonakala sengathi udinga abangani abaningi! Mema abangani abengeziwe esikrinini sakho sasekhaya futhi ubathumele izithombe ezijabulisayo."
your_self_visible="Kubonakala kimi kuphela"
update_new_version="Umsebenzi omusha we-duet, sicela uze uzothuthukisa futhi ujabulele!"
