param_error="Грешка в параметъра"
component_num_limit="Временно не можете да създадете повече групи."
friend_num_limit="Временно не можете да добавите още приятели."
operation_error="Операцията се провали. Моля, опитайте отново по-късно!"
char_limit="Въведените от вас знаци надвишават ограничението за максимална дължина. Максимумът :number знака."
first_name_limit="Въведеното от вас „Фамилно име“ надвишава ограничението за максимална дължина. Максимумът :number знака."
last_name_limit="Въведеното от вас „Първо име“ надвишава ограничението за максимална дължина. Максимумът :number знака."
first_name_required="Фамилия не може да бъде празна."
last_name_required="„Първо име“ не може да бъде празно."
mobile_error="Грешка във формата на телефонния номер"
mobile_required="Телефонният номер не може да бъде празен."
country_code_error="Грешка в кода на държавата"
search_key="Моля, въведете валиден потребителски идентификатор или мобилен номер."
is_add_friend="Заявката за добавяне на приятел е изпратена."
system_error="Системна грешка"
msg_code_error="Грешка във формата на кода за потвърждение"
first_name_length="Фамилното име е твърде дълго."
friends_exist="Потребителят не е намерен"
last_name_length="„Първо име“ е твърде дълго."
content_length="Максимум 200 знака"
he_friend_num_limit="Броят на вашите или на потребителя е достигнал лимита."
sign_error="Проверката на подписа не бе успешно"
is_friends="Потребителят е бил ваш приятел."
sms_friend_tips="Добавете ме в gin-default."
photo_tips="Качена успешно! Добавете още приятели, за да споделяте реалния живот заедно"
message_limit="Изпращате текстови съобщения твърде често. Моля, опитайте отново по-късно."
copy_friend_tips="Добавете ме в gin-default."
no_add_friend_self="Не можете да добавите себе си като приятел."
gin-default_slogan="Да запишем истинския живот заедно!"
gin-default_helper="Ръководство за gin-default"
bind_mobile_error="Телефонният номер е свързан с друг акаунт."
bound_mobile="Обвързването не бе успешно. Моля, опитайте отново по-късно."
not_add_self_friend="Не можете да добавите себе си като приятел."
address_book_tips="Синхронизирайте контактите си, за да намерите приятели, които вече са в gin-default. Данните за вашите контакти ще бъдат изпратени до gin-default, за да подобрите изживяването ви и да позволите на вас и другите да намирате приятели."
follow_user="следвам те!"
notification_friends=":name стана ваш приятел „Само ние“! Опитайте да им изпратите снимки!"
notification_like=":name просто те хареса!"
notification_comment=":name току-що ви коментира, вижте!"
notification_friend_apply=":name ви изпрати молба за приятелство."
notification_friend_send_picture=":name публикува нова снимка."
notification_user_register="Елате и направете снимка! Запишете реалния живот с приятелите си заедно!"
notification_friend_register=":name също е на gin-default. Добавяне?"
notification_memory=":name, имате нов спомен."
notification_wait_add_friend=":name, приятелите ви чакат!"
notification_touch=":name докосна вашата снимка💓"
notification_follow_user=":name следвам те!"
photo_copy_1="Добавих ви в (gin-default). Изтеглете това приложение, за да разрешите молбата ми за приятелство.Моят идентификационен номер:"
photo_tips_1="Качена успешно! Добавете още приятели, за да споделяте реалния живот заедно"
photo_end_1="Няма повече моменти на приятели. Направете снимка или добавете още приятели."
photo_copy_2="Добавете ме в gin-default.Моят идентификационен номер:"
photo_tips_2="Качена успешно! Добавете още приятели, за да споделяте реалния живот заедно"
photo_end_2="Няма повече моменти на приятели. Направете снимка или добавете още приятели."
photo_copy_3="Добавете ме в gin-default, за да можем да споделяме снимки на нашия начален екран. Моят идентификационен номер:"
photo_tips_3="Изпратени на началните им екрани! Добавете още приятели, за да споделяте истинския си живот на началните си екрани."
photo_end_3="Няма повече снимки. Добавете още приятели, за да споделяте истинския си живот на началните си екрани."
photo_copy_4="Добавете ме в gin-default, имам снимки, които да изпратя на началния ви екран. Моят идентификационен номер:"
photo_tips_4="Изпратени на началните им екрани! Добавете още приятели, за да споделяте истинския си живот на началните си екрани."
photo_end_4="Няма повече снимки. Добавете още приятели, за да споделяте истинския си живот на началните си екрани."
photo_copy_5="Добавете ме в gin-default, новата социална мрежа с джаджи! Моят идентификационен номер:"
photo_tips_5="Изпратени на началните им екрани! Добавете още приятели, за да споделяте истинския си живот на началните си екрани."
photo_end_5="Няма повече снимки. Поканете повече приятели да споделят истинския си живот на началните си екрани."
photo_copy_6="Добавете ме в gin-default - Widget Social Network, всичко е готово освен вас!"
photo_tips_6="Изпратени на началните им екрани! Поканете повече приятели, за да споделите истинския си живот с тях."
photo_end_6="Няма повече снимки. Добавете още приятели, за да споделите истинския си живот с тях."
photo_copy_7="Добавете ме в gin-default, всичко е готово освен вас! Моят идентификационен номер:"
photo_tips_7="Изпратени на началните им екрани! Поканете повече приятели, за да споделите истинския си живот с тях."
photo_end_7="Няма повече снимки. Добавете още приятели, за да споделите истинския си живот с тях."
photo_copy_8="Добавете ме в gin-default - Widget Social Network, споделете реалния живот с мен! Моят идентификационен номер:"
photo_tips_8="Изпратени на началните им екрани! Поканете повече приятели, за да споделите истинския си живот с тях."
photo_end_8="Няма повече снимки. Добавете още приятели, за да споделите истинския си живот с тях."
photo_copy_9="Приемете предизвикателството за снимки в реалния живот, Добавете ме в gin-default. Моят идентификационен номер:"
photo_tips_9="Изпратени на началните им екрани! Поканете повече приятели, за да споделите истинския си живот с тях."
photo_end_9="Няма повече снимки. Добавете още приятели, за да споделите истинския си живот с тях."
photo_copy_10="Искам да сте на началния ми екран, добавете ме в gin-default. Моят идентификационен номер:"
photo_tips_10="Изпратени на началните им екрани! Ще бъде по-забавно, ако добавите още приятели."
photo_end_10="Няма повече снимки. Добавете още приятели, за да споделите истинския си живот заедно."
photo_copy_11="Искам да сте на началния ми екран, добавете ме в gin-default. Моят идентификационен номер:"
photo_tips_11="Изпратени на началните им екрани! Добавете още приятели, за да изпратите вашите снимки на началните им екрани."
photo_end_11="Изглежда, че сте свършили снимките на приятели! Добавете още приятели, за да запишете истинския си живот заедно."
photo_copy_12="Бъдете мой приятел на началния екран, добавете ме в gin-default. Моят идентификационен номер:"
photo_tips_12="Изпратени на началните им екрани! Поканете още приятели на началния си екран и им изпратете забавни снимки!"
photo_end_12="Изглежда, че сте свършили снимките на приятели! Поканете още приятели на началния си екран и им изпратете забавни снимки."
photo_copy_13="Бъдете мой приятел на началния екран, добавете ме в gin-default. Моят идентификационен номер:"
photo_tips_13="Изпратени на началните им екрани! Ще бъде по-забавно, ако добавите още приятели на началния екран."
photo_end_13="Изглежда, че имате нужда от повече приятели! Поканете още приятели на началния си екран и им изпратете забавни снимки."
your_self_visible="Вижда се само за мен"
update_new_version="Нова дуетна функция, моля, елате да надстроите и я изживейте!"
