param_error="שגיאת פרמטר"
component_num_limit="באופן זמני אינך יכול ליצור קבוצות נוספות."
friend_num_limit="באופן זמני אינך יכול להוסיף חברים נוספים."
operation_error="פעולה נכשלה. בבקשה נסה שוב מאוחר יותר!"
char_limit="התווים שהזנת חורגים ממגבלת האורך המקסימלית. המקסימום number: תווים."
first_name_limit="שם המשפחה שהזנת חורג ממגבלת האורך המקסימלית. המקסימום number: תווים."
last_name_limit="ה\"שם הפרטי\" שהזנת חורג ממגבלת האורך המקסימלית. המקסימום number: תווים."
first_name_required="שם משפחה לא יכול להיות ריק."
last_name_required="ה\"שם הפרטי\" לא יכול להיות ריק."
mobile_error="שגיאה בפורמט מספר טלפון"
mobile_required="מספר הטלפון לא יכול להיות ריק."
country_code_error="שגיאת קוד מדינה"
search_key="אנא הזן מזהה משתמש חוקי או מספר נייד."
is_add_friend="בקשת חברות הוסף נשלחה."
system_error="שגיאת מערכת"
msg_code_error="שגיאה בפורמט קוד אימות"
first_name_length="שם משפחה ארוך מדי."
friends_exist="המשתמש לא נמצא"
last_name_length="ה\"שם הפרטי\" ארוך מדי."
content_length="מקסימום 200 תווים"
he_friend_num_limit="מספר החברים שלך או של המשתמש הגיע למגבלה."
sign_error="אימות החתימה נכשל"
is_friends="המשתמש היה חבר שלך."
sms_friend_tips="הוסף אותי ב-gin-default."
photo_tips="הועלה בהצלחה! הוסף חברים נוספים כדי לחלוק יחד את החיים האמיתיים"
message_limit="אתה שולח הודעות טקסט לעתים קרובות מדי. בבקשה נסה שוב מאוחר יותר."
copy_friend_tips="הוסף אותי ב-gin-default."
no_add_friend_self="אתה לא יכול להוסיף את עצמך כחבר."
gin-default_slogan="בואו לתעד את החיים האמיתיים ביחד!"
gin-default_helper="מדריך gin-default"
bind_mobile_error="מספר הטלפון נקשר לחשבון אחר."
bound_mobile="הכריכה נכשלה. בבקשה נסה שוב מאוחר יותר."
not_add_self_friend="אתה לא יכול להוסיף את עצמך כחבר."
address_book_tips="סנכרן את אנשי הקשר שלך כדי למצוא חברים שכבר נמצאים ב-gin-default. נתוני אנשי הקשר שלך יישלחו ל-gin-default כדי לשפר את החוויה שלך ולאפשר לך ולאחרים למצוא חברים."
follow_user="עקב אחריך!"
notification_friends=":name הפך לחבר \"רק אנחנו\" שלך! נסה לשלוח להם תמונות!"
notification_like=":name פשוט אהבתי אותך!"
notification_comment=":name בדיוק הגיב עליך, בדוק את זה!"
notification_friend_apply=":name שלח לך בקשת חברות."
notification_friend_send_picture=":name פרסם תמונה חדשה."
notification_user_register="בואו לצלם! הקלט את החיים האמיתיים עם החברים שלך ביחד!"
notification_friend_register=":name נמצא גם ב-gin-default. לְהוֹסִיף?"
notification_memory=":name, יש לך זיכרון חדש."
notification_wait_add_friend=":name, החברים שלך מחכים!"
notification_touch=":name הקיש על התמונה שלך💓"
notification_follow_user=":name עקב אחריך!"
photo_copy_1="הוספתי אותך ב- (gin-default). הורד את האפליקציה הזו כדי לאפשר את בקשת החברות שלי.ID:"
photo_tips_1="הועלה בהצלחה! הוסף חברים נוספים כדי לחלוק יחד את החיים האמיתיים"
photo_end_1="אין יותר רגעים של חברים. צלם תמונה או הוסף חברים נוספים."
photo_copy_2="הוסף אותי ב-gin-default. ID:"
photo_tips_2="הועלה בהצלחה! הוסף חברים נוספים כדי לחלוק יחד את החיים האמיתיים"
photo_end_2="אין יותר רגעים של חברים. צלם תמונה או הוסף חברים נוספים."
photo_copy_3="הוסף אותי ב-gin-default כדי שנוכל לשתף תמונות למסך הבית שלנו. התעודת זהות שלי:"
photo_tips_3="נשלח למסכי הבית שלהם! הוסף חברים נוספים כדי לשתף את חייך האמיתיים במסכי הבית שלך."
photo_end_3="אין יותר תמונות. הוסף חברים נוספים כדי לשתף את חייך האמיתיים במסכי הבית שלך."
photo_copy_4="הוסף אותי ב-gin-default, יש לי תמונות לשלוח למסך הבית שלך. התעודת זהות שלי:"
photo_tips_4="נשלח למסכי הבית שלהם! הוסף חברים נוספים כדי לשתף את חייך האמיתיים במסכי הבית שלך."
photo_end_4="אין יותר תמונות. הוסף חברים נוספים כדי לשתף את חייך האמיתיים במסכי הבית שלך."
photo_copy_5="הוסף אותי ל-gin-default, הרשת החברתית הווידג'ט החדשה! התעודת זהות שלי:"
photo_tips_5="נשלח למסכי הבית שלהם! הוסף חברים נוספים כדי לשתף את חייך האמיתיים במסכי הבית שלך."
photo_end_5="אין יותר תמונות. הזמן חברים נוספים לשתף את חייך האמיתיים במסכי הבית שלך."
photo_copy_6="הוסף אותי ב-gin-default - Widget Social Network, הכל מוכן חוץ ממך!"
photo_tips_6="נשלח למסכי הבית שלהם! הזמן חברים נוספים לשתף איתם את חייך האמיתיים."
photo_end_6="אין יותר תמונות. הוסף חברים נוספים כדי לשתף איתם את החיים האמיתיים שלך."
photo_copy_7="הוסף אותי ב-gin-default, הכל מוכן חוץ ממך! התעודת זהות שלי:"
photo_tips_7="נשלח למסכי הבית שלהם! הזמן חברים נוספים לשתף איתם את חייך האמיתיים."
photo_end_7="אין יותר תמונות. הוסף חברים נוספים כדי לשתף איתם את החיים האמיתיים שלך."
photo_copy_8="הוסף אותי ב-gin-default - Widget Social Network, שתף איתי את החיים האמיתיים! התעודת זהות שלי:"
photo_tips_8="נשלח למסכי הבית שלהם! הזמן חברים נוספים לשתף איתם את חייך האמיתיים."
photo_end_8="אין יותר תמונות. הוסף חברים נוספים כדי לשתף איתם את החיים האמיתיים שלך."
photo_copy_9="קבל את אתגר הצילום בחיים האמיתיים, הוסף אותי ב-gin-default. התעודת זהות שלי:"
photo_tips_9="נשלח למסכי הבית שלהם! הזמן חברים נוספים לשתף איתם את חייך האמיתיים."
photo_end_9="אין יותר תמונות. הוסף חברים נוספים כדי לשתף איתם את החיים האמיתיים שלך."
photo_copy_10="אני רוצה שתהיה על מסך הבית שלי, הוסף אותי ב-gin-default. התעודת זהות שלי:"
photo_tips_10="נשלח למסכי הבית שלהם! זה יהיה יותר כיף אם תוסיף עוד חברים."
photo_end_10="אין יותר תמונות. הוסף חברים נוספים כדי לשתף את חייך האמיתיים יחד."
photo_copy_11="אני רוצה שתהיה על מסך הבית שלי, הוסף אותי ב-gin-default. התעודת זהות שלי:"
photo_tips_11="נשלח למסכי הבית שלהם! הוסף חברים נוספים כדי לשלוח את התמונות שלך למסכי הבית שלהם."
photo_end_11="נראה שנגמרו לך התמונות של חברים! הוסף חברים נוספים כדי להקליט את חייך האמיתיים יחד."
photo_copy_12="היה חבר שלי למסך הבית, הוסף אותי ב-gin-default. התעודת זהות שלי:"
photo_tips_12="נשלח למסכי הבית שלהם! הזמן חברים נוספים למסך הבית שלך ושלח להם תמונות מהנות!"
photo_end_12="נראה שנגמרו לך התמונות של חברים! הזמן חברים נוספים למסך הבית שלך ושלח להם תמונות מהנות."
photo_copy_13="היה חבר שלי למסך הבית, הוסף אותי ב-gin-default. התעודת זהות שלי:"
photo_tips_13="נשלח למסכי הבית שלהם! זה יהיה יותר כיף אם תוסיף עוד חברים למסך הבית."
photo_end_13="נראה שאתה צריך עוד חברים! הזמן חברים נוספים למסך הבית שלך ושלח להם תמונות מהנות."
your_self_visible="גלוי רק לי"
update_new_version="פונקציית דואט חדשה, בבקשה בואו לשדרג ולחוות אותה!"
