param_error="Eroare de parametru"
component_num_limit="Nu puteți, temporar, să creați mai multe grupuri."
friend_num_limit="Nu puteți adăuga temporar mai mulți prieteni."
operation_error="Operațiunea a eșuat. Vă rugăm să încercați din nou mai târziu!"
char_limit="Caracterele pe care le-ați introdus depășesc limita maximă de lungime. Maximul :number caractere."
first_name_limit="„Numele” introdus depășește limita maximă de lungime. Maximul :number caractere."
last_name_limit="„Prenumele” pe care l-ați introdus depășește limita maximă de lungime. Maximul :number caractere."
first_name_required="„Numele de familie” nu poate fi necompletat."
last_name_required="„Prenumele” nu poate fi necompletat."
mobile_error="Eroare de format al numărului de telefon"
mobile_required="Numărul de telefon nu poate fi gol."
country_code_error="Eroare de cod de țară"
search_key="Vă rugăm să introduceți un ID de utilizator valid sau un număr de telefon mobil."
is_add_friend="Cererea de adăugare a prieteniei a fost trimisă."
system_error="Eroare de sistem"
msg_code_error="Eroare de format cod de verificare"
first_name_length="„Numele” este prea lung."
friends_exist="Utilizator nu a fost găsit"
last_name_length="„Prenumele” este prea lung."
content_length="Maximum 200 de caractere"
he_friend_num_limit="Numărul dvs. de prieteni sau al utilizatorului a atins limita."
sign_error="Verificarea semnaturii a eșuat"
is_friends="Utilizatorul a fost prietenul tău."
sms_friend_tips="Adaugă-mă pe gin-default."
photo_tips="Încărcat cu succes! Adăugați mai mulți prieteni pentru a împărtăși viața reală împreună"
message_limit="Trimiți mesaje text prea des. Vă rugăm să încercați din nou mai târziu."
copy_friend_tips="Adaugă-mă pe gin-default."
no_add_friend_self="Nu te poți adăuga ca prieten."
gin-default_slogan="Să înregistrăm împreună viața reală!"
gin-default_helper="Ghidul gin-default"
bind_mobile_error="Numărul de telefon a fost legat de alt cont."
bound_mobile="Legarea a eșuat. Vă rugăm să încercați din nou mai târziu."
not_add_self_friend="Nu te poți adăuga ca prieten."
address_book_tips="Sincronizează-ți contactele pentru a găsi prieteni deja pe gin-default. Datele dvs. de contact vor fi trimise către gin-default pentru a vă îmbunătăți experiența și pentru a vă permite dvs. și altora să vă găsiți prieteni."
follow_user="te-am urmarit!"
notification_friends=":name a devenit prietenul tău „Doar noi”! Încearcă să le trimiți fotografii!"
notification_like=":name doar te-a plăcut!"
notification_comment=":name tocmai te-a comentat, vezi!"
notification_friend_apply=":name v-a trimis o cerere de prietenie."
notification_friend_send_picture=":name a postat o fotografie nouă."
notification_user_register="Vino și fă o fotografie! Înregistrați viața reală împreună cu prietenii tăi!"
notification_friend_register=":name este și pe gin-default. Adăuga?"
notification_memory=":name, ai o nouă memorie."
notification_wait_add_friend=":name, prietenii tăi așteaptă!"
notification_touch=":name ți-a atins fotografia💓"
notification_follow_user=":name te-am urmarit!"
photo_copy_1="Te-am adăugat pe (gin-default). Descărcați această aplicație pentru a permite cererea mea de prietenie.ID-ul meu:"
photo_tips_1="Încărcat cu succes! Adăugați mai mulți prieteni pentru a împărtăși viața reală împreună"
photo_end_1="Gata cu momentele prietenilor. Faceți o fotografie sau adăugați mai mulți prieteni."
photo_copy_2="Adaugă-mă pe gin-default.ID-ul meu:"
photo_tips_2="Încărcat cu succes! Adăugați mai mulți prieteni pentru a împărtăși viața reală împreună"
photo_end_2="Gata cu momentele prietenilor. Faceți o fotografie sau adăugați mai mulți prieteni."
photo_copy_3="Adaugă-mă pe gin-default ca să putem partaja fotografii pe ecranul nostru de pornire. ID-ul meu:"
photo_tips_3="Trimis pe ecranele lor de pornire! Adăugați mai mulți prieteni pentru a vă împărtăși viețile reale pe ecranele dvs. de pornire."
photo_end_3="Nu mai sunt fotografii. Adăugați mai mulți prieteni pentru a vă împărtăși viețile reale pe ecranele dvs. de pornire."
photo_copy_4="Adaugă-mă pe gin-default, am fotografii de trimis pe ecranul tău de pornire. ID-ul meu:"
photo_tips_4="Trimis pe ecranele lor de pornire! Adăugați mai mulți prieteni pentru a vă împărtăși viețile reale pe ecranele dvs. de pornire."
photo_end_4="Nu mai sunt fotografii. Adăugați mai mulți prieteni pentru a vă împărtăși viețile reale pe ecranele dvs. de pornire."
photo_copy_5="Adaugă-mă pe gin-default, noua rețea socială cu widget-uri! ID-ul meu:"
photo_tips_5="Trimis pe ecranele lor de pornire! Adăugați mai mulți prieteni pentru a vă împărtăși viețile reale pe ecranele dvs. de pornire."
photo_end_5="Nu mai sunt fotografii. Invitați mai mulți prieteni să vă împărtășească viețile reale pe ecranele dvs. de pornire."
photo_copy_6="Adaugă-mă pe gin-default - Widget Social Network, totul este gata, cu excepția ta!"
photo_tips_6="Trimis pe ecranele lor de pornire! Invitați mai mulți prieteni să vă împărtășească viața reală cu ei."
photo_end_6="Nu mai sunt fotografii. Adaugă mai mulți prieteni pentru a le împărtăși viețile tale reale."
photo_copy_7="Adaugă-mă pe gin-default, totul este gata, cu excepția ta! ID-ul meu:"
photo_tips_7="Trimis pe ecranele lor de pornire! Invitați mai mulți prieteni să vă împărtășească viața reală cu ei."
photo_end_7="Nu mai sunt fotografii. Adaugă mai mulți prieteni pentru a le împărtăși viețile tale reale."
photo_copy_8="Adaugă-mă pe gin-default - Widget Social Network, împărtășește-mi viața reală! ID-ul meu:"
photo_tips_8="Trimis pe ecranele lor de pornire! Invitați mai mulți prieteni să vă împărtășească viața reală cu ei."
photo_end_8="Nu mai sunt fotografii. Adaugă mai mulți prieteni pentru a le împărtăși viețile tale reale."
photo_copy_9="Acceptă provocarea foto din viața reală, adaugă-mă pe gin-default. ID-ul meu:"
photo_tips_9="Trimis pe ecranele lor de pornire! Invitați mai mulți prieteni să vă împărtășească viața reală cu ei."
photo_end_9="Nu mai sunt fotografii. Adaugă mai mulți prieteni pentru a le împărtăși viețile tale reale."
photo_copy_10="Vreau să fii pe ecranul meu de pornire, adaugă-mă pe gin-default. ID-ul meu:"
photo_tips_10="Trimis pe ecranele lor de pornire! Ar fi mai distractiv dacă adaugi mai mulți prieteni."
photo_end_10="Nu mai sunt fotografii. Adăugați mai mulți prieteni pentru a vă împărtăși viețile reale împreună."
photo_copy_11="Vreau să fii pe ecranul meu de pornire, adaugă-mă pe gin-default. ID-ul meu:"
photo_tips_11="Trimis pe ecranele lor de pornire! Adăugați mai mulți prieteni pentru a vă trimite fotografiile pe ecranele lor de pornire."
photo_end_11="Se pare că ai rămas fără fotografiile prietenilor! Adăugați mai mulți prieteni pentru a vă înregistra viața reală împreună."
photo_copy_12="Fii prietenul meu pe ecranul de pornire, adaugă-mă pe gin-default. ID-ul meu:"
photo_tips_12="Trimis pe ecranele lor de pornire! Invitați mai mulți prieteni pe ecranul dvs. de pornire și trimiteți-le fotografii distractive!"
photo_end_12="Se pare că ai rămas fără fotografiile prietenilor! Invitați mai mulți prieteni pe ecranul dvs. de pornire și trimiteți-le fotografii distractive."
photo_copy_13="Fii prietenul meu pe ecranul de pornire, adaugă-mă pe gin-default. ID-ul meu:"
photo_tips_13="Trimis pe ecranele lor de pornire! Ar fi mai distractiv dacă adăugați mai mulți prieteni pe ecranul de pornire."
photo_end_13="Se pare că ai nevoie de mai mulți prieteni! Invitați mai mulți prieteni pe ecranul dvs. de pornire și trimiteți-le fotografii distractive."
your_self_visible="Vizibil doar pentru mine"
update_new_version="Noua funcție duet, vă rugăm să veniți să faceți upgrade și să experimentați!"
