param_error="Parameterfout"
component_num_limit="U kunt tijdelijk geen groepen meer maken."
friend_num_limit="Je kunt tijdelijk geen vrienden meer toevoegen."
operation_error="Operatie mislukt. Probeer het later opnieuw!"
char_limit="De tekens die u hebt ingevoerd, overschrijden de maximale lengte. Het maximum :number tekens."
first_name_limit="De \"Achternaam\" die u heeft ingevoerd, overschrijdt de maximale lengte. Het maximum :number tekens."
last_name_limit="De door u ingevoerde \"Voornaam\" overschrijdt de maximale lengte. Het maximum :number tekens."
first_name_required="De \"Achternaam\" mag niet leeg zijn."
last_name_required="De \"Voornaam\" mag niet leeg zijn."
mobile_error="Formaatfout telefoonnummer"
mobile_required="Het telefoonnummer mag niet leeg zijn."
country_code_error="Landcodefout"
search_key="Voer een geldige gebruikers-ID of mobiel nummer in."
is_add_friend="Vriendschapsverzoek toevoegen is verzonden."
system_error="Systeemfout"
msg_code_error="Fout in formaat verificatiecode"
first_name_length="De \"Achternaam\" is te lang."
friends_exist="Gebruiker niet gevonden"
last_name_length="De \"Voornaam\" is te lang."
content_length="De maximale 200 tekens"
he_friend_num_limit="Uw of het aantal vrienden van de gebruiker heeft de limiet bereikt."
sign_error="Verificatie handtekening mislukt"
is_friends="De gebruiker is je vriend geweest."
sms_friend_tips="Voeg mij toe op JustUs."
photo_tips="Succesvol geüpload! Voeg meer vrienden toe om het echte leven samen te delen"
message_limit="Je stuurt te vaak sms'jes. Probeer het later opnieuw."
copy_friend_tips="Voeg mij toe op JustUs."
no_add_friend_self="Je kunt jezelf niet toevoegen als vriend."
justus_slogan="Laten we samen het echte leven opnemen!"
justus_helper="JustUs-gids"
bind_mobile_error="Het telefoonnummer is gekoppeld aan een ander account."
bound_mobile="Inbinden mislukt. Probeer het later opnieuw."
not_add_self_friend="Je kunt jezelf niet toevoegen als vriend."
address_book_tips="Synchroniseer je contacten om vrienden te vinden die al op JustUs zijn. Uw contactgegevens worden naar JustUs verzonden om uw ervaring te verbeteren en u en anderen in staat te stellen vrienden te vinden."
follow_user="volgde je!"
notification_friends=":name is je \"JustUs\"-vriend geworden! Probeer ze foto's te sturen!"
notification_like=":name vond je net leuk!"
notification_comment=":name heeft net op je gereageerd, check it out!"
notification_friend_apply=":name heeft je een vriendschapsverzoek gestuurd."
notification_friend_send_picture=":name heeft een nieuwe foto geplaatst."
notification_user_register="Kom en maak een foto! Neem samen met je vrienden het echte leven op!"
notification_friend_register=":name staat ook op JustUs. Toevoegen?"
notification_memory=":name, je hebt een nieuwe herinnering."
notification_wait_add_friend=":name, je vrienden wachten!"
notification_touch=":name heeft op je foto getikt💓"
notification_follow_user=":name volgde je!"
photo_copy_1="Ik heb je toegevoegd op (JustUs). Download deze app om mijn vriendschapsverzoek toe te staan.Mijn ID:"
photo_tips_1="Succesvol geüpload! Voeg meer vrienden toe om het echte leven samen te delen"
photo_end_1="Geen vriendenmomenten meer. Maak een foto of voeg meer vrienden toe."
photo_copy_2="Voeg mij toe op JustUs.Mijn ID:"
photo_tips_2="Succesvol geüpload! Voeg meer vrienden toe om het echte leven samen te delen"
photo_end_2="Geen vriendenmomenten meer. Maak een foto of voeg meer vrienden toe."
photo_copy_3="Voeg me toe op JustUs zodat we foto's kunnen delen op ons startscherm. Mijn ID:"
photo_tips_3="Verzonden naar hun homescreens! Voeg meer vrienden toe om uw echte leven op uw startschermen te delen."
photo_end_3="Geen foto's meer. Voeg meer vrienden toe om uw echte leven op uw startschermen te delen."
photo_copy_4="Voeg me toe op JustUs, ik heb foto's om naar je startscherm te sturen. Mijn ID:"
photo_tips_4="Verzonden naar hun homescreens! Voeg meer vrienden toe om uw echte leven op uw startschermen te delen."
photo_end_4="Geen foto's meer. Voeg meer vrienden toe om uw echte leven op uw startschermen te delen."
photo_copy_5="Voeg me toe op JustUs, het nieuwe sociale netwerk voor widgets! Mijn ID:"
photo_tips_5="Verzonden naar hun homescreens! Voeg meer vrienden toe om uw echte leven op uw startschermen te delen."
photo_end_5="Geen foto's meer. Nodig meer vrienden uit om je echte leven op je homescreens te delen."
photo_copy_6="Voeg me toe op JustUs - Widget Social Network, alles is klaar behalve jij!"
photo_tips_6="Verzonden naar hun homescreens! Nodig meer vrienden uit om je echte leven met hen te delen."
photo_end_6="Geen foto's meer. Voeg meer vrienden toe om je echte leven met hen te delen."
photo_copy_7="Voeg me toe op JustUs, alles is klaar behalve jij! Mijn ID:"
photo_tips_7="Verzonden naar hun homescreens! Nodig meer vrienden uit om je echte leven met hen te delen."
photo_end_7="Geen foto's meer. Voeg meer vrienden toe om je echte leven met hen te delen."
photo_copy_8="Voeg me toe op JustUs - Widget Social Network, deel het echte leven met mij! Mijn ID:"
photo_tips_8="Verzonden naar hun homescreens! Nodig meer vrienden uit om je echte leven met hen te delen."
photo_end_8="Geen foto's meer. Voeg meer vrienden toe om je echte leven met hen te delen."
photo_copy_9="Accepteer de echte foto-uitdaging, voeg me toe op JustUs. Mijn ID:"
photo_tips_9="Verzonden naar hun homescreens! Nodig meer vrienden uit om je echte leven met hen te delen."
photo_end_9="Geen foto's meer. Voeg meer vrienden toe om je echte leven met hen te delen."
photo_copy_10="Ik wil dat je op mijn startscherm staat, voeg me toe op JustUs. Mijn ID:"
photo_tips_10="Verzonden naar hun homescreens! Het zou leuker zijn als je meer vrienden toevoegt."
photo_end_10="Geen foto's meer. Voeg meer vrienden toe om je echte leven samen te delen."
photo_copy_11="Ik wil dat je op mijn startscherm staat, voeg me toe op JustUs. Mijn ID:"
photo_tips_11="Verzonden naar hun homescreens! Voeg meer vrienden toe om uw foto's naar hun startscherm te sturen."
photo_end_11="Het lijkt erop dat je geen foto's van vrienden meer hebt! Voeg meer vrienden toe om uw echte leven samen vast te leggen."
photo_copy_12="Wees mijn homescreen-vriend, voeg me toe op JustUs. Mijn ID:"
photo_tips_12="Verzonden naar hun homescreens! Nodig meer vrienden uit op je startscherm en stuur ze leuke foto's!"
photo_end_12="Het lijkt erop dat je geen foto's van vrienden meer hebt! Nodig meer vrienden uit op je startscherm en stuur ze leuke foto's."
photo_copy_13="Wees mijn homescreen-vriend, voeg me toe op JustUs. Mijn ID:"
photo_tips_13="Verzonden naar hun homescreens! Het zou leuker zijn als je meer homescreen-vrienden toevoegt."
photo_end_13="Het lijkt erop dat je meer vrienden nodig hebt! Nodig meer vrienden uit op je startscherm en stuur ze leuke foto's."
your_self_visible="Alleen zichtbaar voor mij"
update_new_version="Nieuwe duetfunctie, kom alsjeblieft om te upgraden en het te ervaren!"
