param_error="Errore di parametro"
component_num_limit="Non sei temporaneamente in grado di creare più gruppi."
friend_num_limit="Non sei temporaneamente in grado di aggiungere altri amici."
operation_error="Operazione fallita. Per favore riprova più tardi!"
char_limit="I caratteri inseriti superano il limite di lunghezza massima. Il massimo :number caratteri."
first_name_limit="Il \"Cognome\" inserito supera il limite massimo di lunghezza. Il massimo :number caratteri."
last_name_limit="Il \"Nome\" inserito supera il limite massimo di lunghezza. Il massimo :number caratteri."
first_name_required="Il \"Cognome\" non può essere vuoto."
last_name_required="Il \"Nome\" non può essere vuoto."
mobile_error="Errore di formato del numero di telefono"
mobile_required="Il numero di telefono non può essere vuoto."
country_code_error="Errore codice paese"
search_key="Inserisci un ID utente o un numero di cellulare valido."
is_add_friend="La richiesta di aggiunta di amicizia è stata inviata."
system_error="Errore di sistema"
msg_code_error="Errore di formato del codice di verifica"
first_name_length="Il \"Cognome\" è troppo lungo."
friends_exist="Utente non trovato"
last_name_length="Il \"Nome\" è troppo lungo."
content_length="Il massimo 200 caratteri"
he_friend_num_limit="Il numero di amici tuoi o dell'utente ha raggiunto il limite."
sign_error="Verifica della firma fallita"
is_friends="L'utente è stato tuo amico."
sms_friend_tips="Aggiungimi su JustUs."
photo_tips="Hlaðið upp! Bættu við fleiri vinum til að deila raunveruleikanum saman"
message_limit="Invii messaggi di testo troppo spesso. Per favore riprova più tardi."
copy_friend_tips="Aggiungimi su JustUs."
no_add_friend_self="Non puoi aggiungerti come amico."
justus_slogan="Registriamo insieme la vita reale!"
justus_helper="Guida JustUs"
bind_mobile_error="Il numero di telefono è stato associato a un altro account."
bound_mobile="Associazione fallita. Per favore riprova più tardi."
not_add_self_friend="Non puoi aggiungerti come amico."
address_book_tips="Sincronizza i tuoi contatti per trovare amici già su JustUs. I dati dei tuoi contatti verranno inviati a JustUs per migliorare la tua esperienza e consentire a te e ad altri di trovare amici."
follow_user="ti ho seguito!"
notification_friends=":name è diventato il tuo amico \"JustUs\"! Prova a mandargli delle foto!"
notification_like=":name mi sei piaciuta!"
notification_comment=":name ti ha appena commentato, dai un'occhiata!"
notification_friend_apply=":name ti ha inviato una richiesta di amicizia."
notification_friend_send_picture=":name ha pubblicato una nuova foto."
notification_user_register="Vieni a fare una foto! Registra insieme la vita reale con i tuoi amici!"
notification_friend_register=":name è anche su JustUs. Aggiungere?"
notification_memory=":name, hai una nuova memoria."
notification_wait_add_friend=":name, i tuoi amici stanno aspettando!"
notification_touch=":name ha toccato la tua foto💓"
notification_follow_user=":name ti ho seguito!"
photo_copy_1="Ti ho aggiunto su (JustUs). Scarica questa app per consentire la mia richiesta di amicizia.Il mio ID:"
photo_tips_1="Hlaðið upp! Bættu við fleiri vinum til að deila raunveruleikanum saman"
photo_end_1="Niente più momenti tra amici. Scatta una foto o aggiungi altri amici."
photo_copy_2="Aggiungimi su JustUs.Il mio ID:"
photo_tips_2="Hlaðið upp! Bættu við fleiri vinum til að deila raunveruleikanum saman"
photo_end_2="Niente più momenti tra amici. Scatta una foto o aggiungi altri amici."
photo_copy_3="Aggiungimi su JustUs così possiamo condividere le foto sulla nostra schermata iniziale. Il mio ID:"
photo_tips_3="Inviato ai loro homescreen! Aggiungi più amici per condividere le tue vite reali sulle schermate iniziali."
photo_end_3="Niente più foto. Aggiungi più amici per condividere le tue vite reali sulle schermate iniziali."
photo_copy_4="Aggiungimi su JustUs, ho delle foto da inviare alla tua schermata iniziale. Il mio ID:"
photo_tips_4="Inviato ai loro homescreen! Aggiungi più amici per condividere le tue vite reali sulle schermate iniziali."
photo_end_4="Niente più foto. Aggiungi più amici per condividere le tue vite reali sulle schermate iniziali."
photo_copy_5="Aggiungimi su JustUs, il nuovo widget social network! Il mio ID:"
photo_tips_5="Inviato ai loro homescreen! Aggiungi più amici per condividere le tue vite reali sulle schermate iniziali."
photo_end_5="Niente più foto. Invita più amici a condividere le tue vite reali sulle schermate iniziali."
photo_copy_6="Aggiungimi su JustUs - Widget Social Network, tutto è pronto tranne te!"
photo_tips_6="Inviato ai loro homescreen! Invita più amici a condividere la tua vita reale con loro."
photo_end_6="Niente più foto. Aggiungi più amici per condividere la tua vita reale con loro."
photo_copy_7="Aggiungimi su JustUs, tutto è pronto tranne te! Il mio ID:"
photo_tips_7="Inviato ai loro homescreen! Invita più amici a condividere la tua vita reale con loro."
photo_end_7="Niente più foto. Aggiungi più amici per condividere la tua vita reale con loro."
photo_copy_8="Aggiungimi su JustUs - Widget Social Network, condividi la vita reale con me! Il mio ID:"
photo_tips_8="Inviato ai loro homescreen! Invita più amici a condividere la tua vita reale con loro."
photo_end_8="Niente più foto. Aggiungi più amici per condividere la tua vita reale con loro."
photo_copy_9="Accetta la sfida fotografica della vita reale, Aggiungimi su JustUs. Il mio ID:"
photo_tips_9="Inviato ai loro homescreen! Invita più amici a condividere la tua vita reale con loro."
photo_end_9="Niente più foto. Aggiungi più amici per condividere la tua vita reale con loro."
photo_copy_10="Voglio che tu sia sulla mia schermata iniziale, aggiungimi su JustUs. Il mio ID:"
photo_tips_10="Inviato ai loro homescreen! Sarebbe più divertente se aggiungessi più amici."
photo_end_10="Niente più foto. Aggiungi più amici per condividere la tua vita reale insieme."
photo_copy_11="Voglio che tu sia sulla mia schermata iniziale, aggiungimi su JustUs. Il mio ID:"
photo_tips_11="Inviato ai loro homescreen! Aggiungi altri amici per inviare le tue foto alle loro schermate home."
photo_end_11="Sembra che tu abbia esaurito le foto degli amici! Aggiungi più amici per registrare le tue vite reali insieme."
photo_copy_12="Diventa il mio amico homescreen, aggiungimi su JustUs. Il mio ID:"
photo_tips_12="Inviato ai loro homescreen! Invita più amici sulla tua schermata iniziale e invia loro foto divertenti!"
photo_end_12="Sembra che tu abbia esaurito le foto degli amici! Invita più amici sulla tua schermata iniziale e invia loro foto divertenti."
photo_copy_13="Diventa il mio amico homescreen, aggiungimi su JustUs. Il mio ID:"
photo_tips_13="Inviato ai loro homescreen! Sarebbe più divertente se aggiungessi più amici nella schermata iniziale."
photo_end_13="Sembra che tu abbia bisogno di più amici! Invita più amici sulla tua schermata iniziale e invia loro foto divertenti."
your_self_visible="Visibile solo a me"
update_new_version="Nuova funzione di duetto, vieni ad aggiornarla e provala!"
