param_error="Napaka parametra"
component_num_limit="Začasno ne morete ustvariti več skupin."
friend_num_limit="Začasno ne morete dodati več prijateljev."
operation_error="Operacija ni uspela. Prosim poskusite kasneje!"
char_limit="Znaki, ki ste jih vnesli, presegajo omejitev največje dolžine. Največ :number znakov."
first_name_limit="Priimek, ki ste ga vnesli, presega omejitev največje dolžine. Največje dovoljeno število :number znakov."
last_name_limit="Ime, ki ste ga vnesli, presega omejitev največje dolžine. Največje dovoljeno število :number znakov."
first_name_required="Priimek ne sme biti prazen."
last_name_required="Polje »Ime« ne sme biti prazno."
mobile_error="Napaka v formatu telefonske številke"
mobile_required="Telefonska številka ne sme biti prazna."
country_code_error="Napaka kode države"
search_key="Vnesite veljaven ID uporabnika ali številko mobilnega telefona."
is_add_friend="Zahteva za dodajanje prijatelja je bila poslana."
system_error="Sistemska napaka"
msg_code_error="Napaka v formatu potrditvene kode"
first_name_length="Priimek je predolg."
friends_exist="Uporabnik ni najden"
last_name_length="Ime je predolgo."
content_length="Največ 200 znakov"
he_friend_num_limit="Vaše ali uporabnikovo število prijateljev je doseglo omejitev."
sign_error="Preverjanje podpisa ni uspelo"
is_friends="Uporabnik je bil vaš prijatelj."
sms_friend_tips="Dodaj me na gin-default."
photo_tips="Uspešno naloženo! Dodajte več prijateljev, da si skupaj delite resnično življenje"
message_limit="Prepogosto pošiljate besedilna sporočila. Prosim poskusite kasneje."
copy_friend_tips="Dodaj me na gin-default."
no_add_friend_self="Ne morete se dodati kot prijatelja."
gin-default_slogan="Skupaj snemajmo resnično življenje!"
gin-default_helper="Vodnik gin-default"
bind_mobile_error="Telefonska številka je bila vezana na drug račun."
bound_mobile="Vezava ni uspela. Prosim poskusite kasneje."
not_add_self_friend="Ne moreš se dodati kot prijatelja."
address_book_tips="Sinhronizirajte svoje stike, da poiščete prijatelje, ki so že na JustU. Podatki o vaših stikih bodo poslani gin-defaultu, da izboljšamo vašo izkušnjo in omogočimo vam in drugim, da najdejo prijatelje."
follow_user="te spremljal!"
notification_friends=":name je postal vaš prijatelj »Samo mi«! Poskusite jim poslati fotografije!"
notification_like=":name te je pravkar všeč!"
notification_comment=":name vas je pravkar komentirala, preverite!"
notification_friend_apply=":name vam je poslala prošnjo za prijateljstvo."
notification_friend_send_picture=":name je objavila novo fotografijo."
notification_user_register="Pridite in fotografirajte! Snemajte resnično življenje s prijatelji skupaj!"
notification_friend_register=":name je tudi na JustU. dodaj?"
notification_memory=":name, imaš nov spomin."
notification_wait_add_friend=":name, tvoji prijatelji čakajo!"
notification_touch=":name se je dotaknil tvoje fotografije💓"
notification_follow_user=":name te spremljal!"
photo_copy_1="Dodal sem vas na (Samo mi). Prenesite to aplikacijo, da dovolite mojo prošnjo za prijateljstvo.moj ID:"
photo_tips_1="Uspešno naloženo! Dodajte več prijateljev, da si skupaj delite resnično življenje"
photo_end_1="Nič več trenutkov prijateljev. Posnemite fotografijo ali dodajte več prijateljev."
photo_copy_2="Dodaj me na gin-default.moj ID:"
photo_tips_2="Uspešno naloženo! Dodajte več prijateljev, da si skupaj delite resnično življenje"
photo_end_2="Nič več trenutkov prijateljev. Posnemite fotografijo ali dodajte več prijateljev."
photo_copy_3="Dodajte me na gin-default, da bomo lahko delili fotografije na domačem zaslonu. moj ID:"
photo_tips_3="Poslano na njihove domače zaslone! Dodajte več prijateljev, da delite svoja resnična življenja na domačih zaslonih."
photo_end_3="Nič več fotografij. Dodajte več prijateljev, da delite svoja resnična življenja na domačih zaslonih."
photo_copy_4="Dodajte me na gin-default, fotografije moram poslati na vaš domači zaslon. moj ID:"
photo_tips_4="Poslano na njihove domače zaslone! Dodajte več prijateljev, da delite svoja resnična življenja na domačih zaslonih."
photo_end_4="Nič več fotografij. Dodajte več prijateljev, da delite svoja resnična življenja na domačih zaslonih."
photo_copy_5="Dodajte me na gin-default, novo družabno omrežje s pripomočki! moj ID:"
photo_tips_5="Poslano na njihove domače zaslone! Dodajte več prijateljev, da delite svoja resnična življenja na domačih zaslonih."
photo_end_5="Nič več fotografij. Povabite več prijateljev, da delijo svoja resnična življenja na vaših domačih zaslonih."
photo_copy_6="Dodaj me na gin-default - Widget Social Network, vse je pripravljeno, razen tebe!"
photo_tips_6="Poslano na njihove domače zaslone! Povabite več prijateljev, da z njimi delite svoja resnična življenja."
photo_end_6="Nič več fotografij. Dodajte več prijateljev, da z njimi delite svoja resnična življenja."
photo_copy_7="Dodaj me na gin-default, vse je pripravljeno razen tebe! moj ID:"
photo_tips_7="Poslano na njihove domače zaslone! Povabite več prijateljev, da z njimi delite svoja resnična življenja."
photo_end_7="Nič več fotografij. Dodajte več prijateljev, da z njimi delite svoja resnična življenja."
photo_copy_8="Dodajte me na gin-default - Widget Social Network, delite resnično življenje z mano! moj ID:"
photo_tips_8="Poslano na njihove domače zaslone! Povabite več prijateljev, da z njimi delite svoja resnična življenja."
photo_end_8="Nič več fotografij. Dodajte več prijateljev, da z njimi delite svoja resnična življenja."
photo_copy_9="Sprejmite resnični fotografski izziv, dodajte me na gin-default. moj ID:"
photo_tips_9="Poslano na njihove domače zaslone! Povabite več prijateljev, da z njimi delite svoja resnična življenja."
photo_end_9="Nič več fotografij. Dodajte več prijateljev, da z njimi delite svoja resnična življenja."
photo_copy_10="Želim, da si na mojem domačem zaslonu, dodaj me na gin-default. moj ID:"
photo_tips_10="Poslano na njihove domače zaslone! Bolj zabavno bi bilo, če bi dodali več prijateljev."
photo_end_10="Nič več fotografij. Dodajte več prijateljev, da skupaj delite svoja resnična življenja."
photo_copy_11="Želim, da si na mojem domačem zaslonu, dodaj me na gin-default. moj ID:"
photo_tips_11="Poslano na njihove domače zaslone! Dodajte več prijateljev, da pošljete svoje fotografije na njihove domače zaslone."
photo_end_11="Zdi se, da vam je zmanjkalo fotografij prijateljev! Dodajte več prijateljev, da skupaj posnamete svoja resnična življenja."
photo_copy_12="Bodi moj prijatelj na domačem zaslonu, dodaj me na gin-default. moj ID:"
photo_tips_12="Poslano na njihove domače zaslone! Povabite več prijateljev na domači zaslon in jim pošljite zabavne fotografije!"
photo_end_12="Zdi se, da vam je zmanjkalo fotografij prijateljev! Povabite več prijateljev na domači zaslon in jim pošljite zabavne fotografije."
photo_copy_13="Bodi moj prijatelj na domačem zaslonu, dodaj me na gin-default. moj ID:"
photo_tips_13="Poslano na njihove domače zaslone! Bolj zabavno bi bilo, če dodate več prijateljev na domačem zaslonu."
photo_end_13="Zdi se, da potrebujete več prijateljev! Povabite več prijateljev na domači zaslon in jim pošljite zabavne fotografije."
your_self_visible="Vidno samo meni"
update_new_version="Nova funkcija dueta, pridite, da jo nadgradite in jo doživite!"
