param_error="Parameterfel"
component_num_limit="Du kan tillf칛lligt inte skapa fler grupper."
friend_num_limit="Du kan tillf칛lligt inte l칛gga till fler v칛nner."
operation_error="Operationen misslyckades. V칛nligen f칬rs칬k igen senare!"
char_limit="Tecknen du angav 칬verskrider den maximala l칛ngden. Maximalt :number tecken."
first_name_limit="Efternamnet du angav 칬verskrider den maximala l칛ngdgr칛nsen. Max :number tecken."
last_name_limit="F칬rnamnet du angav 칬verskrider den maximala l칛ngdgr칛nsen. Max :number tecken."
first_name_required="Efternamn f친r inte vara tomt."
last_name_required="F칬rnamn f친r inte vara tomt."
mobile_error="Formateringsfel f칬r telefonnummer"
mobile_required="Telefonnumret f친r inte vara tomt."
country_code_error="Landskodsfel"
search_key="Ange ett giltigt anv칛ndar-ID eller mobilnummer."
is_add_friend="L칛gg till v칛nf칬rfr친gan har skickats."
system_error="Systemfel"
msg_code_error="Verifieringskodsformatfel"
first_name_length="Efternamn 칛r f칬r l친ngt."
friends_exist="Anv칛ndaren hittades inte"
last_name_length="F칬rnamn 칛r f칬r l친ngt."
content_length="H칬gst 200 tecken"
he_friend_num_limit="Ditt eller anv칛ndarens antal v칛nner har n친tt gr칛nsen."
sign_error="Signaturverifiering misslyckades"
is_friends="Anv칛ndaren har varit din v칛n."
sms_friend_tips="L칛gg till mig p친 JustUs."
photo_tips="Laddades upp! L칛gg till fler v칛nner f칬r att dela det verkliga livet tillsammans"
message_limit="Du skickar sms f칬r ofta. V칛nligen f칬rs칬k igen senare."
copy_friend_tips="L칛gg till mig p친 JustUs."
no_add_friend_self="Du kan inte l칛gga till dig sj칛lv som v칛n."
justus_slogan="L친t oss spela in det verkliga livet tillsammans!"
justus_helper="JustUs guide"
bind_mobile_error="Telefonnumret har kopplats till ett annat konto."
bound_mobile="Bindningen misslyckades. V칛nligen f칬rs칬k igen senare."
not_add_self_friend="Du kan inte l칛gga till dig sj칛lv som v칛n."
address_book_tips="Synkronisera dina kontakter f칬r att hitta v칛nner som redan finns p친 JustUs. Dina kontaktuppgifter kommer att skickas till JustUs f칬r att f칬rb칛ttra din upplevelse och l친ta dig och andra hitta v칛nner."
follow_user="f칬ljde dig!"
notification_friends=":name har blivit din \"Bara oss\"-v칛n! Prova att skicka bilder till dem!"
notification_like=":name gillade dig bara!"
notification_comment=":name kommenterade dig precis, kolla in det!"
notification_friend_apply=":name skickade en v칛nf칬rfr친gan till dig."
notification_friend_send_picture=":name har lagt upp ett nytt foto."
notification_user_register="Kom och ta ett foto! Spela in det verkliga livet med dina v칛nner tillsammans!"
notification_friend_register=":name finns ocks친 p친 JustUs. L칛gg till?"
notification_memory=":name, du har ett nytt minne."
notification_wait_add_friend=":name, dina v칛nner v칛ntar!"
notification_touch=":name r칬rde vid ditt foto游눕"
notification_follow_user=":name f칬ljde dig!"
photo_copy_1="Jag har lagt till dig p친 (JustUs). Ladda ner den h칛r appen f칬r att till친ta min v칛nf칬rfr친gan.Mitt ID:"
photo_tips_1="Laddades upp! L칛gg till fler v칛nner f칬r att dela det verkliga livet tillsammans"
photo_end_1="Inga fler v칛nners stunder. Ta ett foto eller l칛gg till fler v칛nner."
photo_copy_2="L칛gg till mig p친 JustUs. Mitt ID:"
photo_tips_2="Laddades upp! L칛gg till fler v칛nner f칬r att dela det verkliga livet tillsammans"
photo_end_2="Inga fler v칛nners stunder. Ta ett foto eller l칛gg till fler v칛nner."
photo_copy_3="L칛gg till mig p친 JustUs s친 att vi kan dela bilder p친 v친r startsk칛rm. Mitt ID:"
photo_tips_3="Skickat till deras hemsk칛rmar! L칛gg till fler v칛nner f칬r att dela dina verkliga liv p친 dina hemsk칛rmar."
photo_end_3="Inga fler bilder. L칛gg till fler v칛nner f칬r att dela dina verkliga liv p친 dina hemsk칛rmar."
photo_copy_4="L칛gg till mig p친 JustUs, jag har bilder att skicka till din startsk칛rm. Mitt ID:"
photo_tips_4="Skickat till deras hemsk칛rmar! L칛gg till fler v칛nner f칬r att dela dina verkliga liv p친 dina hemsk칛rmar."
photo_end_4="Inga fler bilder. L칛gg till fler v칛nner f칬r att dela dina verkliga liv p친 dina hemsk칛rmar."
photo_copy_5="L칛gg till mig p친 JustUs, det nya sociala n칛tverket f칬r widgeten! Mitt ID:"
photo_tips_5="Skickat till deras hemsk칛rmar! L칛gg till fler v칛nner f칬r att dela dina verkliga liv p친 dina hemsk칛rmar."
photo_end_5="Inga fler bilder. Bjud in fler v칛nner att dela dina verkliga liv p친 dina hemsk칛rmar."
photo_copy_6="L칛gg till mig p친 JustUs - Widget Social Network, allt 칛r klart utom du!"
photo_tips_6="Skickat till deras hemsk칛rmar! Bjud in fler v칛nner att dela ditt verkliga liv med dem."
photo_end_6="Inga fler bilder. L칛gg till fler v칛nner f칬r att dela ditt verkliga liv med dem."
photo_copy_7="L칛gg till mig p친 JustUs, allt 칛r klart utom du! Mitt ID:"
photo_tips_7="Skickat till deras hemsk칛rmar! Bjud in fler v칛nner att dela ditt verkliga liv med dem."
photo_end_7="Inga fler bilder. L칛gg till fler v칛nner f칬r att dela ditt verkliga liv med dem."
photo_copy_8="L칛gg till mig p친 JustUs - Widget Social Network, dela det verkliga livet med mig! Mitt ID:"
photo_tips_8="Skickat till deras hemsk칛rmar! Bjud in fler v칛nner att dela ditt verkliga liv med dem."
photo_end_8="Inga fler bilder. L칛gg till fler v칛nner f칬r att dela ditt verkliga liv med dem."
photo_copy_9="Acceptera den verkliga fotoutmaningen, L칛gg till mig p친 JustUs. Mitt ID:"
photo_tips_9="Skickat till deras hemsk칛rmar! Bjud in fler v칛nner att dela ditt verkliga liv med dem."
photo_end_9="Inga fler bilder. L칛gg till fler v칛nner f칬r att dela ditt verkliga liv med dem."
photo_copy_10="Jag vill att du ska vara p친 min startsk칛rm, l칛gg till mig p친 JustUs. Mitt ID:"
photo_tips_10="Skickat till deras hemsk칛rmar! Det skulle vara roligare om du l칛gger till fler v칛nner."
photo_end_10="Inga fler bilder. L칛gg till fler v칛nner f칬r att dela era verkliga liv tillsammans."
photo_copy_11="Jag vill att du ska vara p친 min startsk칛rm, l칛gg till mig p친 JustUs. Mitt ID:"
photo_tips_11="Skickat till deras hemsk칛rmar! L칛gg till fler v칛nner f칬r att skicka dina foton till deras hemsk칛rmar."
photo_end_11="Du verkar ha slut p친 v칛nners bilder! L칛gg till fler v칛nner f칬r att spela in era verkliga liv tillsammans."
photo_copy_12="Var min hemsk칛rmsv칛n, l칛gg till mig p친 JustUs. Mitt ID:"
photo_tips_12="Skickat till deras hemsk칛rmar! Bjud in fler v칛nner till din startsk칛rm och skicka roliga bilder till dem!"
photo_end_12="Du verkar ha slut p친 v칛nners bilder! Bjud in fler v칛nner till din startsk칛rm och skicka roliga bilder till dem."
photo_copy_13="Var min hemsk칛rmsv칛n, l칛gg till mig p친 JustUs. Mitt ID:"
photo_tips_13="Skickat till deras hemsk칛rmar! Det skulle vara roligare om du l칛gger till fler hemsk칛rmsv칛nner."
photo_end_13="Du verkar beh칬va fler v칛nner! Bjud in fler v칛nner till din startsk칛rm och skicka roliga bilder till dem."
your_self_visible="Bara synlig f칬r mig"
update_new_version="Ny duettfunktion, kom g칛rna f칬r att uppgradera och uppleva den!"
