param_error="Parametrų klaida"
component_num_limit="Laikinai negalite sukurti daugiau grupių."
friend_num_limit="Laikinai negalite pridėti daugiau draugų."
operation_error="Operacija nepavyko. Pabandykite dar kartą vėliau!"
char_limit="Įvesti simboliai viršija didžiausią ilgio limitą. Daugiausia :number simboliai."
first_name_limit="Įvesta „Pavardė“ viršija didžiausio ilgio limitą. Daugiausia :number simboliai."
last_name_limit="Įvestas „Vardas“ viršija didžiausio ilgio limitą. Daugiausia :number simboliai."
first_name_required="Lauko „Pavardė“ laukas negali būti tuščias."
last_name_required="Lauko „Vardas“ laukas negali būti tuščias."
mobile_error="Telefono numerio formato klaida"
mobile_required="Telefono numerio laukas negali būti tuščias."
country_code_error="Šalies kodo klaida"
search_key="Įveskite galiojantį vartotojo ID arba mobiliojo telefono numerį."
is_add_friend="Prašymas pridėti draugą išsiųstas."
system_error="Sistemos klaida"
msg_code_error="Patvirtinimo kodo formato klaida"
first_name_length="„Pavardė“ per ilga."
friends_exist="Vartotojas nerastas"
last_name_length="„Vardas“ per ilgas."
content_length="Daugiausia 200 simbolių"
he_friend_num_limit="Jūsų arba vartotojo draugų skaičius pasiekė limitą."
sign_error="Parašo patikrinimas nepavyko"
is_friends="Vartotojas buvo jūsų draugas."
sms_friend_tips="Pridėkite mane prie gin-default."
photo_tips="Įkelta sėkmingai! Pridėkite daugiau draugų ir dalinkitės tikru gyvenimu"
message_limit="Per dažnai siunčiate tekstinius pranešimus. Pabandykite dar kartą vėliau."
copy_friend_tips="Pridėkite mane prie gin-default."
no_add_friend_self="Negalite pridėti savęs kaip draugo."
gin-default_slogan="Įrašykime tikrą gyvenimą kartu!"
gin-default_helper="gin-default vadovas"
bind_mobile_error="Telefono numeris susietas su kita paskyra."
bound_mobile="Įrišimas nepavyko. Pabandykite dar kartą vėliau."
not_add_self_friend="Negalite pridėti savęs kaip draugo."
address_book_tips="Sinchronizuokite savo kontaktus, kad rastumėte draugų, kurie jau naudojasi gin-default. Jūsų kontaktų duomenys bus siunčiami „gin-default“, kad pagerintumėte jūsų patirtį ir leistų jums bei kitiems susirasti draugų."
follow_user="sekiau tave!"
notification_friends=":name tapo jūsų draugu „Tik mes“! Pabandykite nusiųsti jiems nuotraukas!"
notification_like=":name tu tiesiog patikai!"
notification_comment=":name ką tik pakomentavo jus, pažiūrėkite!"
notification_friend_apply=":name atsiuntė jums prašymą draugauti."
notification_friend_send_picture=":name paskelbė naują nuotrauką."
notification_user_register="Ateik ir nusifotografuok! Įrašykite tikrą gyvenimą su draugais kartu!"
notification_friend_register=":name taip pat yra gin-default. Papildyti?"
notification_memory=":name, turite naują atmintį."
notification_wait_add_friend=":name, jūsų draugai laukia!"
notification_touch=":name palietė tavo nuotrauką💓"
notification_follow_user=":name sekiau tave!"
photo_copy_1="Aš įtraukiau jus į (gin-default). Atsisiųskite šią programą, kad galėtumėte prašyti draugo.Mano ID:"
photo_tips_1="Įkelta sėkmingai! Pridėkite daugiau draugų ir dalinkitės tikru gyvenimu"
photo_end_1="Daugiau jokių draugų akimirkų. Nufotografuokite arba pridėkite daugiau draugų."
photo_copy_2="Pridėkite mane prie gin-default.Mano ID:"
photo_tips_2="Įkelta sėkmingai! Pridėkite daugiau draugų ir dalinkitės tikru gyvenimu"
photo_end_2="Daugiau jokių draugų akimirkų. Nufotografuokite arba pridėkite daugiau draugų."
photo_copy_3="Pridėkite mane prie gin-default, kad galėtume bendrinti nuotraukas pagrindiniame ekrane. Mano ID:"
photo_tips_3="Išsiųsta į jų pagrindinius ekranus! Pridėkite daugiau draugų, kad pradiniame ekrane pasidalintumėte savo tikruoju gyvenimu."
photo_end_3="Daugiau nuotraukų nėra. Pridėkite daugiau draugų, kad pradiniame ekrane pasidalintumėte savo tikruoju gyvenimu."
photo_copy_4="Pridėkite mane prie gin-default, turiu nuotraukų, kurias galite siųsti į jūsų pagrindinį ekraną. Mano ID:"
photo_tips_4="Išsiųsta į jų pagrindinius ekranus! Pridėkite daugiau draugų, kad pradiniame ekrane pasidalintumėte savo tikruoju gyvenimu."
photo_end_4="Daugiau nuotraukų nėra. Pridėkite daugiau draugų, kad pradiniame ekrane pasidalintumėte savo tikruoju gyvenimu."
photo_copy_5="Pridėkite mane prie gin-default, naujo valdiklio socialinio tinklo! Mano ID:"
photo_tips_5="Išsiųsta į jų pagrindinius ekranus! Pridėkite daugiau draugų, kad pradiniame ekrane pasidalintumėte savo tikruoju gyvenimu."
photo_end_5="Daugiau nuotraukų nėra. Pakvieskite daugiau draugų pasidalyti savo tikruoju gyvenimu pagrindiniuose ekranuose."
photo_copy_6="Pridėkite mane prie gin-default – valdiklio socialinio tinklo, viskas yra paruošta, išskyrus jus!"
photo_tips_6="Išsiųsta į jų pagrindinius ekranus! Pakvieskite daugiau draugų pasidalyti su jais savo tikruoju gyvenimu."
photo_end_6="Daugiau nuotraukų nėra. Pridėkite daugiau draugų, kad su jais pasidalintumėte savo tikruoju gyvenimu."
photo_copy_7="Pridėkite mane prie gin-default, viskas yra paruošta, išskyrus jus! Mano ID:"
photo_tips_7="Išsiųsta į jų pagrindinius ekranus! Pakvieskite daugiau draugų pasidalyti su jais savo tikruoju gyvenimu."
photo_end_7="Daugiau nuotraukų nėra. Pridėkite daugiau draugų, kad su jais pasidalintumėte savo tikruoju gyvenimu."
photo_copy_8="Pridėkite mane prie gin-default – valdiklio socialinio tinklo, pasidalykite tikru gyvenimu su manimi! Mano ID:"
photo_tips_8="Išsiųsta į jų pagrindinius ekranus! Pakvieskite daugiau draugų pasidalyti su jais savo tikruoju gyvenimu."
photo_end_8="Daugiau nuotraukų nėra. Pridėkite daugiau draugų, kad su jais pasidalintumėte savo tikruoju gyvenimu."
photo_copy_9="Priimkite realaus gyvenimo nuotraukų iššūkį, pridėkite mane prie gin-default. Mano ID:"
photo_tips_9="Išsiųsta į jų pagrindinius ekranus! Pakvieskite daugiau draugų pasidalyti su jais savo tikruoju gyvenimu."
photo_end_9="Daugiau nuotraukų nėra. Pridėkite daugiau draugų, kad su jais pasidalintumėte savo tikruoju gyvenimu."
photo_copy_10="Noriu, kad būtumėte mano pagrindiniame ekrane, įtraukite mane į gin-default. Mano ID:"
photo_tips_10="Išsiųsta į jų pagrindinius ekranus! Būtų smagiau, jei pridėtumėte daugiau draugų."
photo_end_10="Daugiau nuotraukų nėra. Pridėkite daugiau draugų, kad kartu pasidalytumėte savo tikruoju gyvenimu."
photo_copy_11="Noriu, kad būtumėte mano pagrindiniame ekrane, įtraukite mane į gin-default. Mano ID:"
photo_tips_11="Išsiųsta į jų pagrindinius ekranus! Pridėkite daugiau draugų, kad galėtumėte siųsti nuotraukas į jų pagrindinį ekraną."
photo_end_11="Atrodo, kad pritrūko draugų nuotraukų! Pridėkite daugiau draugų, kad kartu įrašytumėte savo tikrąjį gyvenimą."
photo_copy_12="Būkite mano pagrindinio ekrano draugas, pridėkite mane prie gin-default. Mano ID:"
photo_tips_12="Išsiųsta į jų pagrindinius ekranus! Pakvieskite daugiau draugų į pagrindinį ekraną ir siųskite jiems smagių nuotraukų!"
photo_end_12="Atrodo, kad pritrūko draugų nuotraukų! Pakvieskite daugiau draugų į pagrindinį ekraną ir siųskite jiems smagių nuotraukų."
photo_copy_13="Būkite mano pagrindinio ekrano draugas, pridėkite mane prie gin-default. Mano ID:"
photo_tips_13="Išsiųsta į jų pagrindinius ekranus! Būtų smagiau, jei pridėtumėte daugiau pagrindinio ekrano draugų."
photo_end_13="Atrodo, kad tau reikia daugiau draugų! Pakvieskite daugiau draugų į pagrindinį ekraną ir siųskite jiems smagių nuotraukų."
your_self_visible="Matoma tik man"
update_new_version="Nauja dueto funkcija, ateikite atnaujinti ir patirti!"
