param_error="Грешка параметра"
component_num_limit="Привремено не можете да креирате више група."
friend_num_limit="Привремено не можете да додате још пријатеља."
operation_error="Операција неуспела. Покушајте поново касније!"
char_limit="Знакови које сте унели премашују ограничење максималне дужине. Максимум :number знакова."
first_name_limit="„Презиме“ које сте унели премашује ограничење максималне дужине. Максимално :number знакова."
last_name_limit="„Име“ које сте унели премашује ограничење максималне дужине. Максимално :number знакова."
first_name_required="Поље „Презиме“ не може бити празно."
last_name_required="Поље „Име“ не може бити празно."
mobile_error="Грешка у формату телефонског броја"
mobile_required="Број телефона не може бити празан."
country_code_error="Грешка кода земље"
search_key="Унесите важећи кориснички ИД или број мобилног телефона."
is_add_friend="Захтев за додавање пријатеља је послат."
system_error="Грешка у систему"
msg_code_error="Грешка у формату верификационог кода"
first_name_length="„Презиме“ је предугачко."
friends_exist="Корисник није пронађен"
last_name_length="„Име“ је предугачко."
content_length="Максимално 200 знакова"
he_friend_num_limit="Ваш или корисников број пријатеља је достигао ограничење."
sign_error="Верификација потписа неуспешна"
is_friends="Корисник је био ваш пријатељ."
sms_friend_tips="Додај ме на ЈustUs."
photo_tips="Успешно отпремљено! Додајте још пријатеља да заједно делите стварни живот"
message_limit="Пречесто шаљете текстуалне поруке. Покушајте поново касније."
copy_friend_tips="Додај ме на ЈustUs."
no_add_friend_self="Не можете се додати као пријатеља."
justus_slogan="Снимимо прави живот заједно!"
justus_helper="JustUs Гуиде"
bind_mobile_error="Број телефона је везан."
bound_mobile="Повезивање није успело. Покушајте поново касније."
not_add_self_friend="Не можете себе додати као пријатеља."
address_book_tips="Синхронизујте своје контакте да бисте пронашли пријатеље који већ користе ЈustUs. Подаци о вашим контактима ће бити послати у ЈustUs да побољшамо ваше искуство и омогућите вама и другима да пронађете пријатеље."
follow_user="пратио те!"
notification_friends="name: је постао ваш пријатељ „JustUs“! Покушајте да им пошаљете фотографије!"
notification_like="name: ти се управо допао!"
notification_comment="name: вас је управо коментарисао, погледајте!"
notification_friend_apply=":name вам је послао захтев за пријатељство."
notification_friend_send_picture="name: је поставио/ла нову фотографију."
notification_user_register="Дођите и сликајте се! Снимите прави живот са својим пријатељима заједно!"
notification_friend_register=":name је такође на ЈustUs-у. Додати?"
notification_memory=":name, имаш нову успомену."
notification_wait_add_friend=":name, твоји пријатељи чекају!"
notification_touch=":name је додирнуо твоју фотографију💓"
notification_follow_user=":name пратио те!"
photo_copy_1="Додао сам вас на (JustUs). Преузмите ову апликацију да бисте дозволили мој захтев за пријатељство.Мој ИД:"
photo_tips_1="Успешно отпремљено! Додајте још пријатеља да заједно делите стварни живот"
photo_end_1="Нема више тренутака пријатеља. Снимите фотографију или додајте још пријатеља."
photo_copy_2="Додај ме на ЈustUs. Мој ИД:"
photo_tips_2="Успешно отпремљено! Додајте још пријатеља да заједно делите стварни живот"
photo_end_2="Нема више тренутака пријатеља. Снимите фотографију или додајте још пријатеља."
photo_copy_3="Додајте ме на ЈустУс да бисмо могли да делимо фотографије на нашем почетном екрану. Мој ИД:"
photo_tips_3="Послато на њихове почетне екране! Додајте још пријатеља да бисте делили своје стварне животе на почетним екранима."
photo_end_3="Нема више фотографија. Додајте још пријатеља да бисте делили своје стварне животе на почетним екранима."
photo_copy_4="Додајте ме на ЈустУс, имам фотографије за слање на ваш почетни екран. Мој ИД:"
photo_tips_4="Послато на њихове почетне екране! Додајте још пријатеља да бисте делили своје стварне животе на почетним екранима."
photo_end_4="Нема више фотографија. Додајте још пријатеља да бисте делили своје стварне животе на почетним екранима."
photo_copy_5="Додај ме на ЈустУс, нову видгет друштвену мрежу! Мој ИД:"
photo_tips_5="Послато на њихове почетне екране! Додајте још пријатеља да бисте делили своје стварне животе на почетним екранима."
photo_end_5="Нема више фотографија. Позовите још пријатеља да поделе ваше стварне животе на вашим почетним екранима."
photo_copy_6="Додај ме на ЈустУс - Видгет Социал Нетворк, све је спремно осим тебе!"
photo_tips_6="Послато на њихове почетне екране! Позовите још пријатеља да са њима поделите своје стварне животе."
photo_end_6="Нема више фотографија. Додајте још пријатеља да бисте са њима поделили своје стварне животе."
photo_copy_7="Додај ме на ЈустУс, све је спремно осим тебе! Мој ИД:"
photo_tips_7="Послато на њихове почетне екране! Позовите још пријатеља да са њима поделите своје стварне животе."
photo_end_7="Нема више фотографија. Додајте још пријатеља да бисте са њима поделили своје стварне животе."
photo_copy_8="Додајте ме на ЈустУс - Видгет Социал Нетворк, поделите прави живот са мном! Мој ИД:"
photo_tips_8="Послато на њихове почетне екране! Позовите још пријатеља да са њима поделите своје стварне животе."
photo_end_8="Нема више фотографија. Додајте још пријатеља да бисте са њима поделили своје стварне животе."
photo_copy_9="Прихватите изазов за фотографије из стварног живота, додајте ме на ЈустУс. Мој ИД:"
photo_tips_9="Послато на њихове почетне екране! Позовите још пријатеља да са њима поделите своје стварне животе."
photo_end_9="Нема више фотографија. Додајте још пријатеља да бисте са њима поделили своје стварне животе."
photo_copy_10="Желим да будеш на мом почетном екрану, додај ме на ЈустУс. Мој ИД:"
photo_tips_10="Послато на њихове почетне екране! Било би забавније ако додате још пријатеља."
photo_end_10="Нема више фотографија. Додајте још пријатеља да бисте заједно поделили своје стварне животе."
photo_copy_11="Желим да будеш на мом почетном екрану, додај ме на ЈустУс. Мој ИД:"
photo_tips_11="Послато на њихове почетне екране! Додајте још пријатеља да бисте послали своје фотографије на њихове почетне екране."
photo_end_11="Изгледа да сте остали без фотографија пријатеља! Додајте још пријатеља да бисте заједно снимили своје стварне животе."
photo_copy_12="Будите мој пријатељ са почетног екрана, додајте ме на ЈустУс. Мој ИД:"
photo_tips_12="Послато на њихове почетне екране! Позовите још пријатеља на почетни екран и пошаљите им забавне фотографије!"
photo_end_12="Изгледа да сте остали без фотографија пријатеља! Позовите још пријатеља на почетни екран и пошаљите им забавне фотографије."
photo_copy_13="Будите мој пријатељ са почетног екрана, додајте ме на ЈустУс. Мој ИД:"
photo_tips_13="Послато на њихове почетне екране! Било би забавније ако додате још пријатеља на почетни екран."
photo_end_13="Чини се да вам треба више пријатеља! Позовите још пријатеља на почетни екран и пошаљите им забавне фотографије."
your_self_visible="Само мени видљиво"
update_new_version="Нова функција дуета, дођите да надоградите и доживите је!"
