param_error="Chyba parametru"
component_num_limit="Dočasně nemůžete vytvořit další skupiny."
friend_num_limit="Dočasně nemůžete přidat další přátele."
operation_error="Operace se nezdařila. Prosím zkuste to znovu později!"
char_limit="Zadané znaky překračují limit maximální délky. Maximum :number znaků."
first_name_limit="Zadané „Příjmení“ překračuje limit maximální délky. Maximum :number znaků."
last_name_limit="Zadané „Jméno“ překračuje limit maximální délky. Maximum :number znaků."
first_name_required="Pole „Příjmení“ nemůže být prázdné."
last_name_required="Pole „Křestní jméno“ nemůže být prázdné."
mobile_error="Chyba formátu telefonního čísla"
mobile_required="Telefonní číslo nesmí být prázdné."
country_code_error="Chyba kódu země"
search_key="Zadejte prosím platné ID uživatele nebo číslo mobilního telefonu."
is_add_friend="Žádost o přidání přátelství byla odeslána."
system_error="Chyba systému"
msg_code_error="Chyba formátu ověřovacího kódu"
first_name_length="Příjmení je příliš dlouhé."
friends_exist="Uživatel nenalezen"
last_name_length="Křestní jméno je příliš dlouhé."
content_length="Maximálně 200 znaků"
he_friend_num_limit="Váš nebo uživatelův počet přátel dosáhl limitu."
sign_error="Ověření podpisu selhalo"
is_friends="Uživatel byl váš přítel."
sms_friend_tips="Přidejte si mě na gin-default."
photo_tips="Úspěšně nahráno! Přidejte si další přátele a sdílejte spolu skutečný život"
message_limit="Příliš často posíláte textové zprávy. Prosím zkuste to znovu později."
copy_friend_tips="Přidejte si mě na gin-default."
no_add_friend_self="Nemůžete se přidat jako přítele."
gin-default_slogan="Pojďme společně zaznamenat skutečný život!"
gin-default_helper="Průvodce gin-default"
bind_mobile_error="Telefonní číslo bylo svázáno s jiným účtem."
bound_mobile="Vazba se nezdařila. Prosím zkuste to znovu později."
not_add_self_friend="Nemůžete se přidat jako přítele."
address_book_tips="Synchronizujte své kontakty a najděte přátele, kteří již jsou na gin-default. Vaše kontaktní údaje budou odeslány společnosti gin-default, aby se zlepšila vaše zkušenost a umožnila vám i ostatním najít přátele."
follow_user="sledoval tě!"
notification_friends=":name se stal vaším přítelem „Jen my“! Zkuste jim poslat fotky!"
notification_like=":name se ti prostě líbilo!"
notification_comment=":name vás právě okomentoval, podívejte se!"
notification_friend_apply=":name vám poslal žádost o přátelství."
notification_friend_send_picture=":name zveřejnil(a) novou fotku."
notification_user_register="Přijďte se vyfotit! Nahrajte skutečný život se svými přáteli společně!"
notification_friend_register=":name je také na gin-default. Přidat?"
notification_memory=":name, máte novou paměť."
notification_wait_add_friend=":name, vaši přátelé čekají!"
notification_touch=":name zaklepal na vaši fotku💓"
notification_follow_user=":name sledoval tě!"
photo_copy_1="Přidal jsem si vás na (gin-default). Stáhněte si tuto aplikaci a povolte moji žádost o přátelství.Můj průkaz:"
photo_tips_1="Úspěšně nahráno! Přidejte si další přátele a sdílejte spolu skutečný život"
photo_end_1="Žádné další chvíle přátel. Pořiďte fotku nebo přidejte další přátele."
photo_copy_2="Přidejte si mě na gin-default.Můj průkaz:"
photo_tips_2="Úspěšně nahráno! Přidejte si další přátele a sdílejte spolu skutečný život"
photo_end_2="Žádné další chvíle přátel. Pořiďte fotku nebo přidejte další přátele."
photo_copy_3="Přidejte si mě na gin-default, abychom mohli sdílet fotografie na domovské obrazovce. Můj průkaz:"
photo_tips_3="Odesláno na jejich domovské obrazovky! Přidejte si další přátele a sdílejte své skutečné životy na svých domovských obrazovkách."
photo_end_3="Žádné další fotky. Přidejte si další přátele a sdílejte své skutečné životy na svých domovských obrazovkách."
photo_copy_4="Přidejte si mě na gin-default, mám fotky k odeslání na vaši domovskou obrazovku. Můj průkaz:"
photo_tips_4="Odesláno na jejich domovské obrazovky! Přidejte si další přátele a sdílejte své skutečné životy na svých domovských obrazovkách."
photo_end_4="Žádné další fotky. Přidejte si další přátele a sdílejte své skutečné životy na svých domovských obrazovkách."
photo_copy_5="Přidejte si mě na gin-default, nové sociální síti widgetů! Můj průkaz:"
photo_tips_5="Odesláno na jejich domovské obrazovky! Přidejte si další přátele a sdílejte své skutečné životy na svých domovských obrazovkách."
photo_end_5="Žádné další fotky. Pozvěte více přátel, aby sdíleli vaše skutečné životy na vašich domovských obrazovkách."
photo_copy_6="Přidejte si mě na gin-default - sociální síť Widget, vše je připraveno kromě vás!"
photo_tips_6="Odesláno na jejich domovské obrazovky! Pozvěte více přátel, abyste s nimi sdíleli své skutečné životy."
photo_end_6="Žádné další fotky. Přidejte si další přátele a sdílejte s nimi svůj skutečný život."
photo_copy_7="Přidejte si mě na gin-default, vše je připraveno kromě vás! Můj průkaz:"
photo_tips_7="Odesláno na jejich domovské obrazovky! Pozvěte více přátel, abyste s nimi sdíleli své skutečné životy."
photo_end_7="Žádné další fotky. Přidejte si další přátele a sdílejte s nimi svůj skutečný život."
photo_copy_8="Přidejte si mě na gin-default - Widget Social Network, sdílejte se mnou skutečný život! Můj průkaz:"
photo_tips_8="Odesláno na jejich domovské obrazovky! Pozvěte více přátel, abyste s nimi sdíleli své skutečné životy."
photo_end_8="Žádné další fotky. Přidejte si další přátele a sdílejte s nimi svůj skutečný život."
photo_copy_9="Přijměte skutečnou fotografickou výzvu, přidejte si mě na gin-default. Můj průkaz:"
photo_tips_9="Odesláno na jejich domovské obrazovky! Pozvěte více přátel, abyste s nimi sdíleli své skutečné životy."
photo_end_9="Žádné další fotky. Přidejte si další přátele a sdílejte s nimi svůj skutečný život."
photo_copy_10="Chci, abyste byli na mé domovské obrazovce, přidejte si mě na gin-default. Můj průkaz:"
photo_tips_10="Odesláno na jejich domovské obrazovky! Bylo by zábavnější, kdybyste přidali více přátel."
photo_end_10="Žádné další fotky. Přidejte si další přátele a sdílejte spolu své skutečné životy."
photo_copy_11="Chci, abyste byli na mé domovské obrazovce, přidejte si mě na gin-default. Můj průkaz:"
photo_tips_11="Odesláno na jejich domovské obrazovky! Přidejte další přátele a posílejte jim fotografie na jejich domovské obrazovky."
photo_end_11="Zdá se, že vám došly fotografie přátel! Přidejte si další přátele, abyste mohli společně zaznamenat své skutečné životy."
photo_copy_12="Buď můj přítel na úvodní obrazovce, přidej si mě na gin-default. Můj průkaz:"
photo_tips_12="Odesláno na jejich domovské obrazovky! Pozvěte více přátel na svou domovskou obrazovku a posílejte jim zábavné fotografie!"
photo_end_12="Zdá se, že vám došly fotografie přátel! Pozvěte více přátel na svou domovskou obrazovku a posílejte jim zábavné fotografie."
photo_copy_13="Buď můj přítel na úvodní obrazovce, přidej si mě na gin-default. Můj průkaz:"
photo_tips_13="Odesláno na jejich domovské obrazovky! Bylo by zábavnější, kdybyste přidali více přátel na úvodní obrazovce."
photo_end_13="Zdá se, že potřebujete více přátel! Pozvěte více přátel na svou domovskou obrazovku a posílejte jim zábavné fotografie."
your_self_visible="Viditelné pouze pro mě"
update_new_version="Nová funkce duetu, přijďte upgradovat a zažít to!"
