param_error="Ralat parameter"
component_num_limit="Anda tidak dapat membuat lebih banyak kumpulan buat sementara waktu."
friend_num_limit="Anda tidak dapat menambah lagi rakan buat sementara waktu."
operation_error="Operasi gagal. Sila cuba sebentar lagi!"
char_limit="Aksara yang anda masukkan melebihi had panjang maksimum. Maksimum :number aksara."
first_name_limit="Nama akhir yang anda masukkan melebihi had panjang maksimum. Maksimum :number aksara."
last_name_limit="Nama pertama yang anda masukkan melebihi had panjang maksimum. Maksimum :number aksara."
first_name_required="Nama akhir tidak boleh kosong."
last_name_required="Nama pertama tidak boleh kosong."
mobile_error="Ralat format nombor telefon"
mobile_required="Nombor telefon tidak boleh kosong."
country_code_error="Ralat kod negara"
search_key="Sila masukkan id pengguna atau nombor mudah alih yang sah."
is_add_friend="Tambah permintaan rakan telah dihantar."
system_error="Ralat sistem"
msg_code_error="Ralat format kod pengesahan"
first_name_length="Nama akhir terlalu panjang."
friends_exist="Pengguna tidak dijumpai"
last_name_length="Nama pertama terlalu panjang."
content_length="Maksimum 200 aksara"
he_friend_num_limit="Bilangan rakan anda atau pengguna telah mencapai had."
sign_error="Pengesahan tandatangan gagal"
is_friends="Pengguna itu telah menjadi rakan anda."
sms_friend_tips="Tambahkan saya di JustUs."
photo_tips="Berjaya dimuat naik! Tambah lebih ramai rakan untuk berkongsi kehidupan sebenar bersama"
message_limit="Anda terlalu kerap menghantar mesej teks. Sila cuba sebentar lagi."
copy_friend_tips="Tambahkan saya di JustUs."
no_add_friend_self="Anda tidak boleh menambah diri anda sebagai rakan."
justus_slogan="Mari merakam kehidupan sebenar bersama!"
justus_helper="Panduan JustUs"
bind_mobile_error="Nombor telefon telah diikat ke akaun lain."
bound_mobile="Pengikatan gagal. Sila cuba sebentar lagi."
not_add_self_friend="Anda tidak boleh menambah diri anda sebagai rakan."
address_book_tips="Segerakkan kenalan anda untuk mencari rakan yang sudah menggunakan JustUs. Data kenalan anda akan dihantar kepada JustUs untuk meningkatkan pengalaman anda dan membolehkan anda dan orang lain mencari rakan."
follow_user="mengikuti awak!"
notification_friends=":name telah menjadi rakan \"JustUs\" anda! Cuba hantar foto kepada mereka!"
notification_like=":name hanya menyukai anda!"
notification_comment=":name baru sahaja mengulas tentang anda, lihat!"
notification_friend_apply=":name menghantar permintaan rakan kepada anda."
notification_friend_send_picture=":name menyiarkan foto baharu."
notification_user_register="Datang dan ambil gambar! Rakam kehidupan sebenar bersama rakan anda bersama-sama!"
notification_friend_register=":name juga ada pada JustUs. Tambah?"
notification_memory=":name, anda mempunyai ingatan baharu."
notification_wait_add_friend=":name, rakan anda sedang menunggu!"
notification_touch=":name mengetik foto anda💓"
notification_follow_user=":name mengikuti awak!"
photo_copy_1="Saya telah menambah anda di (JustUs). Muat turun aplikasi ini untuk membenarkan permintaan rakan saya.ID saya:"
photo_tips_1="Berjaya dimuat naik! Tambah lebih ramai rakan untuk berkongsi kehidupan sebenar bersama"
photo_end_1="Tiada lagi detik kawan. Ambil foto atau tambah lebih ramai rakan."
photo_copy_2="Tambahkan saya di JustUs. ID saya:"
photo_tips_2="Berjaya dimuat naik! Tambah lebih ramai rakan untuk berkongsi kehidupan sebenar bersama"
photo_end_2="Tiada lagi detik kawan. Ambil foto atau tambah lebih ramai rakan."
photo_copy_3="Tambahkan saya di JustUs supaya kami boleh berkongsi foto ke skrin utama kami. ID saya:"
photo_tips_3="Dihantar ke skrin utama mereka! Tambah lebih ramai rakan untuk berkongsi kehidupan sebenar anda pada skrin utama anda."
photo_end_3="Tiada lagi foto. Tambah lebih ramai rakan untuk berkongsi kehidupan sebenar anda pada skrin utama anda."
photo_copy_4="Tambahkan saya di JustUs, saya mempunyai foto untuk dihantar ke skrin utama anda. ID saya:"
photo_tips_4="Dihantar ke skrin utama mereka! Tambah lebih ramai rakan untuk berkongsi kehidupan sebenar anda pada skrin utama anda."
photo_end_4="Tiada lagi foto. Tambah lebih ramai rakan untuk berkongsi kehidupan sebenar anda pada skrin utama anda."
photo_copy_5="Tambahkan saya di JustUs, rangkaian sosial widget baharu! ID saya:"
photo_tips_5="Dihantar ke skrin utama mereka! Tambah lebih ramai rakan untuk berkongsi kehidupan sebenar anda pada skrin utama anda."
photo_end_5="Tiada lagi foto. Jemput lebih ramai rakan untuk berkongsi kehidupan sebenar anda pada skrin utama anda."
photo_copy_6="Tambahkan saya di JustUs - Rangkaian Sosial Widget, semuanya sedia kecuali anda!"
photo_tips_6="Dihantar ke skrin utama mereka! Jemput lebih ramai rakan untuk berkongsi kehidupan sebenar anda dengan mereka."
photo_end_6="Tiada lagi foto. Tambah lebih ramai rakan untuk berkongsi kehidupan sebenar anda dengan mereka."
photo_copy_7="Tambah saya di JustUs, semuanya sedia kecuali anda! ID saya:"
photo_tips_7="Dihantar ke skrin utama mereka! Jemput lebih ramai rakan untuk berkongsi kehidupan sebenar anda dengan mereka."
photo_end_7="Tiada lagi foto. Tambah lebih ramai rakan untuk berkongsi kehidupan sebenar anda dengan mereka."
photo_copy_8="Tambahkan saya di JustUs - Rangkaian Sosial Widget, kongsi kehidupan sebenar dengan saya! ID saya:"
photo_tips_8="Dihantar ke skrin utama mereka! Jemput lebih ramai rakan untuk berkongsi kehidupan sebenar anda dengan mereka."
photo_end_8="Tiada lagi foto. Tambah lebih ramai rakan untuk berkongsi kehidupan sebenar anda dengan mereka."
photo_copy_9="Terima cabaran foto kehidupan sebenar, Tambah saya di JustUs. ID saya:"
photo_tips_9="Dihantar ke skrin utama mereka! Jemput lebih ramai rakan untuk berkongsi kehidupan sebenar anda dengan mereka."
photo_end_9="Tiada lagi foto. Tambah lebih ramai rakan untuk berkongsi kehidupan sebenar anda dengan mereka."
photo_copy_10="Saya mahu anda berada di skrin utama saya, tambahkan saya di JustUs. ID saya:"
photo_tips_10="Dihantar ke skrin utama mereka! Lebih seronok kalau tambah lagi kawan."
photo_end_10="Tiada lagi foto. Tambah lebih ramai rakan untuk berkongsi kehidupan sebenar anda bersama-sama."
photo_copy_11="Saya mahu anda berada di skrin utama saya, tambahkan saya di JustUs. ID saya:"
photo_tips_11="Dihantar ke skrin utama mereka! Tambahkan lebih ramai rakan untuk menghantar foto anda ke skrin utama mereka."
photo_end_11="Nampaknya anda kehabisan gambar rakan! Tambahkan lebih ramai rakan untuk merakam kehidupan sebenar anda bersama."
photo_copy_12="Jadi rakan skrin utama saya, tambahkan saya di JustUs. ID saya:"
photo_tips_12="Dihantar ke skrin utama mereka! Jemput lebih ramai rakan ke skrin utama anda dan hantar foto yang menyeronokkan kepada mereka!"
photo_end_12="Nampaknya anda kehabisan gambar rakan! Jemput lebih ramai rakan ke skrin utama anda dan hantar foto yang menyeronokkan kepada mereka."
photo_copy_13="Jadi rakan skrin utama saya, tambahkan saya di JustUs. ID saya:"
photo_tips_13="Dihantar ke skrin utama mereka! Lebih seronok jika anda menambah lebih ramai rakan skrin utama."
photo_end_13="Nampaknya anda memerlukan lebih ramai kawan! Jemput lebih ramai rakan ke skrin utama anda dan hantar foto yang menyeronokkan kepada mereka."
your_self_visible="Hanya kelihatan kepada saya"
update_new_version="Fungsi duet baharu, sila datang untuk menaik taraf dan mengalaminya!"
