param_error="Parameterfejl"
component_num_limit="Du kan midlertidigt ikke oprette flere grupper."
friend_num_limit="Du kan midlertidigt ikke tilføje flere venner."
operation_error="Handlingen mislykkedes. Prøv igen senere!"
char_limit="Zadané znaky překračují limit maximální délky. Maximum :number znaků."
first_name_limit="Zadané „Příjmení“ překračuje limit maximální délky. Maximum :number znaků."
last_name_limit="Zadané „Jméno“ překračuje limit maximální délky. Maximum :number znaků."
first_name_required="Efternavn må ikke være tomt."
last_name_required="Fornavn må ikke være tomt."
mobile_error="Telefonnummerformateringsfejl"
mobile_required="Telefonnummeret må ikke være tomt."
country_code_error="Landekodefejl"
search_key="Indtast venligst et gyldigt bruger-id eller mobilnummer."
is_add_friend="Tilføj venneanmodning er blevet sendt."
system_error="Systemfejl"
msg_code_error="Bekræftelseskodeformatfejl"
first_name_length="Efternavn er for langt."
friends_exist="Bruger ikke fundet"
last_name_length="Fornavn er for langt."
content_length="De maksimale 200 tegn"
he_friend_num_limit="Dit eller brugerens antal venner har nået grænsen."
sign_error="Verificering af signatur mislykkedes"
is_friends="Brugeren har været din ven."
sms_friend_tips="Tilføj mig på JustUs."
photo_tips="Uploadet med succes! Tilføj flere venner for at dele det virkelige liv sammen"
message_limit="Du sender tekstbeskeder for ofte. Prøv igen senere."
copy_friend_tips="Tilføj mig på JustUs."
no_add_friend_self="Du kan ikke tilføje dig selv som ven."
justus_slogan="Lad os optage det virkelige liv sammen!"
justus_helper="JustUs guide"
bind_mobile_error="Telefonnummeret er blevet bundet til en anden konto."
bound_mobile="Binding mislykkedes. Prøv igen senere."
not_add_self_friend="Du kan ikke tilføje dig selv som ven."
address_book_tips="Synkroniser dine kontakter for at finde venner, der allerede er på JustUs. Dine kontaktdata vil blive sendt til JustUs for at forbedre din oplevelse og give dig og andre mulighed for at finde venner."
follow_user="fulgte dig!"
notification_friends=":name er blevet din \"Bare os\"-ven! Prøv at sende dem billeder!"
notification_like=":name kunne bare lide dig!"
notification_comment=":name har lige kommenteret dig, tjek det ud!"
notification_friend_apply=":name sendte dig en venneanmodning."
notification_friend_send_picture=":name har slået et nyt billede op."
notification_user_register="Kom og tag et billede! Optag det virkelige liv med dine venner sammen!"
notification_friend_register=":name er også på JustUs. Tilføje?"
notification_memory=":name, du har en ny hukommelse."
notification_wait_add_friend=":name, dine venner venter!"
notification_touch=":name trykkede på dit billede💓"
notification_follow_user=":name fulgte dig!"
photo_copy_1="Jeg har tilføjet dig på (JustUs). Download denne app for at tillade min venneanmodning.Mit ID:"
photo_tips_1="Uploadet med succes! Tilføj flere venner for at dele det virkelige liv sammen"
photo_end_1="Ikke flere venners øjeblikke. Tag et billede, eller tilføj flere venner."
photo_copy_2="Tilføj mig på JustUs.Mit ID:"
photo_tips_2="Uploadet med succes! Tilføj flere venner for at dele det virkelige liv sammen"
photo_end_2="Ikke flere venners øjeblikke. Tag et billede, eller tilføj flere venner."
photo_copy_3="Tilføj mig på JustUs, så vi kan dele billeder til vores startskærm. Mit ID:"
photo_tips_3="Sendt til deres startskærme! Tilføj flere venner for at dele dit virkelige liv på dine hjemmeskærme."
photo_end_3="Ikke flere billeder. Tilføj flere venner for at dele dit virkelige liv på dine hjemmeskærme."
photo_copy_4="Tilføj mig på JustUs, jeg har billeder at sende til din startskærm. Mit ID:"
photo_tips_4="Sendt til deres startskærme! Tilføj flere venner for at dele dit virkelige liv på dine hjemmeskærme."
photo_end_4="Ikke flere billeder. Tilføj flere venner for at dele dit virkelige liv på dine hjemmeskærme."
photo_copy_5="Tilføj mig på JustUs, det nye widget sociale netværk! Mit ID:"
photo_tips_5="Sendt til deres startskærme! Tilføj flere venner for at dele dit virkelige liv på dine hjemmeskærme."
photo_end_5="Ikke flere billeder. Inviter flere venner til at dele dit virkelige liv på dine hjemmeskærme."
photo_copy_6="Tilføj mig på JustUs - Widget Social Network, alt er klar undtagen dig!"
photo_tips_6="Sendt til deres startskærme! Inviter flere venner til at dele dit virkelige liv med dem."
photo_end_6="Ikke flere billeder. Tilføj flere venner for at dele dit virkelige liv med dem."
photo_copy_7="Tilføj mig på JustUs, alt er klar undtagen dig! Mit ID:"
photo_tips_7="Sendt til deres startskærme! Inviter flere venner til at dele dit virkelige liv med dem."
photo_end_7="Ikke flere billeder. Tilføj flere venner for at dele dit virkelige liv med dem."
photo_copy_8="Tilføj mig på JustUs - Widget Social Network, del det virkelige liv med mig! Mit ID:"
photo_tips_8="Sendt til deres startskærme! Inviter flere venner til at dele dit virkelige liv med dem."
photo_end_8="Ikke flere billeder. Tilføj flere venner for at dele dit virkelige liv med dem."
photo_copy_9="Accepter den virkelige fotoudfordring, Tilføj mig på JustUs. Mit ID:"
photo_tips_9="Sendt til deres startskærme! Inviter flere venner til at dele dit virkelige liv med dem."
photo_end_9="Ikke flere billeder. Tilføj flere venner for at dele dit virkelige liv med dem."
photo_copy_10="Jeg vil have dig til at være på min startskærm, tilføj mig på JustUs. Mit ID:"
photo_tips_10="Sendt til deres startskærme! Det ville være sjovere, hvis du tilføjer flere venner."
photo_end_10="Ikke flere billeder. Tilføj flere venner for at dele jeres virkelige liv sammen."
photo_copy_11="Jeg vil have dig til at være på min startskærm, tilføj mig på JustUs. Mit ID:"
photo_tips_11="Sendt til deres startskærme! Tilføj flere venner for at sende dine billeder til deres startskærme."
photo_end_11="Det ser ud til, at du er løbet tør for venners billeder! Tilføj flere venner for at optage jeres virkelige liv sammen."
photo_copy_12="Vær min hjemmeskærmsven, tilføj mig på JustUs. Mit ID:"
photo_tips_12="Sendt til deres startskærme! Inviter flere venner til din startskærm, og send dem sjove billeder!"
photo_end_12="Det ser ud til, at du er løbet tør for venners billeder! Inviter flere venner til din startskærm, og send dem sjove billeder."
photo_copy_13="Vær min hjemmeskærmsven, tilføj mig på JustUs. Mit ID:"
photo_tips_13="Sendt til deres startskærme! Det ville være sjovere, hvis du tilføjer flere venner på hjemmeskærmen."
photo_end_13="Det ser ud til, at du har brug for flere venner! Inviter flere venner til din startskærm, og send dem sjove billeder."
your_self_visible="Kun synlig for mig"
update_new_version="Ny duetfunktion, kom venligst for at opgradere og oplev det!"
