param_error="Error sa parameter"
component_num_limit="Pansamantalang hindi ka makakagawa ng higit pang mga grupo."
friend_num_limit="Pansamantala kang hindi makakapagdagdag ng higit pang mga kaibigan."
operation_error="Nabigo ang operasyon. Subukang muli mamaya!"
char_limit="Ang mga character na iyong ipinasok ay lumampas sa maximum na limitasyon sa haba. Ang maximum :number character."
first_name_limit="Ang \"Apelyido\" na iyong inilagay ay lumampas sa maximum na limitasyon sa haba. Ang maximum :number character."
last_name_limit="Ang \"Unang pangalan\" na iyong inilagay ay lumampas sa maximum na limitasyon sa haba. Ang maximum :number character."
first_name_required="Ang \"Apelyido\" ay hindi maaaring walang laman."
last_name_required="Ang \"Unang pangalan\" ay hindi maaaring walang laman."
mobile_error="Error sa format ng numero ng telepono"
mobile_required="Hindi maaaring walang laman ang numero ng telepono."
country_code_error="Error sa code ng bansa"
search_key="Mangyaring magpasok ng wastong user id o numero ng mobile."
is_add_friend="Naipadala na ang hiling na magdagdag ng kaibigan."
system_error="Error sa system"
msg_code_error="Error sa format ng verification code"
first_name_length="Ang \"Apelyido\" ay masyadong mahaba."
friends_exist="Hindi Nahanap ang User"
last_name_length="Ang \"Unang pangalan\" ay masyadong mahaba."
content_length="Ang maximum na 200 character"
he_friend_num_limit="Ang bilang mo o ng user ng mga kaibigan ay umabot na sa limitasyon."
sign_error="Nabigo ang pag-verify ng lagda"
is_friends="Ang gumagamit ay naging kaibigan mo."
sms_friend_tips="Add mo ako sa JustUs."
photo_tips="Matagumpay na na-upload! Magdagdag ng higit pang mga kaibigan upang ibahagi ang totoong buhay nang magkasama"
message_limit="Masyado kang madalas magpadala ng mga text message. Subukang muli mamaya."
copy_friend_tips="Add mo ako sa JustUs."
no_add_friend_self="Hindi mo maaaring idagdag ang iyong sarili bilang isang kaibigan."
justus_slogan="Sama-sama tayong mag-record ng totoong buhay!"
justus_helper="Gabay sa JustUs"
bind_mobile_error="Ang numero ng telepono ay nakatali sa ibang account."
bound_mobile="Nabigo ang pagbubuklod. Subukang muli mamaya."
not_add_self_friend="Hindi mo maaaring idagdag ang iyong sarili bilang isang kaibigan."
address_book_tips="I-sync ang iyong mga contact upang makahanap ng mga kaibigan na nasa JustUs. Ang iyong data ng mga contact ay ipapadala sa JustUs upang pahusayin ang iyong karanasan at payagan ka at ang iba pa na makahanap ng mga kaibigan."
follow_user="sinundan kita!"
notification_friends="Ang :name ay naging iyong \"JustUs\" na kaibigan! Subukang magpadala sa kanila ng mga larawan!"
notification_like="Nagustuhan ka lang ni :name!"
notification_comment="Nagkomento lang si :name sa iyo, tingnan mo!"
notification_friend_apply="Nagpadala sa iyo si :name ng isang friend request."
notification_friend_send_picture="Nag-post si :name ng bagong larawan."
notification_user_register="Halika at kumuha ng litrato! Mag-record ng totoong buhay kasama ang iyong mga kaibigan nang magkasama!"
notification_friend_register=":name nasa JustUs din ang. Idagdag?"
notification_memory=":name, mayroon kang bagong alaala."
notification_wait_add_friend=":name, naghihintay ang iyong mga kaibigan!"
notification_touch="Tinapik ni :name ang iyong larawan💓"
notification_follow_user=":name sinundan kita!"
photo_copy_1="Na-add na kita sa (JustUs). I-download ang app na ito para payagan ang aking friend request.Aking ID:"
photo_tips_1="Matagumpay na na-upload! Magdagdag ng higit pang mga kaibigan upang ibahagi ang totoong buhay nang magkasama"
photo_end_1="Wala nang friends' moments. Kumuha ng larawan o magdagdag ng higit pang mga kaibigan."
photo_copy_2="Add mo ako sa JustUs. Aking ID:"
photo_tips_2="Matagumpay na na-upload! Magdagdag ng higit pang mga kaibigan upang ibahagi ang totoong buhay nang magkasama"
photo_end_2="Wala nang friends' moments. Kumuha ng larawan o magdagdag ng higit pang mga kaibigan."
photo_copy_3="Idagdag ako sa JustUs para makapagbahagi kami ng mga larawan sa aming homescreen. Aking ID:"
photo_tips_3="Ipinadala sa kanilang mga homescreen! Magdagdag ng higit pang mga kaibigan upang ibahagi ang iyong mga totoong buhay sa iyong mga homescreen."
photo_end_3="Wala nang mga larawan. Magdagdag ng higit pang mga kaibigan upang ibahagi ang iyong mga totoong buhay sa iyong mga homescreen."
photo_copy_4="Idagdag ako sa JustUs, mayroon akong mga larawang ipapadala sa iyong homescreen. Aking ID:"
photo_tips_4="Ipinadala sa kanilang mga homescreen! Magdagdag ng higit pang mga kaibigan upang ibahagi ang iyong mga totoong buhay sa iyong mga homescreen."
photo_end_4="Wala nang mga larawan. Magdagdag ng higit pang mga kaibigan upang ibahagi ang iyong mga totoong buhay sa iyong mga homescreen."
photo_copy_5="Idagdag ako sa JustUs, ang bagong widget na social network! Aking ID:"
photo_tips_5="Ipinadala sa kanilang mga homescreen! Magdagdag ng higit pang mga kaibigan upang ibahagi ang iyong mga totoong buhay sa iyong mga homescreen."
photo_end_5="Wala nang mga larawan. Mag-imbita ng higit pang mga kaibigan na ibahagi ang iyong totoong buhay sa iyong mga homescreen."
photo_copy_6="Idagdag ako sa JustUs - Widget Social Network, handa na ang lahat maliban sa iyo!"
photo_tips_6="Ipinadala sa kanilang mga homescreen! Mag-imbita ng higit pang mga kaibigan upang ibahagi ang iyong totoong buhay sa kanila."
photo_end_6="Wala nang mga larawan. Magdagdag ng higit pang mga kaibigan upang ibahagi ang iyong totoong buhay sa kanila."
photo_copy_7="Idagdag ako sa JustUs, handa na ang lahat maliban sa iyo! Aking ID:"
photo_tips_7="Ipinadala sa kanilang mga homescreen! Mag-imbita ng higit pang mga kaibigan upang ibahagi ang iyong totoong buhay sa kanila."
photo_end_7="Wala nang mga larawan. Magdagdag ng higit pang mga kaibigan upang ibahagi ang iyong totoong buhay sa kanila."
photo_copy_8="Idagdag ako sa JustUs - Widget Social Network, ibahagi sa akin ang totoong buhay! Aking ID:"
photo_tips_8="Ipinadala sa kanilang mga homescreen! Mag-imbita ng higit pang mga kaibigan upang ibahagi ang iyong totoong buhay sa kanila."
photo_end_8="Wala nang mga larawan. Magdagdag ng higit pang mga kaibigan upang ibahagi ang iyong totoong buhay sa kanila."
photo_copy_9="Tanggapin ang totoong buhay na hamon sa larawan, Idagdag ako sa JustUs. Aking ID:"
photo_tips_9="Ipinadala sa kanilang mga homescreen! Mag-imbita ng higit pang mga kaibigan upang ibahagi ang iyong totoong buhay sa kanila."
photo_end_9="Wala nang mga larawan. Magdagdag ng higit pang mga kaibigan upang ibahagi ang iyong totoong buhay sa kanila."
photo_copy_10="Gusto kong nasa homescreen ka, idagdag mo ako sa JustUs. Aking ID:"
photo_tips_10="Ipinadala sa kanilang mga homescreen! Mas masaya kung magdadagdag ka pa ng mga kaibigan."
photo_end_10="Wala nang mga larawan. Magdagdag ng higit pang mga kaibigan upang ibahagi ang iyong totoong buhay nang magkasama."
photo_copy_11="Gusto kong nasa homescreen ka, idagdag mo ako sa JustUs. Aking ID:"
photo_tips_11="Ipinadala sa kanilang mga homescreen! Magdagdag ng higit pang mga kaibigan upang ipadala ang iyong mga larawan sa kanilang mga homescreen."
photo_end_11="Mukhang naubusan ka ng mga larawan ng mga kaibigan! Magdagdag ng higit pang mga kaibigan upang itala ang iyong totoong buhay nang magkasama."
photo_copy_12="Maging kaibigan ko sa homescreen, idagdag ako sa JustUs. Aking ID:"
photo_tips_12="Ipinadala sa kanilang mga homescreen! Mag-imbita ng higit pang mga kaibigan sa iyong homescreen at magpadala sa kanila ng mga masasayang larawan!"
photo_end_12="Mukhang naubusan ka ng mga larawan ng mga kaibigan! Mag-imbita ng higit pang mga kaibigan sa iyong homescreen at magpadala sa kanila ng mga masasayang larawan."
photo_copy_13="Maging kaibigan ko sa homescreen, idagdag ako sa JustUs. Aking ID:"
photo_tips_13="Ipinadala sa kanilang mga homescreen! Mas magiging masaya kung magdagdag ka ng higit pang mga kaibigan sa homescreen."
photo_end_13="Mukhang kailangan mo ng higit pang mga kaibigan! Mag-imbita ng higit pang mga kaibigan sa iyong homescreen at magpadala sa kanila ng mga masasayang larawan."
your_self_visible="Sa akin lang nakikita"
update_new_version="Bagong duet function, mangyaring pumunta upang mag-upgrade at maranasan ito!"
