param_error="Σφάλμα παραμέτρου"
component_num_limit="Δεν μπορείτε προσωρινά να δημιουργήσετε περισσότερες ομάδες."
friend_num_limit="Δεν μπορείτε προσωρινά να προσθέσετε περισσότερους φίλους."
operation_error="Η λειτουργία απέτυχε. Παρακαλώ δοκιμάστε ξανά αργότερα!"
char_limit="Οι χαρακτήρες που εισαγάγατε υπερβαίνουν το μέγιστο όριο μήκους. Το μέγιστο :number χαρακτήρες."
first_name_limit="Το \"Επώνυμο\" που καταχωρίσατε υπερβαίνει το μέγιστο όριο μήκους. Το μέγιστο :number χαρακτήρες."
last_name_limit="Το \"Όνομα\" που εισαγάγατε υπερβαίνει το μέγιστο όριο μήκους. Το μέγιστο :number χαρακτήρες."
first_name_required="Το \"Επώνυμο\" δεν μπορεί να είναι κενό."
last_name_required="Το \"First name\" δεν μπορεί να είναι κενό."
mobile_error="Σφάλμα μορφής αριθμού τηλεφώνου"
mobile_required="Ο αριθμός τηλεφώνου δεν μπορεί να είναι κενός."
country_code_error="Σφάλμα κωδικού χώρας"
search_key="Εισαγάγετε ένα έγκυρο αναγνωριστικό χρήστη ή έναν αριθμό κινητού τηλεφώνου."
is_add_friend="Το αίτημα προσθήκης φιλίας έχει σταλεί."
system_error="Σφάλμα συστήματος"
msg_code_error="Σφάλμα μορφής κωδικού επαλήθευσης"
first_name_length="Το \"Επώνυμο\" είναι πολύ μεγάλο."
friends_exist="Ο χρήστης δεν βρέθηκε"
last_name_length="Το \"First name\" είναι πολύ μεγάλο."
content_length="Το μέγιστο 200 χαρακτήρες"
he_friend_num_limit="Ο αριθμός των φίλων σας ή του χρήστη έχει φτάσει το όριο."
sign_error="Η επαλήθευση της υπογραφής απέτυχε"
is_friends="Ο χρήστης ήταν φίλος σας."
sms_friend_tips="Προσθέστε με στο JustUs."
photo_tips="Μεταφορτώθηκε με επιτυχία! Προσθέστε περισσότερους φίλους για να μοιραστείτε την πραγματική ζωή μαζί"
message_limit="Στέλνετε πολύ συχνά μηνύματα κειμένου. Παρακαλώ δοκιμάστε ξανά αργότερα."
copy_friend_tips="Προσθέστε με στο JustUs."
no_add_friend_self="Δεν μπορείτε να προσθέσετε τον εαυτό σας ως φίλο."
justus_slogan="Ελάτε να καταγράψουμε μαζί την πραγματική ζωή!"
justus_helper="Οδηγός JustUs"
bind_mobile_error="Ο αριθμός τηλεφώνου έχει δεσμευτεί σε άλλο λογαριασμό."
bound_mobile="Η δέσμευση απέτυχε. Παρακαλώ δοκιμάστε ξανά αργότερα."
not_add_self_friend="Δεν μπορείτε να προσθέσετε τον εαυτό σας ως φίλο."
address_book_tips="Συγχρονίστε τις επαφές σας για να βρείτε φίλους ήδη στο JustUs. Τα δεδομένα των επαφών σας θα σταλούν στο JustUs για να βελτιώσουν την εμπειρία σας και να επιτρέψουν σε εσάς και σε άλλους να βρείτε φίλους."
follow_user="σε ακολούθησα!"
notification_friends="Ο :name έγινε φίλος σας \"JustUs\"! Δοκιμάστε να τους στείλετε φωτογραφίες!"
notification_like=":name μόλις σας άρεσε!"
notification_comment="Ο :name μόλις σας σχολίασε, δείτε το!"
notification_friend_apply="Ο :name σάς έστειλε ένα αίτημα φιλίας."
notification_friend_send_picture="Ο :name δημοσίευσε μια νέα φωτογραφία."
notification_user_register="Ελάτε να βγάλετε μια φωτογραφία! Καταγράψτε μαζί την πραγματική ζωή με τους φίλους σας!"
notification_friend_register=":name είναι επίσης στο JustUs. Προσθήκη?"
notification_memory=":name, έχετε νέα μνήμη."
notification_wait_add_friend=":name, οι φίλοι σας περιμένουν!"
notification_touch="Ο :name πάτησε τη φωτογραφία σου💓"
notification_follow_user=":name σε ακολούθησα!"
photo_copy_1="Σας έχω προσθέσει στο (JustUs). Κάντε λήψη αυτής της εφαρμογής για να επιτρέψετε το αίτημα φιλίας μου.Η ταυτότητά μου:"
photo_tips_1="Μεταφορτώθηκε με επιτυχία! Προσθέστε περισσότερους φίλους για να μοιραστείτε την πραγματική ζωή μαζί"
photo_end_1="Όχι άλλες στιγμές φίλων. Τραβήξτε μια φωτογραφία ή προσθέστε περισσότερους φίλους."
photo_copy_2="Προσθέστε με στο JustUs. Η ταυτότητά μου:"
photo_tips_2="Μεταφορτώθηκε με επιτυχία! Προσθέστε περισσότερους φίλους για να μοιραστείτε την πραγματική ζωή μαζί"
photo_end_2="Όχι άλλες στιγμές φίλων. Τραβήξτε μια φωτογραφία ή προσθέστε περισσότερους φίλους."
photo_copy_3="Προσθέστε με στο JustUs για να μπορούμε να κοινοποιούμε φωτογραφίες στην αρχική μας οθόνη. Η ταυτότητά μου:"
photo_tips_3="Στάλθηκε στις αρχικές οθόνες τους! Προσθέστε περισσότερους φίλους για να μοιραστείτε τις πραγματικές σας ζωές στις αρχικές οθόνες σας."
photo_end_3="Όχι άλλες φωτογραφίες. Προσθέστε περισσότερους φίλους για να μοιραστείτε τις πραγματικές σας ζωές στις αρχικές οθόνες σας."
photo_copy_4="Προσθέστε με στο JustUs, έχω φωτογραφίες να στείλω στην αρχική σας οθόνη. Η ταυτότητά μου:"
photo_tips_4="Στάλθηκε στις αρχικές οθόνες τους! Προσθέστε περισσότερους φίλους για να μοιραστείτε τις πραγματικές σας ζωές στις αρχικές οθόνες σας."
photo_end_4="Όχι άλλες φωτογραφίες. Προσθέστε περισσότερους φίλους για να μοιραστείτε τις πραγματικές σας ζωές στις αρχικές οθόνες σας."
photo_copy_5="Προσθέστε με στο JustUs, το νέο κοινωνικό δίκτυο widget! Η ταυτότητά μου:"
photo_tips_5="Στάλθηκε στις αρχικές οθόνες τους! Προσθέστε περισσότερους φίλους για να μοιραστείτε τις πραγματικές σας ζωές στις αρχικές οθόνες σας."
photo_end_5="Όχι άλλες φωτογραφίες. Προσκαλέστε περισσότερους φίλους να μοιραστούν τις πραγματικές σας ζωές στις αρχικές σας οθόνες."
photo_copy_6="Προσθέστε με στο JustUs - Widget Social Network, όλα είναι έτοιμα εκτός από εσάς!"
photo_tips_6="Στάλθηκε στις αρχικές οθόνες τους! Προσκαλέστε περισσότερους φίλους να μοιραστείτε μαζί τους την πραγματική σας ζωή."
photo_end_6="Όχι άλλες φωτογραφίες. Προσθέστε περισσότερους φίλους για να μοιραστείτε την πραγματική σας ζωή μαζί τους."
photo_copy_7="Προσθέστε με στο JustUs, όλα είναι έτοιμα εκτός από εσάς! Η ταυτότητά μου:"
photo_tips_7="Στάλθηκε στις αρχικές οθόνες τους! Προσκαλέστε περισσότερους φίλους να μοιραστείτε μαζί τους την πραγματική σας ζωή."
photo_end_7="Όχι άλλες φωτογραφίες. Προσθέστε περισσότερους φίλους για να μοιραστείτε την πραγματική σας ζωή μαζί τους."
photo_copy_8="Προσθέστε με στο JustUs - Widget Social Network, μοιραστείτε την πραγματική ζωή μαζί μου! Η ταυτότητά μου:"
photo_tips_8="Στάλθηκε στις αρχικές οθόνες τους! Προσκαλέστε περισσότερους φίλους να μοιραστείτε μαζί τους την πραγματική σας ζωή."
photo_end_8="Όχι άλλες φωτογραφίες. Προσθέστε περισσότερους φίλους για να μοιραστείτε την πραγματική σας ζωή μαζί τους."
photo_copy_9="Αποδεχτείτε την πραγματική πρόκληση φωτογραφιών, Προσθέστε με στο JustUs. Η ταυτότητά μου:"
photo_tips_9="Στάλθηκε στις αρχικές οθόνες τους! Προσκαλέστε περισσότερους φίλους να μοιραστείτε μαζί τους την πραγματική σας ζωή."
photo_end_9="Όχι άλλες φωτογραφίες. Προσθέστε περισσότερους φίλους για να μοιραστείτε την πραγματική σας ζωή μαζί τους."
photo_copy_10="Θέλω να είστε στην αρχική μου οθόνη, προσθέστε με στο JustUs. Η ταυτότητά μου:"
photo_tips_10="Στάλθηκε στις αρχικές οθόνες τους! Θα ήταν πιο διασκεδαστικό αν προσθέσετε περισσότερους φίλους."
photo_end_10="Όχι άλλες φωτογραφίες. Προσθέστε περισσότερους φίλους για να μοιραστείτε μαζί την πραγματική σας ζωή."
photo_copy_11="Θέλω να είστε στην αρχική μου οθόνη, προσθέστε με στο JustUs. Η ταυτότητά μου:"
photo_tips_11="Στάλθηκε στις αρχικές οθόνες τους! Προσθέστε περισσότερους φίλους για να στείλετε τις φωτογραφίες σας στις αρχικές τους οθόνες."
photo_end_11="Φαίνεται ότι έχετε ξεμείνει από φωτογραφίες φίλων! Προσθέστε περισσότερους φίλους για να καταγράψετε την πραγματική σας ζωή μαζί."
photo_copy_12="Γίνετε φίλος της αρχικής οθόνης μου, προσθέστε με στο JustUs. Η ταυτότητά μου:"
photo_tips_12="Στάλθηκε στις αρχικές οθόνες τους! Προσκαλέστε περισσότερους φίλους στην αρχική σας οθόνη και στείλτε τους διασκεδαστικές φωτογραφίες!"
photo_end_12="Φαίνεται ότι έχετε ξεμείνει από φωτογραφίες φίλων! Προσκαλέστε περισσότερους φίλους στην αρχική σας οθόνη και στείλτε τους διασκεδαστικές φωτογραφίες."
photo_copy_13="Γίνετε φίλος της αρχικής οθόνης μου, προσθέστε με στο JustUs. Η ταυτότητά μου:"
photo_tips_13="Στάλθηκε στις αρχικές οθόνες τους! Θα ήταν πιο διασκεδαστικό αν προσθέσετε περισσότερους φίλους στην αρχική οθόνη."
photo_end_13="Φαίνεται ότι χρειάζεσαι περισσότερους φίλους! Προσκαλέστε περισσότερους φίλους στην αρχική σας οθόνη και στείλτε τους διασκεδαστικές φωτογραφίες."
your_self_visible="Ορατό μόνο σε εμένα"
update_new_version="Νέα λειτουργία ντουέτου, ελάτε να το αναβαθμίσετε και να το ζήσετε!"
