param_error="Parameter error"
component_num_limit="You are temporarily unable to create more groups."
friend_num_limit="You are temporarily unable to add more friends."
operation_error="Operation failed. Please try again later!"
char_limit="The characters you entered exceed the maximum length limit. The maximum :number characters."
first_name_limit="The \"Last name\" you entered exceed the maximum length limit. The maximum :number characters."
last_name_limit="The \"First name\" you entered exceed the maximum length limit. The maximum :number characters."
first_name_required="The \"Last name\" cannot be empty."
last_name_required="The \"First name\" cannot be empty."
mobile_error="Phone number format error"
mobile_required="The phone number cannot be empty."
country_code_error="Country code error"
search_key="Please enter a valid user id or mobile number."
is_add_friend="Friend request has been sent."
system_error="System error"
msg_code_error="Verification code error"
first_name_length="The \"Last name\" is too long."
friends_exist="User Not Found"
last_name_length="The \"First name\" is too long."
content_length="The maximum 200 characters"
he_friend_num_limit="Your or the user's number of friends has reached the limit."
sign_error="Signature verification failed"
is_friends="You are already friends"
sms_friend_tips="Add me on JustUs."
photo_tips="Uploaded successfully! Add more friends to share real life together"
message_limit="You send text messages too often. Please try again later."
copy_friend_tips="Add me on JustUs."
no_add_friend_self="You can not add yourself as a friend."
justus_slogan="Record real life together!"
justus_helper="JustUs Guide"
bind_mobile_error="The phone number has been bound to another account."
bound_mobile="Binding failed. Please try again later."
not_add_self_friend="You can't add yourself as a friend."
address_book_tips="Sync your contacts to find friends already on JustUs. Your contacts data will be sent to JustUs to improve your experience and allow you and others to find friends."
follow_user="just followed you!"
notification_friends=":name has become your \"JustUs\" friend! Try sending them photos!"
notification_like=":name just liked you!"
notification_comment=":name just commented on you, check it out!"
notification_friend_apply=":name sent you a friend request."
notification_friend_send_picture=":name posted a new photo."
notification_user_register="Come and take a photo! Record real life with your friends together!"
notification_friend_register=":name is also on JustUs. Add？"
notification_memory=":name, you have a new memory."
notification_wait_add_friend=":name, your friends are waiting on JustUs!"
notification_touch=":name touched your photo💓"
notification_follow_user=":name just followed you!"
photo_copy_1="I have added you on (JustUs). Download this app to accept my friend request.My ID:"
photo_tips_1="Uploaded successfully! Add more friends to share real life together"
photo_end_1="No more friends' moments. Take a photo or add more friends."
photo_copy_2="Add me on JustUs. My ID:"
photo_tips_2="Uploaded successfully! Add more friends to share real life together"
photo_end_2="No more friends' moments. Take a photo or add more friends."
photo_copy_3="Add me on JustUs so we can share photos to our homescreen. My ID:"
photo_tips_3="Sent to their homescreens! Add more friends to share your real lives on your homescreens."
photo_end_3="No more photos. Add more friends to share your real lives on your homescreens."
photo_copy_4="Add me on JustUs, I have photos to send to your homescreen. My ID:"
photo_tips_4="Sent to their homescreens! Add more friends to share your real lives on your homescreens."
photo_end_4="No more photos. Add more friends to share your real lives on your homescreens."
photo_copy_5="Add me on JustUs, the new widget social network! My ID:"
photo_tips_5="Sent to their homescreens! Add more friends to share your real lives on your homescreens."
photo_end_5="No more photos. Invite more friends to share your real lives on your homescreens."
photo_copy_6="Add me on JustUs - Widget Social Network, all is ready except you! My ID:"
photo_tips_6="Sent to their homescreens! Invite more friends to share your real lives with them."
photo_end_6="No more photos. Add more friends to share your real lives with them."
photo_copy_7="Add me on JustUs, all is ready excepet you! My ID:"
photo_tips_7="Sent to their homescreens! Invite more friends to share your real lives with them."
photo_end_7="No more photos. Add more friends to share your real lives with them."
photo_copy_8="Add me on JustUs - Widget Social Network, share real life with me! My ID:"
photo_tips_8="Sent to their homescreens! Invite more friends to share your real lives with them."
photo_end_8="No more photos. Add more friends to share your real lives with them."
photo_copy_9="Accept the real life photo challenge, Add me on JustUs. My ID:"
photo_tips_9="Sent to their homescreens! Invite more friends to share your real lives with them."
photo_end_9="No more photos. Add more friends to share your real lives with them."
photo_copy_10="I want you to be on my homescreen, add me on JustUs. My ID:"
photo_tips_10="Sent to their homescreens! It would be more fun if you add more friends."
photo_end_10="No more photos. Add more friends to share your real lives together."
photo_copy_11="I want you to be on my homescreen, add me on JustUs. My ID:"
photo_tips_11="Sent to their homescreens! Add more friends to send your photos to their homescreens."
photo_end_11="Seems you've run out of friends' photos! Add more friends to record your real lives together."
photo_copy_12="Be my homescreen friend, add me on JustUs. My ID:"
photo_tips_12="Sent to their homescreens! Invite more friends to your homescreen and send them fun photos!"
photo_end_12="Seems you've run out of friends' photos! Invite more friends to your homescreen and send them fun photos."
photo_copy_13="Be my homescreen friend, add me on JustUs. My ID:"
photo_tips_13="Sent to their homescreens! It would be more fun if you add more homescreen friends."
photo_end_13="Seems you need more friends! Invite more friends to your homescreen and send them fun photos."
your_self_visible="Only visible to me"
update_new_version="New duet function, please upgrade to experience it!"
