param_error="パラメータエラー"
component_num_limit="一時的にこれ以上グループを作成することはできません。"
friend_num_limit="一時的に友達を追加できなくなります。"
operation_error="操作に失敗しました。 後でもう一度やり直してください。"
char_limit="入力したキャラクターが最大長制限を超えています。 最大：number キャラクター。"
first_name_limit="入力した「姓」が最大長の制限を超えています。 最大：number キャラクター。"
last_name_limit="入力した「名」が最大長の制限を超えています。 最大：number キャラクター。"
first_name_required="「姓」を空にすることはできません。"
last_name_required="「名」を空にすることはできません。"
mobile_error="電話番号フォーマットエラー"
mobile_required="電話番号を空にすることはできません。"
country_code_error="国コードエラー"
search_key="有効なユーザーIDまたは携帯電話番号を入力してください。"
is_add_friend="友達追加リクエストが送信されました。"
system_error="システムエラー"
msg_code_error="検証コードフォーマットエラー"
first_name_length="「姓」が長すぎます。"
friends_exist="ユーザーが見つかりません"
last_name_length="「名」が長すぎます。"
content_length="最大200キャラクター"
he_friend_num_limit="あなたや相手の親友の数が上限に達しました。"
sign_error="署名の検証に失敗しました"
is_friends="ユーザーはあなたの友達です。"
sms_friend_tips="JustUsに私を追加してください。"
photo_tips="正常にアップロードされました。 友達を追加して、実際の生活を一緒に共有しましょう"
message_limit="あなたはあまりにも頻繁にテキストメッセージを送信します。 後でもう一度やり直してください。"
copy_friend_tips="JustUsに私を追加してください。"
no_add_friend_self="自分を友達として追加することはできません。"
justus_slogan="一緒に実生活を記録しよう！"
justus_helper="JustUs　ガイド"
bind_mobile_error="電話番号は別のアカウントにバインドされています。"
bound_mobile="バインドに失敗しました。 後でもう一度やり直してください。"
not_add_self_friend="あなた自身を友達に追加することはできません。"
address_book_tips="連絡先を同期して、すでにJustUsにいる友達を見つけます。 あなたの連絡先データはあなたの経験を改善し、あなたや他の人が友達を見つけることができるようにJustUsに送信されます。"
follow_user="あなたをフォローしました！"
notification_friends=":nameはあなたの「JustUs」の友達になりました！写真を送ってみてください！"
notification_like=":nameはあなたが好きでした！"
notification_comment=":nameがあなたにコメントしました、チェックしてください！"
notification_friend_apply=":nameはあなたに友達リクエストを送信しました。"
notification_friend_send_picture=":nameは新しい写真を投稿しました。"
notification_user_register="是非、写真を撮りましょう！ 友達と一緒に実際の生活を記録しましょう！"
notification_friend_register="：nameは JustUs にもあります。 追加？"
notification_memory=":name、あなたは新しい記憶を持っています。"
notification_wait_add_friend=":name、あなたの友達が待っています！"
notification_touch=":nameはあなたの写真をタップしました💓"
notification_follow_user=":nameあなたをフォローしました！"
photo_copy_1="（JustUs）にあなたを追加しました。このアプリをダウンロードして、友達リクエストを許可してください。私のID："
photo_tips_1="正常にアップロードされました。 友達を追加して、実際の生活を一緒に共有しましょう"
photo_end_1="これ以上の友達の瞬間はありません。 写真を撮るか、友達を追加します。"
photo_copy_2="JustUsに私を追加してください。私のID："
photo_tips_2="正常にアップロードされました。 友達を追加して、実際の生活を一緒に共有しましょう"
photo_end_2="これ以上の友達の瞬間はありません。 写真を撮るか、友達を追加します。"
photo_copy_3="JustUsに私を追加して、ホーム画面で写真を共有できるようにします。私のID："
photo_tips_3="彼らのホームスクリーンに送られました！友達を追加して、ホーム画面で実際の生活を共有しましょう。"
photo_end_3="これ以上の写真はありません。友達を追加して、ホーム画面で実際の生活を共有しましょう。"
photo_copy_4="JustUsに私を追加してください。あなたのホーム画面に送信する写真があります。私のID："
photo_tips_4="彼らのホームスクリーンに送られました！友達を追加して、ホーム画面で実際の生活を共有しましょう。"
photo_end_4="これ以上の写真はありません。友達を追加して、ホーム画面で実際の生活を共有しましょう。"
photo_copy_5="新しいウィジェットソーシャルネットワークであるJustUsに私を追加してください！私のID："
photo_tips_5="彼らのホームスクリーンに送られました！友達を追加して、ホーム画面で実際の生活を共有しましょう。"
photo_end_5="これ以上の写真はありません。ホーム画面で実際の生活を共有するために、より多くの友達を招待します。"
photo_copy_6="JustUs-Widget Social Networkに私を追加してください。あなた以外はすべて準備ができています！"
photo_tips_6="彼らのホームスクリーンに送られました！より多くの友達を招待して、あなたの実際の生活を彼らと共有してください。"
photo_end_6="これ以上の写真はありません。友達を追加して、実際の生活を共有しましょう。"
photo_copy_7="JustUsに私を追加してください、すべてがあなたを凌駕する準備ができています！私のID："
photo_tips_7="彼らのホームスクリーンに送られました！より多くの友達を招待して、あなたの実際の生活を彼らと共有してください。"
photo_end_7="これ以上の写真はありません。友達を追加して、実際の生活を共有しましょう。"
photo_copy_8="JustUs-Widget Social Networkに私を追加して、実際の生活を私と共有してください！私のID："
photo_tips_8="彼らのホームスクリーンに送られました！より多くの友達を招待して、あなたの実際の生活を彼らと共有してください。"
photo_end_8="これ以上の写真はありません。友達を追加して、実際の生活を共有しましょう。"
photo_copy_9="実際の写真の挑戦を受け入れ、JustUsに私を追加してください。私のID："
photo_tips_9="彼らのホームスクリーンに送られました！より多くの友達を招待して、あなたの実際の生活を彼らと共有してください。"
photo_end_9="これ以上の写真はありません。友達を追加して、実際の生活を共有しましょう。"
photo_copy_10="私はあなたが私のホームスクリーンにいることを望んでいます、JustUsに私を追加してください。私のID："
photo_tips_10="彼らのホームスクリーンに送られました！友達を追加するともっと楽しくなります。"
photo_end_10="これ以上の写真はありません。友達を追加して、実際の生活を一緒に共有しましょう。"
photo_copy_11="私はあなたが私のホームスクリーンにいることを望んでいます、JustUsに私を追加してください。私のID："
photo_tips_11="彼らのホームスクリーンに送られました！友達を追加して、写真をホーム画面に送信します。"
photo_end_11="友達の写真が足りなくなったようです！友達を追加して、実際の生活を一緒に記録します。"
photo_copy_12="私のホームスクリーンの友達になって、JustUsに私を追加してください。私のID："
photo_tips_12="彼らのホームスクリーンに送られました！より多くの友達をホームスクリーンに招待して、楽しい写真を送ってください！"
photo_end_12="友達の写真が足りなくなったようです！より多くの友達をホームスクリーンに招待して、楽しい写真を送ってください。"
photo_copy_13="私のホームスクリーンの友達になって、JustUsに私を追加してください。私のID："
photo_tips_13="彼らのホームスクリーンに送られました！ホームスクリーンの友達をもっと追加するともっと楽しいでしょう。"
photo_end_13="もっと友達が必要なようです！より多くの友達をホームスクリーンに招待して、楽しい写真を送ってください。"
your_self_visible="私にしか見えない"
update_new_version="新しいデュエット機能、ぜひアップグレードして体験してください！"
