param_error="Kesalahan parameter"
component_num_limit="Untuk sementara Anda tidak dapat membuat grup lagi."
friend_num_limit="Untuk sementara Anda tidak dapat menambahkan lebih banyak teman."
operation_error="Operasi gagal. Silakan coba lagi nanti!"
char_limit="Karakter yang Anda masukkan melebihi batas panjang maksimum. Maksimum :number karakter."
first_name_limit="Nama belakang yang Anda masukkan melebihi batas panjang maksimum. Maksimum :number karakter."
last_name_limit="Nama depan yang Anda masukkan melebihi batas panjang maksimum. Maksimum :number karakter."
first_name_required="Nama belakang wajib diisi."
last_name_required="Nama depan wajib diisi."
mobile_error="Kesalahan format nomor telepon"
mobile_required="Nomor telepon tidak boleh kosong."
country_code_error="Kesalahan kode negara"
search_key="Silakan masukkan ID pengguna atau nomor ponsel yang valid."
is_add_friend="Tambah permintaan pertemanan telah terkirim."
system_error="Sistem bermasalah"
msg_code_error="Kesalahan format kode verifikasi"
first_name_length="Nama belakang terlalu panjang."
friends_exist="Pengguna tidak ditemukan"
last_name_length="Nama depan terlalu panjang."
content_length="Maksimal 200 karakter"
he_friend_num_limit="Jumlah teman Anda atau pengguna telah mencapai batas."
sign_error="Verifikasi tanda tangan gagal"
is_friends="Pengguna telah menjadi teman Anda."
sms_friend_tips="Tambahkan saya di JustUs."
photo_tips="Berhasil diunggah! Tambahkan lebih banyak teman untuk berbagi kehidupan nyata bersama"
message_limit="Anda terlalu sering mengirim pesan teks. Silakan coba lagi nanti."
copy_friend_tips="Tambahkan saya di JustUs."
no_add_friend_self="Anda tidak dapat menambahkan diri Anda sebagai teman."
justus_slogan="Mari kita merekam kehidupan nyata bersama-sama!"
justus_helper="Panduan JustUs"
bind_mobile_error="Nomor telepon telah terikat ke akun lain."
bound_mobile="Pengikatan gagal. Silakan coba lagi nanti."
not_add_self_friend="Anda tidak dapat menambahkan diri Anda sebagai teman."
address_book_tips="Sinkronkan kontak Anda untuk menemukan teman yang sudah ada di JustUs. Data kontak Anda akan dikirim ke JustUs untuk meningkatkan pengalaman Anda dan memungkinkan Anda dan orang lain untuk menemukan teman."
follow_user="mengikutimu!"
notification_friends=":name telah menjadi teman \"Hanya Kami\" Anda! Coba kirimi mereka foto!"
notification_like=":name hanya menyukaimu!"
notification_comment=":name baru saja mengomentari Anda, lihatlah!"
notification_friend_apply=":name mengirimi Anda permintaan pertemanan."
notification_friend_send_picture=":name memposting foto baru."
notification_user_register="Datang dan ambil foto! Rekam kehidupan nyata dengan teman-teman Anda bersama-sama!"
notification_friend_register=":name juga ada di JustUs. Menambahkan?"
notification_memory=":name, Anda memiliki memori baru."
notification_wait_add_friend=":name, temanmu sedang menunggu!"
notification_touch=":name mengetuk fotomu💓"
notification_follow_user=":name mengikutimu!"
photo_copy_1="Saya telah menambahkan Anda di (JustUs). Unduh aplikasi ini untuk mengizinkan permintaan pertemanan saya.ID saya:"
photo_tips_1="Berhasil diunggah! Tambahkan lebih banyak teman untuk berbagi kehidupan nyata bersama"
photo_end_1="Tidak ada lagi momen teman. Ambil foto atau tambahkan lebih banyak teman."
photo_copy_2="Tambahkan saya di JustUs.ID saya:"
photo_tips_2="Berhasil diunggah! Tambahkan lebih banyak teman untuk berbagi kehidupan nyata bersama"
photo_end_2="Tidak ada lagi momen teman. Ambil foto atau tambahkan lebih banyak teman."
photo_copy_3="Tambahkan saya di JustUs sehingga kami dapat berbagi foto ke layar beranda kami. ID saya:"
photo_tips_3="Dikirim ke homescreens mereka! Tambahkan lebih banyak teman untuk berbagi kehidupan nyata Anda di layar beranda."
photo_end_3="Tidak ada lagi foto. Tambahkan lebih banyak teman untuk berbagi kehidupan nyata Anda di layar beranda."
photo_copy_4="Tambahkan saya di JustUs, saya punya foto untuk dikirim ke layar beranda Anda. ID saya:"
photo_tips_4="Dikirim ke homescreens mereka! Tambahkan lebih banyak teman untuk berbagi kehidupan nyata Anda di layar beranda."
photo_end_4="Tidak ada lagi foto. Tambahkan lebih banyak teman untuk berbagi kehidupan nyata Anda di layar beranda."
photo_copy_5="Tambahkan saya di JustUs, jejaring sosial widget baru! ID saya:"
photo_tips_5="Dikirim ke homescreens mereka! Tambahkan lebih banyak teman untuk berbagi kehidupan nyata Anda di layar beranda."
photo_end_5="Tidak ada lagi foto. Undang lebih banyak teman untuk berbagi kehidupan nyata Anda di layar beranda."
photo_copy_6="Tambahkan saya di JustUs - Widget Jejaring Sosial, semua sudah siap kecuali Anda!"
photo_tips_6="Dikirim ke homescreens mereka! Undang lebih banyak teman untuk berbagi kehidupan nyata Anda dengan mereka."
photo_end_6="Tidak ada lagi foto. Tambahkan lebih banyak teman untuk berbagi kehidupan nyata Anda dengan mereka."
photo_copy_7="Tambahkan saya di JustUs, semuanya sudah siap kecuali Anda! ID saya:"
photo_tips_7="Dikirim ke homescreens mereka! Undang lebih banyak teman untuk berbagi kehidupan nyata Anda dengan mereka."
photo_end_7="Tidak ada lagi foto. Tambahkan lebih banyak teman untuk berbagi kehidupan nyata Anda dengan mereka."
photo_copy_8="Tambahkan saya di JustUs - Jaringan Sosial Widget, bagikan kehidupan nyata dengan saya! ID saya:"
photo_tips_8="Dikirim ke homescreens mereka! Undang lebih banyak teman untuk berbagi kehidupan nyata Anda dengan mereka."
photo_end_8="Tidak ada lagi foto. Tambahkan lebih banyak teman untuk berbagi kehidupan nyata Anda dengan mereka."
photo_copy_9="Terima tantangan foto kehidupan nyata, Tambahkan saya di JustUs. ID saya:"
photo_tips_9="Dikirim ke homescreens mereka! Undang lebih banyak teman untuk berbagi kehidupan nyata Anda dengan mereka."
photo_end_9="Tidak ada lagi foto. Tambahkan lebih banyak teman untuk berbagi kehidupan nyata Anda dengan mereka."
photo_copy_10="Saya ingin Anda berada di layar beranda saya, tambahkan saya di JustUs. ID saya:"
photo_tips_10="Dikirim ke homescreens mereka! Akan lebih menyenangkan jika Anda menambahkan lebih banyak teman."
photo_end_10="Tidak ada lagi foto. Tambahkan lebih banyak teman untuk berbagi kehidupan nyata Anda bersama."
photo_copy_11="Saya ingin Anda berada di layar beranda saya, tambahkan saya di JustUs. ID saya:"
photo_tips_11="Dikirim ke homescreens mereka! Tambahkan lebih banyak teman untuk mengirim foto Anda ke layar beranda mereka."
photo_end_11="Sepertinya Anda sudah kehabisan foto teman! Tambahkan lebih banyak teman untuk merekam kehidupan nyata Anda bersama."
photo_copy_12="Jadilah teman homescreen saya, tambahkan saya di JustUs. ID saya:"
photo_tips_12="Dikirim ke homescreens mereka! Undang lebih banyak teman ke layar beranda Anda dan kirimkan foto-foto menyenangkan kepada mereka!"
photo_end_12="Sepertinya Anda sudah kehabisan foto teman! Undang lebih banyak teman ke layar beranda Anda dan kirimkan foto-foto menyenangkan kepada mereka."
photo_copy_13="Jadilah teman homescreen saya, tambahkan saya di JustUs. ID saya:"
photo_tips_13="Dikirim ke homescreens mereka! Akan lebih menyenangkan jika Anda menambahkan lebih banyak teman homescreen."
photo_end_13="Sepertinya Anda membutuhkan lebih banyak teman! Undang lebih banyak teman ke layar beranda Anda dan kirimkan foto-foto menyenangkan kepada mereka."
your_self_visible="Hanya terlihat oleh saya"
update_new_version="Fungsi duet baru, silakan datang untuk meningkatkan dan mengalaminya!"
