param_error="Ошибка параметра"
component_num_limit="Вы временно не можете создавать дополнительные группы."
friend_num_limit="Вы временно не можете добавлять друзей."
operation_error="Операция не удалась. Пожалуйста, попробуйте позже!"
char_limit="Введенные символы превышают максимально допустимую длину. Максимум :number символов."
first_name_limit="Введенная вами «Фамилия» превышает максимально допустимую длину. Максимум :number символов."
last_name_limit="Введенное вами имя превышает максимальную длину. Максимум :number символов."
first_name_required="Поле «Фамилия» не может быть пустым."
last_name_required="Поле «Имя» не может быть пустым."
mobile_error="Ошибка формата номера телефона"
mobile_required="Номер телефона не может быть пустым."
country_code_error="Ошибка кода страны"
search_key="Введите действительный идентификатор пользователя или номер мобильного телефона."
is_add_friend="Запрос на добавление в друзья отправлен."
system_error="Системная ошибка"
msg_code_error="Ошибка формата проверочного кода"
first_name_length="Фамилия слишком длинная."
friends_exist="Пользователь не найден"
last_name_length="Имя слишком длинное."
content_length="Максимум 200 символов"
he_friend_num_limit="Количество ваших друзей или друзей пользователя достигло предела."
sign_error="Ошибка проверки подписи"
is_friends="Пользователь был вашим другом."
sms_friend_tips="Добавьте меня в gin-default."
photo_tips="Загружено успешно! Добавьте больше друзей, чтобы поделиться реальной жизнью вместе"
message_limit="Вы слишком часто отправляете текстовые сообщения. Пожалуйста, попробуйте позже."
copy_friend_tips="Добавьте меня в gin-default."
no_add_friend_self="Вы не можете добавить себя в друзья."
gin-default_slogan="Давайте записывать настоящую жизнь вместе!"
gin-default_helper="Руководство gin-default"
bind_mobile_error="Номер телефона привязан к другому аккаунту."
bound_mobile="Привязка не удалась. Пожалуйста, повторите попытку позже."
not_add_self_friend="Вы не можете добавить себя в друзья."
address_book_tips="Синхронизируйте свои контакты, чтобы найти друзей, уже использующих gin-default. Данные ваших контактов будут отправлены в gin-default, чтобы улучшить ваш опыт и позволить вам и другим найти друзей."
follow_user="проследовал за тобой!"
notification_friends=":name стал вашим другом \"Только мы\"! Попробуйте отправить им фотографии!"
notification_like=":name ты просто понравился!"
notification_comment=":name только что прокомментировал вас, посмотрите!"
notification_friend_apply=":name отправил вам запрос на добавление в друзья."
notification_friend_send_picture=":name опубликовал новое фото."
notification_user_register="Приходите и сделайте фото! Записывайте реальную жизнь с друзьями вместе!"
notification_friend_register=":name также есть на gin-default. Добавлять?"
notification_memory=":name, у тебя новое воспоминание."
notification_wait_add_friend=":name, твои друзья ждут!"
notification_touch=":name коснулся твоего фото💓"
notification_follow_user=":name проследовал за тобой!"
photo_copy_1="Я добавил вас в (gin-default). Загрузите это приложение, чтобы разрешить мой запрос на добавление в друзья.Мой ID:"
photo_tips_1="Загружено успешно! Добавьте больше друзей, чтобы поделиться реальной жизнью вместе"
photo_end_1="Нет больше моментов друзей. Сделайте снимок или добавьте больше друзей."
photo_copy_2="Добавьте меня в gin-default.Мой ID:"
photo_tips_2="Загружено успешно! Добавьте больше друзей, чтобы поделиться реальной жизнью вместе"
photo_end_2="Нет больше моментов друзей. Сделайте снимок или добавьте больше друзей."
photo_copy_3="Добавьте меня в gin-default, чтобы мы могли делиться фотографиями на главном экране. Мой ID:"
photo_tips_3="Отправлено на их домашние экраны! Добавьте больше друзей, чтобы поделиться своей реальной жизнью на своих домашних экранах."
photo_end_3="Нет больше фотографий. Добавьте больше друзей, чтобы поделиться своей реальной жизнью на своих домашних экранах."
photo_copy_4="Добавьте меня на gin-default, у меня есть фотографии для отправки на ваш рабочий стол. Мой ID:"
photo_tips_4="Отправлено на их домашние экраны! Добавьте больше друзей, чтобы поделиться своей реальной жизнью на своих домашних экранах."
photo_end_4="Нет больше фотографий. Добавьте больше друзей, чтобы поделиться своей реальной жизнью на своих домашних экранах."
photo_copy_5="Добавьте меня в gin-default, новую социальную сеть с виджетами! Мой ID:"
photo_tips_5="Отправлено на их домашние экраны! Добавьте больше друзей, чтобы поделиться своей реальной жизнью на своих домашних экранах."
photo_end_5="Нет больше фотографий. Пригласите больше друзей, чтобы поделиться своей реальной жизнью на своих домашних экранах."
photo_copy_6="Добавьте меня в gin-default - Widget Social Network, все готово, кроме вас!"
photo_tips_6="Отправлено на их домашние экраны! Пригласите больше друзей, чтобы поделиться с ними своей реальной жизнью."
photo_end_6="Нет больше фотографий. Добавьте больше друзей, чтобы поделиться с ними своей реальной жизнью."
photo_copy_7="Добавьте меня в gin-default, все готово, кроме вас! Мой ID:"
photo_tips_7="Отправлено на их домашние экраны! Пригласите больше друзей, чтобы поделиться с ними своей реальной жизнью."
photo_end_7="Нет больше фотографий. Добавьте больше друзей, чтобы поделиться с ними своей реальной жизнью."
photo_copy_8="Добавьте меня в gin-default - Widget Social Network, поделитесь со мной реальной жизнью! Мой ID:"
photo_tips_8="Отправлено на их домашние экраны! Пригласите больше друзей, чтобы поделиться с ними своей реальной жизнью."
photo_end_8="Нет больше фотографий. Добавьте больше друзей, чтобы поделиться с ними своей реальной жизнью."
photo_copy_9="Прими участие в конкурсе фото из реальной жизни, добавь меня в gin-default. Мой ID:"
photo_tips_9="Отправлено на их домашние экраны! Пригласите больше друзей, чтобы поделиться с ними своей реальной жизнью."
photo_end_9="Нет больше фотографий. Добавьте больше друзей, чтобы поделиться с ними своей реальной жизнью."
photo_copy_10="Я хочу, чтобы вы были на моем домашнем экране, добавьте меня в gin-default. Мой ID:"
photo_tips_10="Отправлено на их домашние экраны! Было бы веселее, если бы вы добавили больше друзей."
photo_end_10="Нет больше фотографий. Добавьте больше друзей, чтобы поделиться своей реальной жизнью вместе."
photo_copy_11="Я хочу, чтобы вы были на моем домашнем экране, добавьте меня в gin-default. Мой ID:"
photo_tips_11="Отправлено на их домашние экраны! Добавьте больше друзей, чтобы отправить свои фотографии на их домашние экраны."
photo_end_11="Кажется, у вас закончились фотографии друзей! Добавьте больше друзей, чтобы записать свою настоящую совместную жизнь."
photo_copy_12="Будь моим другом на рабочем столе, добавь меня в gin-default. Мой ID:"
photo_tips_12="Отправлено на их домашние экраны! Пригласите больше друзей на домашний экран и отправьте им забавные фотографии!"
photo_end_12="Кажется, у вас закончились фотографии друзей! Пригласите больше друзей на домашний экран и отправьте им забавные фотографии."
photo_copy_13="Будь моим другом на рабочем столе, добавь меня в gin-default. Мой ID:"
photo_tips_13="Отправлено на их домашние экраны! Было бы веселее, если бы вы добавили больше друзей на домашнем экране."
photo_end_13="Кажется, тебе нужно больше друзей! Пригласите больше друзей на домашний экран и отправьте им забавные фотографии."
your_self_visible="Видно только мне"
update_new_version="Новая функция дуэта, пожалуйста, обновите и испытайте ее!"
