param_error="Erreur de paramètre"
component_num_limit="Vous ne pouvez temporairement pas créer d'autres groupes."
friend_num_limit="Vous ne pouvez temporairement pas ajouter d'amis."
operation_error="L'opération a échoué. Veuillez réessayer plus tard!"
char_limit="Les caractères que vous avez saisis dépassent la limite de longueur maximale. Le maximum :number caractères."
first_name_limit="Le \"Nom de famille\" que vous avez entré dépasse la limite de longueur maximale. Le maximum :number caractères."
last_name_limit="Le \"Prénom\" que vous avez entré dépasse la limite de longueur maximale. Le maximum :number caractères."
first_name_required="Le \"Nom de famille\" ne peut pas être vide."
last_name_required="Le \"Prénom\" ne peut pas être vide."
mobile_error="Erreur de format de numéro de téléphone"
mobile_required="Le numéro de téléphone ne peut pas être vide."
country_code_error="Erreur de code de pays"
search_key="Veuillez saisir un ID utilisateur ou un numéro de mobile valide."
is_add_friend="La demande d'ajout d'ami a été envoyée."
system_error="Erreur système"
msg_code_error="Erreur de format du code de vérification"
first_name_length="Le \"Nom de famille\" est trop long."
friends_exist="Utilisateur non trouvé"
last_name_length="Le \"Prénom\" est trop long."
content_length="Les 200 caractères maximum"
he_friend_num_limit="Votre nombre d'amis ou celui de l'utilisateur a atteint la limite."
sign_error="Vérification de signature a échoué"
is_friends="L'utilisateur a été votre ami."
sms_friend_tips="Ajoutez-moi sur JustUs."
photo_tips="Téléchargé avec succès ! Ajoutez plus d'amis pour partager la vraie vie ensemble"
message_limit="Vous envoyez trop souvent des SMS. Veuillez réessayer plus tard."
copy_friend_tips="Ajoutez-moi sur JustUs."
no_add_friend_self="Vous ne pouvez pas vous ajouter vous-même comme ami."
justus_slogan="Ensemble, enregistrons la vraie vie !"
justus_helper="Guide JustUs"
bind_mobile_error="Le numéro de téléphone a été lié à un autre compte."
bound_mobile="La liaison a échoué. Veuillez réessayer plus tard."
not_add_self_friend="Vous ne pouvez pas vous ajouter en tant qu'ami."
address_book_tips="Synchronisez vos contacts pour trouver des amis déjà sur JustUs. Vos données de contacts seront envoyées à JustUs pour améliorer votre expérience et vous permettre, ainsi qu'aux autres, de trouver des amis."
follow_user="je t'ai suivi!"
notification_friends=":name est devenu votre ami \"JustUs\" ! Essayez de leur envoyer des photos !"
notification_like=":name vient de vous aimer!"
notification_comment=":name vient de commenter sur vous, regardez-le!"
notification_friend_apply=":name vous a envoyé une demande d'ami."
notification_friend_send_picture=":name a publié une nouvelle photo."
notification_user_register="Venez prendre une photo! Enregistrez la vraie vie avec vos amis ensemble!"
notification_friend_register=":name est aussi sur JustUs. Ajouter?"
notification_memory=":name, vous avez un nouveau souvenir."
notification_wait_add_friend=":name, vos amis vous attendent !"
notification_touch=":name a tapé sur votre photo💓"
notification_follow_user=":name je t'ai suivi!"
photo_copy_1="Je vous ai ajouté sur (JustUs). Téléchargez cette application pour autoriser ma demande d'ami. Ma pièce d'identité:"
photo_tips_1="Téléchargé avec succès ! Ajoutez plus d'amis pour partager la vraie vie ensemble"
photo_end_1="Fini les moments entre amis. Prenez une photo ou ajoutez plus d'amis."
photo_copy_2="Ajoutez-moi sur JustUs. Ma pièce d'identité:"
photo_tips_2="Téléchargé avec succès ! Ajoutez plus d'amis pour partager la vraie vie ensemble"
photo_end_2="Fini les moments entre amis. Prenez une photo ou ajoutez plus d'amis."
photo_copy_3="Ajoutez-moi sur JustUs afin que nous puissions partager des photos sur notre écran d'accueil. Ma pièce d'identité:"
photo_tips_3="Envoyé sur leurs écrans d'accueil ! Ajoutez plus d'amis pour partager votre vie réelle sur vos écrans d'accueil."
photo_end_3="Plus de photos. Ajoutez plus d'amis pour partager votre vie réelle sur vos écrans d'accueil."
photo_copy_4="Ajoutez-moi sur JustUs, j'ai des photos à envoyer sur votre écran d'accueil. Ma pièce d'identité:"
photo_tips_4="Envoyé sur leurs écrans d'accueil ! Ajoutez plus d'amis pour partager votre vie réelle sur vos écrans d'accueil."
photo_end_4="Plus de photos. Ajoutez plus d'amis pour partager votre vie réelle sur vos écrans d'accueil."
photo_copy_5="Ajoutez-moi sur JustUs, le nouveau réseau social de widgets ! Ma pièce d'identité:"
photo_tips_5="Envoyé sur leurs écrans d'accueil ! Ajoutez plus d'amis pour partager votre vie réelle sur vos écrans d'accueil."
photo_end_5="Plus de photos. Invitez plus d'amis à partager votre vie réelle sur vos écrans d'accueil."
photo_copy_6="Ajoutez-moi sur JustUs - Widget Social Network, tout est prêt sauf vous !"
photo_tips_6="Envoyé sur leurs écrans d'accueil ! Invitez plus d'amis à partager votre vraie vie avec eux."
photo_end_6="Plus de photos. Ajoutez plus d'amis pour partager votre vraie vie avec eux."
photo_copy_7="Ajoutez-moi sur JustUs, tout est prêt sauf vous ! Ma pièce d'identité:"
photo_tips_7="Envoyé sur leurs écrans d'accueil ! Invitez plus d'amis à partager votre vraie vie avec eux."
photo_end_7="Plus de photos. Ajoutez plus d'amis pour partager votre vraie vie avec eux."
photo_copy_8="Ajoutez-moi sur JustUs - Widget Social Network, partagez la vraie vie avec moi ! Ma pièce d'identité:"
photo_tips_8="Envoyé sur leurs écrans d'accueil ! Invitez plus d'amis à partager votre vraie vie avec eux."
photo_end_8="Plus de photos. Ajoutez plus d'amis pour partager votre vraie vie avec eux."
photo_copy_9="Acceptez le défi photo de la vie réelle, ajoutez-moi sur JustUs. Ma pièce d'identité:"
photo_tips_9="Envoyé sur leurs écrans d'accueil ! Invitez plus d'amis à partager votre vraie vie avec eux."
photo_end_9="Plus de photos. Ajoutez plus d'amis pour partager votre vraie vie avec eux."
photo_copy_10="Je veux que vous soyez sur mon écran d'accueil, ajoutez-moi sur JustUs. Ma pièce d'identité:"
photo_tips_10="Envoyé sur leurs écrans d'accueil ! Ce serait plus amusant si vous ajoutiez plus d'amis."
photo_end_10="Plus de photos. Ajoutez plus d'amis pour partager vos vraies vies ensemble."
photo_copy_11="Je veux que vous soyez sur mon écran d'accueil, ajoutez-moi sur JustUs. Ma pièce d'identité:"
photo_tips_11="Envoyé sur leurs écrans d'accueil ! Ajoutez plus d'amis pour envoyer vos photos sur leurs écrans d'accueil."
photo_end_11="Il semble que vous n'ayez plus de photos d'amis ! Ajoutez plus d'amis pour enregistrer vos vraies vies ensemble."
photo_copy_12="Soyez mon ami de l'écran d'accueil, ajoutez-moi sur JustUs. Ma pièce d'identité:"
photo_tips_12="Envoyé sur leurs écrans d'accueil ! Invitez plus d'amis sur votre écran d'accueil et envoyez-leur des photos amusantes !"
photo_end_12="Il semble que vous n'ayez plus de photos d'amis ! Invitez plus d'amis sur votre écran d'accueil et envoyez-leur des photos amusantes."
photo_copy_13="Soyez mon ami de l'écran d'accueil, ajoutez-moi sur JustUs. Ma pièce d'identité:"
photo_tips_13="Envoyé sur leurs écrans d'accueil ! Ce serait plus amusant si vous ajoutiez plus d'amis à l'écran d'accueil."
photo_end_13="Il semble que vous ayez besoin de plus d'amis ! Invitez plus d'amis sur votre écran d'accueil et envoyez-leur des photos amusantes."
your_self_visible="Uniquement visible pour moi"
update_new_version="Nouvelle fonction duo, venez la mettre à niveau et en faire l'expérience !"
