param_error="Помилка параметра"
component_num_limit="Ви тимчасово не можете створити більше груп."
friend_num_limit="Ви тимчасово не можете додати більше друзів."
operation_error="Операція не вдалася. Будь-ласка спробуйте пізніше!"
char_limit="Введені символи перевищують максимальну довжину. Максимум :number символів."
first_name_limit="Прізвище, яке ви ввели, перевищує максимальну довжину. Максимальна кількість :number символів."
last_name_limit="Ім'я, яке ви ввели, перевищує максимальну довжину. Максимальна кількість :number символів."
first_name_required="Поле \"Прізвище\" не може бути порожнім."
last_name_required="Поле \"Ім'я\" не може бути порожнім."
mobile_error="Помилка формату номера телефону"
mobile_required="Номер телефону не може бути порожнім."
country_code_error="Помилка коду країни"
search_key="Будь ласка, введіть дійсний ідентифікатор користувача або номер мобільного телефону."
is_add_friend="Запит на додавання друзів надіслано."
system_error="Системна помилка"
msg_code_error="Помилка форматування коду підтвердження"
first_name_length="Прізвище занадто довге."
friends_exist="Користувач не знайдений"
last_name_length="Ім'я задовге."
content_length="Максимум 200 символів"
he_friend_num_limit="Кількість ваших друзів або друзів користувача досягла ліміту."
sign_error="Не вдалося перевірити підпис"
is_friends="Користувач був вашим другом."
sms_friend_tips="Додайте мене на gin-default."
photo_tips="Завантажено успішно! Додайте більше друзів, щоб ділитися реальним життям разом"
message_limit="Ви надто часто надсилаєте текстові повідомлення. Будь-ласка спробуйте пізніше."
copy_friend_tips="Додайте мене на gin-default."
no_add_friend_self="Ви не можете додати себе в друзі."
gin-default_slogan="Записуємо реальне життя разом!"
gin-default_helper="Довідник gin-default"
bind_mobile_error="Номер телефону прив’язано до іншого облікового запису."
bound_mobile="Помилка зв’язування. Будь-ласка спробуйте пізніше."
not_add_self_friend="Ви не можете додати себе в друзі."
address_book_tips="Синхронізуйте свої контакти, щоб знайти друзів, які вже є на gin-default. Дані ваших контактів будуть надіслані в gin-default, щоб покращити ваш досвід і дозволити вам та іншим знайти друзів."
follow_user="стежив за вами!"
notification_friends=":name став вашим другом \"Тільки ми\"! Спробуйте надіслати їм фотографії!"
notification_like=":name ти просто сподобався!"
notification_comment=":name щойно прокоментував вас. Перегляньте це!"
notification_friend_apply=":name надіслав вам запит на дружбу."
notification_friend_send_picture=":name опублікував нове фото."
notification_user_register="Приходь і сфотографуйся! Записуйте реальне життя з друзями разом!"
notification_friend_register=":name також є на gin-default. Додати?"
notification_memory=":name, у вас новий спогад."
notification_wait_add_friend=":name, твої друзі чекають!"
notification_touch=":name торкнувся твоєї фотографії💓"
notification_follow_user=":name стежив за вами!"
photo_copy_1="Я додав вас у (gin-default). Завантажте цю програму, щоб дозволити моєму запиту в друзі.Мій ідентифікатор:"
photo_tips_1="Завантажено успішно! Додайте більше друзів, щоб ділитися реальним життям разом"
photo_end_1="Більше жодних моментів друзів. Зробіть фото або додайте більше друзів."
photo_copy_2="Додайте мене на gin-default.Мій ідентифікатор:"
photo_tips_2="Завантажено успішно! Додайте більше друзів, щоб ділитися реальним життям разом"
photo_end_2="Більше жодних моментів друзів. Зробіть фото або додайте більше друзів."
photo_copy_3="Додайте мене в gin-default, щоб ми могли ділитися фотографіями на наш головний екран. Мій ідентифікатор:"
photo_tips_3="Надіслано на їхній головний екран! Додайте більше друзів, щоб поділитися своїм реальним життям на своїх домашніх екранах."
photo_end_3="Більше немає фотографій. Додайте більше друзів, щоб поділитися своїм реальним життям на своїх домашніх екранах."
photo_copy_4="Додайте мене на gin-default, у мене є фотографії, які можна надіслати на ваш головний екран. Мій ідентифікатор:"
photo_tips_4="Надіслано на їхній головний екран! Додайте більше друзів, щоб поділитися своїм реальним життям на своїх домашніх екранах."
photo_end_4="Більше немає фотографій. Додайте більше друзів, щоб поділитися своїм реальним життям на своїх домашніх екранах."
photo_copy_5="Додайте мене в gin-default, нову соціальну мережу віджетів! Мій ідентифікатор:"
photo_tips_5="Надіслано на їхній головний екран! Додайте більше друзів, щоб поділитися своїм реальним життям на своїх домашніх екранах."
photo_end_5="Більше немає фотографій. Запросіть більше друзів поділитися своїм реальним життям на ваших домашніх екранах."
photo_copy_6="Додайте мене в gin-default - Widget Social Network, все готово, крім вас!"
photo_tips_6="Надіслано на їхній головний екран! Запросіть більше друзів, щоб поділитися з ними своїм справжнім життям."
photo_end_6="Більше немає фотографій. Додайте більше друзів, щоб поділитися з ними своїм реальним життям."
photo_copy_7="Додайте мене на gin-default, все готово, крім вас! Мій ідентифікатор:"
photo_tips_7="Надіслано на їхній головний екран! Запросіть більше друзів, щоб поділитися з ними своїм справжнім життям."
photo_end_7="Більше немає фотографій. Додайте більше друзів, щоб поділитися з ними своїм реальним життям."
photo_copy_8="Додайте мене в gin-default - Widget Social Network, поділіться зі мною реальним життям! Мій ідентифікатор:"
photo_tips_8="Надіслано на їхній головний екран! Запросіть більше друзів, щоб поділитися з ними своїм справжнім життям."
photo_end_8="Більше немає фотографій. Додайте більше друзів, щоб поділитися з ними своїм реальним життям."
photo_copy_9="Прийміть справжній фотовиклик, додайте мене на gin-default. Мій ідентифікатор:"
photo_tips_9="Надіслано на їхній головний екран! Запросіть більше друзів, щоб поділитися з ними своїм справжнім життям."
photo_end_9="Більше немає фотографій. Додайте більше друзів, щоб поділитися з ними своїм реальним життям."
photo_copy_10="Я хочу, щоб ви були на моєму головному екрані, додайте мене на gin-default. Мій ідентифікатор:"
photo_tips_10="Надіслано на їхній головний екран! Було б веселіше, якби ви додали більше друзів."
photo_end_10="Більше немає фотографій. Додайте більше друзів, щоб ділитися своїми реальними життями разом."
photo_copy_11="Я хочу, щоб ви були на моєму головному екрані, додайте мене на gin-default. Мій ідентифікатор:"
photo_tips_11="Надіслано на їхній головний екран! Додайте більше друзів, щоб надсилати свої фотографії на їхній головний екран."
photo_end_11="Здається, у вас закінчилися фотографії друзів! Додайте більше друзів, щоб записати ваше реальне життя разом."
photo_copy_12="Будьте моїм другом на головному екрані, додайте мене в gin-default. Мій ідентифікатор:"
photo_tips_12="Надіслано на їхній головний екран! Запросіть більше друзів на свій головний екран і відправте їм веселі фотографії!"
photo_end_12="Здається, у вас закінчилися фотографії друзів! Запросіть більше друзів на свій головний екран і відправте їм веселі фотографії."
photo_copy_13="Будьте моїм другом на головному екрані, додайте мене в gin-default. Мій ідентифікатор:"
photo_tips_13="Надіслано на їхній головний екран! Було б веселіше, якби ви додали більше друзів на головному екрані."
photo_end_13="Здається, тобі потрібно більше друзів! Запросіть більше друзів на свій головний екран і відправте їм веселі фотографії."
your_self_visible="Видно тільки мені"
update_new_version="Нова функція дуету, будь ласка, приходьте, щоб оновити та відчути це!"
