param_error="Villa við færibreytur"
component_num_limit="Þú getur ekki stofnað fleiri hópa tímabundið."
friend_num_limit="Þú getur ekki bætt við fleiri vinum í augnablikinu."
operation_error="Aðgerð mistókst. Vinsamlegast reyndu aftur síðar!"
char_limit="Stafirnir sem þú slóst inn fara yfir hámarkslengd. Hámark:number stafir."
first_name_limit="„Eftirnafn“ sem þú slóst inn fer yfir hámarkslengd. Hámark :number stafir."
last_name_limit="„Fyrsta nafnið“ sem þú slóst inn fer yfir hámarkslengd. Hámark :number stafir."
first_name_required="„Eftirnafn“ má ekki vera autt."
last_name_required="„Fyrsta nafnið“ má ekki vera autt."
mobile_error="Villa í sniði símanúmers"
mobile_required="Símanúmerið má ekki vera autt."
country_code_error="Landskóðavilla"
search_key="Vinsamlegast sláðu inn gilt notandaauðkenni eða farsímanúmer."
is_add_friend="Bæta við vinabeiðni hefur verið send."
system_error="Kerfisvilla"
msg_code_error="Villa í sniði staðfestingarkóða"
first_name_length="„Eftirnafn“ er of langt."
friends_exist="Notandi finnst ekki"
last_name_length="„Fyrsta nafnið“ er of langt."
content_length="Hámark 200 stafir"
he_friend_num_limit="Vinafjöldi þinn eða notandans hefur náð hámarkinu."
sign_error="Staðfesting undirskriftar mistókst"
is_friends="Notandinn hefur verið vinur þinn."
sms_friend_tips="Bættu mér við á JustUs."
photo_tips="Hlaðið upp! Bættu við fleiri vinum til að deila raunveruleikanum saman"
message_limit="Þú sendir textaskilaboð of oft. Vinsamlegast reyndu aftur síðar."
copy_friend_tips="Bættu mér við á JustUs."
no_add_friend_self="Þú getur ekki bætt sjálfum þér við sem vini."
justus_slogan="Tökum upp raunveruleikann saman!"
justus_helper="JustUs leiðarvísir"
bind_mobile_error="Símanúmerið hefur verið bundið við annan reikning."
bound_mobile="Binding mistókst. Vinsamlegast reyndu aftur síðar."
not_add_self_friend="Þú getur ekki bætt sjálfum þér við sem vini."
address_book_tips="Samstilltu tengiliðina þína til að finna vini sem þegar eru á JustUs. Tengiliðagögnin þín verða send til JustUs til að bæta upplifun þína og gera þér og öðrum kleift að finna vini."
follow_user="elti þig!"
notification_friends=":name er orðinn „bara við“ vinur þinn! Prófaðu að senda þeim myndir!"
notification_like=":name líkaði bara við þig!"
notification_comment=":name skrifaði bara ummæli við þig, skoðaðu það!"
notification_friend_apply=":name sendi þér vinabeiðni."
notification_friend_send_picture=":name setti inn nýja mynd."
notification_user_register="Komdu og taktu mynd! Taktu upp raunveruleikann með vinum þínum saman!"
notification_friend_register=":name er líka á JustUs. Bæta við?"
notification_memory=":name, þú ert með nýtt minni."
notification_wait_add_friend=":name, vinir þínir bíða!"
notification_touch=":name smellti á myndina þína💓"
notification_follow_user=":name elti þig!"
photo_copy_1="Ég hef bætt þér við á (JustUs). Sæktu þetta forrit til að leyfa vinabeiðni mína.Auðkenni mitt:"
photo_tips_1="Hlaðið upp! Bættu við fleiri vinum til að deila raunveruleikanum saman"
photo_end_1="Ekki lengur vinastundir. Taktu mynd eða bættu við fleiri vinum."
photo_copy_2="Bættu mér við á JustUs. Auðkenni mitt:"
photo_tips_2="Hlaðið upp! Bættu við fleiri vinum til að deila raunveruleikanum saman"
photo_end_2="Ekki lengur vinastundir. Taktu mynd eða bættu við fleiri vinum."
photo_copy_3="Bættu mér við á JustUs svo við getum deilt myndum á heimaskjáinn okkar. Auðkenni mitt:"
photo_tips_3="Sent á heimaskjáinn þeirra! Bættu við fleiri vinum til að deila raunverulegu lífi þínu á heimaskjánum þínum."
photo_end_3="Engar fleiri myndir. Bættu við fleiri vinum til að deila raunverulegu lífi þínu á heimaskjánum þínum."
photo_copy_4="Bættu mér við á JustUs, ég á myndir til að senda á heimaskjáinn þinn. Auðkenni mitt:"
photo_tips_4="Sent á heimaskjáinn þeirra! Bættu við fleiri vinum til að deila raunverulegu lífi þínu á heimaskjánum þínum."
photo_end_4="Engar fleiri myndir. Bættu við fleiri vinum til að deila raunverulegu lífi þínu á heimaskjánum þínum."
photo_copy_5="Bættu mér við á JustUs, nýja búnaðarsamfélagsnetinu! Auðkenni mitt:"
photo_tips_5="Sent á heimaskjáinn þeirra! Bættu við fleiri vinum til að deila raunverulegu lífi þínu á heimaskjánum þínum."
photo_end_5="Engar fleiri myndir. Bjóddu fleiri vinum að deila raunverulegu lífi þínu á heimaskjánum þínum."
photo_copy_6="Bættu mér við á JustUs - Widget Social Network, allt er tilbúið nema þú!"
photo_tips_6="Sent á heimaskjáinn þeirra! Bjóddu fleiri vinum til að deila raunverulegu lífi þínu með þeim."
photo_end_6="Engar fleiri myndir. Bættu við fleiri vinum til að deila raunverulegu lífi þínu með þeim."
photo_copy_7="Bættu mér við á JustUs, allt er tilbúið nema þú! Auðkenni mitt:"
photo_tips_7="Sent á heimaskjáinn þeirra! Bjóddu fleiri vinum til að deila raunverulegu lífi þínu með þeim."
photo_end_7="Engar fleiri myndir. Bættu við fleiri vinum til að deila raunverulegu lífi þínu með þeim."
photo_copy_8="Bættu mér við á JustUs - Widget Social Network, deildu raunveruleikanum með mér! Auðkenni mitt:"
photo_tips_8="Sent á heimaskjáinn þeirra! Bjóddu fleiri vinum til að deila raunverulegu lífi þínu með þeim."
photo_end_8="Engar fleiri myndir. Bættu við fleiri vinum til að deila raunverulegu lífi þínu með þeim."
photo_copy_9="Samþykktu alvöru ljósmyndaáskorunina, bættu mér við á JustUs. Auðkenni mitt:"
photo_tips_9="Sent á heimaskjáinn þeirra! Bjóddu fleiri vinum til að deila raunverulegu lífi þínu með þeim."
photo_end_9="Engar fleiri myndir. Bættu við fleiri vinum til að deila raunverulegu lífi þínu með þeim."
photo_copy_10="Ég vil að þú sért á heimaskjánum mínum, bættu mér við á JustUs. Auðkenni mitt:"
photo_tips_10="Sent á heimaskjáinn þeirra! Það væri skemmtilegra ef þú bætir við fleiri vinum."
photo_end_10="Engar fleiri myndir. Bættu við fleiri vinum til að deila raunverulegu lífi þínu saman."
photo_copy_11="Ég vil að þú sért á heimaskjánum mínum, bættu mér við á JustUs. Auðkenni mitt:"
photo_tips_11="Sent á heimaskjáinn þeirra! Bættu við fleiri vinum til að senda myndirnar þínar á heimaskjái þeirra."
photo_end_11="Svo virðist sem þú hafir klárað myndir vina! Bættu við fleiri vinum til að taka upp raunverulegt líf þitt saman."
photo_copy_12="Vertu vinur minn heimaskjás, bættu mér við á JustUs. Auðkenni mitt:"
photo_tips_12="Sent á heimaskjáinn þeirra! Bjóddu fleiri vinum á heimaskjáinn þinn og sendu þeim skemmtilegar myndir!"
photo_end_12="Svo virðist sem þú hafir klárað myndir vina! Bjóddu fleiri vinum á heimaskjáinn þinn og sendu þeim skemmtilegar myndir."
photo_copy_13="Vertu vinur minn heimaskjás, bættu mér við á JustUs. Auðkenni mitt:"
photo_tips_13="Sent á heimaskjáinn þeirra! Það væri skemmtilegra ef þú bætir við fleiri heimaskjávinum."
photo_end_13="Þú virðist þurfa fleiri vini! Bjóddu fleiri vinum á heimaskjáinn þinn og sendu þeim skemmtilegar myndir."
your_self_visible="Aðeins sýnilegt mér"
update_new_version="Ný dúettaðgerð, vinsamlega komdu til að uppfæra og upplifa það!"
