param_error="ข้อผิดพลาดของพารามิเตอร์"
component_num_limit="คุณไม่สามารถสร้างกลุ่มเพิ่มเติมได้ชั่วคราว"
friend_num_limit="คุณไม่สามารถเพิ่มเพื่อนเพิ่มได้ชั่วคราว"
operation_error="การดำเนินการล้มเหลว. โปรดลองอีกครั้งในภายหลัง!"
char_limit="อักขระที่คุณป้อนเกินขีดจำกัดความยาวสูงสุด สูงสุด :number อักขระ"
first_name_limit="นามสกุล ที่คุณป้อนเกินขีดจำกัดความยาวสูงสุด สูงสุด :number อักขระ"
last_name_limit="ชื่อ ที่คุณป้อนเกินขีดจำกัดความยาวสูงสุด สูงสุด :number อักขระ"
first_name_required="ต้องระบุ \"นามสกุล\""
last_name_required="ต้องระบุ \"ชื่อจริง\""
mobile_error="ข้อผิดพลาดรูปแบบหมายเลขโทรศัพท์"
mobile_required="ต้องระบุหมายเลขโทรศัพท์"
country_code_error="รหัสประเทศผิดพลาด"
search_key="โปรดป้อน ID ผู้ใช้หรือหมายเลขโทรศัพท์มือถือที่ถูกต้อง"
is_add_friend="ส่งคำขอเป็นเพื่อนแล้ว"
system_error="ระบบผิดพลาด"
msg_code_error="ข้อผิดพลาดรูปแบบรหัสยืนยัน"
first_name_length="นามสกุล ยาวเกินไป"
friends_exist="ไม่พบชื่อผู้ใช้"
last_name_length="ชื่อจริง ยาวเกินไป"
content_length="สูงสุด 200 ตัวอักษร"
he_friend_num_limit="เพื่อนของคุณหรือผู้ใช้ถึงขีดจำกัดแล้ว"
sign_error="การตรวจสอบลายเซ็นล้มเหลว"
is_friends="ผู้ใช้รายนี้เป็นเพื่อนของคุณ"
sms_friend_tips="เพิ่มฉันใน JustUs"
photo_tips="อัพโหลดสำเร็จ! เพิ่มเพื่อนเพื่อแบ่งปันชีวิตจริงด้วยกัน"
message_limit="คุณส่งข้อความบ่อยเกินไป โปรดลองอีกครั้งในภายหลัง."
copy_friend_tips="เพิ่มฉันใน JustUs"
no_add_friend_self="คุณไม่สามารถเพิ่มตัวเองเป็นเพื่อนได้"
justus_slogan="มาบันทึกชีวิตจริงด้วยกันเถอะ!"
justus_helper="JustUs แนะนำ"
bind_mobile_error="หมายเลขโทรศัพท์ถูกผูกไว้กับบัญชีอื่น"
bound_mobile="การผูกล้มเหลว กรุณาลองใหม่อีกครั้งในภายหลัง."
not_add_self_friend="คุณไม่สามารถเพิ่มตัวเองเป็นเพื่อนได้"
address_book_tips="ซิงค์ผู้ติดต่อของคุณเพื่อค้นหาเพื่อนที่อยู่ใน JustUs แล้ว ข้อมูลผู้ติดต่อของคุณจะถูกส่งไปยัง JustUs เพื่อปรับปรุงประสบการณ์ของคุณและช่วยให้คุณและคนอื่นๆ สามารถค้นหาเพื่อนได้"
follow_user="ติดตามคุณ!"
notification_friends=":name กลายเป็นเพื่อน \"JustUs\" ของคุณแล้ว! ลองส่งรูปถ่ายให้พวกเขาดูสิ!"
notification_like=":name ชอบคุณ!"
notification_comment=":name เพิ่งแสดงความคิดเห็นกับคุณ ลองดูสิ!"
notification_friend_apply=":name ส่งคำขอเป็นเพื่อนถึงคุณ"
notification_friend_send_picture=":name ได้โพสต์รูปภาพใหม่"
notification_user_register="มาถ่ายรูปกัน! บันทึกชีวิตจริงกับเพื่อน ๆ ของคุณด้วยกัน!"
notification_friend_register=":name อยู่ใน JustUs ด้วย เพิ่ม?"
notification_memory=":name คุณมีความทรงจำใหม่แล้ว"
notification_wait_add_friend=":name เพื่อนของคุณกำลังรออยู่!"
notification_touch=":name เคาะรูปของคุณ💓"
notification_follow_user=":name ติดตามคุณ!"
photo_copy_1="ฉันได้เพิ่มคุณใน (JustUs) ดาวน์โหลดแอปนี้เพื่ออนุญาตคำขอเป็นเพื่อนของฉัน ไอดีของฉัน:"
photo_tips_1="อัพโหลดสำเร็จ! เพิ่มเพื่อนเพื่อแบ่งปันชีวิตจริงด้วยกัน"
photo_end_1="ไม่มีช่วงเวลาของเพื่อนอีกต่อไป ถ่ายรูปหรือเพิ่มเพื่อน"
photo_copy_2="เพิ่มฉันใน JustUs ไอดีของฉัน:"
photo_tips_2="อัพโหลดสำเร็จ! เพิ่มเพื่อนเพื่อแบ่งปันชีวิตจริงด้วยกัน"
photo_end_2="ไม่มีช่วงเวลาของเพื่อนอีกต่อไป ถ่ายรูปหรือเพิ่มเพื่อน"
photo_copy_3="เพิ่มฉันใน JustUs เพื่อให้เราสามารถแชร์รูปภาพไปยังหน้าจอหลักของเรา รหัสของฉัน:"
photo_tips_3="ส่งไปที่หน้าจอหลักแล้ว! เพิ่มเพื่อนเพื่อแบ่งปันชีวิตจริงของคุณบนหน้าจอหลักของคุณ"
photo_end_3="ไม่มีรูปถ่ายอีกต่อไป เพิ่มเพื่อนเพื่อแบ่งปันชีวิตจริงของคุณบนหน้าจอหลักของคุณ"
photo_copy_4="เพิ่มฉันใน JustUs ฉันมีรูปภาพที่จะส่งไปที่หน้าจอหลักของคุณ รหัสของฉัน:"
photo_tips_4="ส่งไปที่หน้าจอหลักแล้ว! เพิ่มเพื่อนเพื่อแบ่งปันชีวิตจริงของคุณบนหน้าจอหลักของคุณ"
photo_end_4="ไม่มีรูปถ่ายอีกต่อไป เพิ่มเพื่อนเพื่อแบ่งปันชีวิตจริงของคุณบนหน้าจอหลักของคุณ"
photo_copy_5="เพิ่มฉันใน JustUs วิดเจ็ตโซเชียลเน็ตเวิร์กใหม่! รหัสของฉัน:"
photo_tips_5="ส่งไปที่หน้าจอหลักแล้ว! เพิ่มเพื่อนเพื่อแบ่งปันชีวิตจริงของคุณบนหน้าจอหลักของคุณ"
photo_end_5="ไม่มีรูปถ่ายอีกต่อไป เชิญเพื่อนมากขึ้นเพื่อแบ่งปันชีวิตจริงของคุณบนหน้าจอหลักของคุณ"
photo_copy_6="เพิ่มฉันใน JustUs - Widget Social Network ทุกอย่างพร้อมแล้ว ยกเว้นคุณ!"
photo_tips_6="ส่งไปที่หน้าจอหลักแล้ว! เชิญเพื่อน ๆ มาแบ่งปันชีวิตจริงของคุณกับพวกเขามากขึ้น"
photo_end_6="ไม่มีรูปถ่ายอีกต่อไป เพิ่มเพื่อนเพื่อแบ่งปันชีวิตจริงของคุณกับพวกเขา"
photo_copy_7="เพิ่มฉันใน JustUs ทุกอย่างพร้อมแล้ว ยกเว้นคุณ! รหัสของฉัน:"
photo_tips_7="ส่งไปที่หน้าจอหลักแล้ว! เชิญเพื่อน ๆ มาแบ่งปันชีวิตจริงของคุณกับพวกเขามากขึ้น"
photo_end_7="ไม่มีรูปถ่ายอีกต่อไป เพิ่มเพื่อนเพื่อแบ่งปันชีวิตจริงของคุณกับพวกเขา"
photo_copy_8="เพิ่มฉันใน JustUs - Widget Social Network แบ่งปันชีวิตจริงกับฉัน! รหัสของฉัน:"
photo_tips_8="ส่งไปที่หน้าจอหลักแล้ว! เชิญเพื่อน ๆ มาแบ่งปันชีวิตจริงของคุณกับพวกเขามากขึ้น"
photo_end_8="ไม่มีรูปถ่ายอีกต่อไป เพิ่มเพื่อนเพื่อแบ่งปันชีวิตจริงของคุณกับพวกเขา"
photo_copy_9="ยอมรับความท้าทายภาพถ่ายในชีวิตจริง เพิ่มฉันใน JustUs รหัสของฉัน:"
photo_tips_9="ส่งไปที่หน้าจอหลักแล้ว! เชิญเพื่อน ๆ มาแบ่งปันชีวิตจริงของคุณกับพวกเขามากขึ้น"
photo_end_9="ไม่มีรูปถ่ายอีกต่อไป เพิ่มเพื่อนเพื่อแบ่งปันชีวิตจริงของคุณกับพวกเขา"
photo_copy_10="ฉันอยากให้คุณอยู่ที่หน้าจอหลักของฉัน เพิ่มฉันใน JustUs รหัสของฉัน:"
photo_tips_10="ส่งไปที่หน้าจอหลักแล้ว! มันจะสนุกมากขึ้นถ้าคุณเพิ่มเพื่อนมากขึ้น"
photo_end_10="ไม่มีรูปถ่ายอีกต่อไป เพิ่มเพื่อนเพื่อแบ่งปันชีวิตจริงของคุณด้วยกัน"
photo_copy_11="ฉันอยากให้คุณอยู่ที่หน้าจอหลักของฉัน เพิ่มฉันใน JustUs รหัสของฉัน:"
photo_tips_11="ส่งไปที่หน้าจอหลักแล้ว! เพิ่มเพื่อนเพื่อส่งรูปภาพของคุณไปที่หน้าจอหลักของพวกเขา"
photo_end_11="ดูเหมือนเพื่อนจะหมดรูปแล้ว! เพิ่มเพื่อนเพื่อบันทึกชีวิตจริงของคุณร่วมกัน"
photo_copy_12="เป็นเพื่อนบนหน้าจอหลักของฉัน เพิ่มฉันใน JustUs รหัสของฉัน:"
photo_tips_12="ส่งไปที่หน้าจอหลักแล้ว! เชิญเพื่อน ๆ มาที่หน้าจอหลักของคุณและส่งรูปถ่ายแสนสนุกให้พวกเขา!"
photo_end_12="ดูเหมือนเพื่อนจะหมดรูปแล้ว! เชิญเพื่อน ๆ มาที่หน้าจอหลักของคุณและส่งรูปภาพสนุกๆ ให้พวกเขา"
photo_copy_13="เป็นเพื่อนบนหน้าจอหลักของฉัน เพิ่มฉันใน JustUs รหัสของฉัน:"
photo_tips_13="ส่งไปที่หน้าจอหลักแล้ว! มันจะสนุกมากขึ้นถ้าคุณเพิ่มเพื่อนบนหน้าจอหลักมากขึ้น"
photo_end_13="ดูเหมือนว่าคุณต้องการเพื่อนเพิ่ม! เชิญเพื่อน ๆ มาที่หน้าจอหลักของคุณและส่งรูปภาพสนุกๆ ให้พวกเขา"
your_self_visible="มีเพียงฉันเท่านั้นที่มองเห็นได้"
update_new_version="ฟังก์ชั่นคู่ใหม่ โปรดมาอัปเกรดและสัมผัสมัน!"
