param_error="Error de paràmetre"
component_num_limit="No pots crear més grups temporalment."
friend_num_limit="No pots afegir més amics temporalment."
operation_error="L'operació ha fallat. Siusplau, intenta-ho més tard!"
char_limit="Els caràcters que heu introduït superen el límit de longitud màxima. El màxim :number caràcters."
first_name_limit="El \"Cognom\" que heu introduït supera el límit de longitud màxima. El màxim :number caràcters."
last_name_limit="El \"Nom\" que heu introduït supera el límit de longitud màxima. El màxim :number caràcters."
first_name_required="El \"Cognom\" no pot estar buit."
last_name_required="El \"Nom\" no pot estar buit."
mobile_error="Error de format del número de telèfon"
mobile_required="El número de telèfon no pot estar buit."
country_code_error="Error del codi de país"
search_key="Introduïu un identificador d'usuari o un número de mòbil vàlid."
is_add_friend="S'ha enviat la sol·licitud per afegir amistat."
system_error="Error del sistema"
msg_code_error="Error de format del codi de verificació"
first_name_length="El \"Cognom\" és massa llarg."
friends_exist="Usuari no trobat"
last_name_length="El \"Nom\" és massa llarg."
content_length="El màxim de 200 caràcters"
he_friend_num_limit="El vostre nombre d'amics o de l'usuari ha arribat al límit."
sign_error="La verificació de la signatura ha fallat"
is_friends="L'usuari ha estat el teu amic."
sms_friend_tips="Afegeix-me a JustUs."
photo_tips="S'ha penjat correctament! Afegeix més amics per compartir la vida real junts"
message_limit="Envieu missatges de text massa sovint. Siusplau, intenta-ho més tard."
copy_friend_tips="Afegeix-me a JustUs."
no_add_friend_self="No pots afegir-te com a amic."
justus_slogan="Gravem la vida real junts!"
justus_helper="Guia JustUs"
bind_mobile_error="El número de telèfon s'ha vinculat a un altre compte."
bound_mobile="Ha fallat l'enllaç. Siusplau, intenta-ho més tard."
not_add_self_friend="No et pots afegir com a amic."
address_book_tips="Sincronitza els teus contactes per trobar amics ja a JustUs. Les vostres dades de contactes s'enviaran a JustUs per millorar la vostra experiència i permetre que vosaltres i els altres trobeu amics."
follow_user="t'ha seguit!"
notification_friends=":name s'ha convertit en el teu amic \"JustUs\"! Prova d'enviar-los fotos!"
notification_like=":name t'ha agradat!"
notification_comment=":name t'acaba de comentar, fes-hi una ullada!"
notification_friend_apply=":name t'ha enviat una sol·licitud d'amistat."
notification_friend_send_picture=":name ha publicat una foto nova."
notification_user_register="Vine i fes-te una foto! Grava la vida real amb els teus amics junts!"
notification_friend_register=":name també és a JustUs. Afegeix?"
notification_memory=":name, tens un nou record."
notification_wait_add_friend=":name, els teus amics estan esperant!"
notification_touch=":name ha tocat la teva foto💓"
notification_follow_user=":name t'ha seguit!"
photo_copy_1="T'he afegit a (JustUs). Baixeu aquesta aplicació per permetre la meva sol·licitud d'amistat.El meu DNI:"
photo_tips_1="S'ha penjat correctament! Afegeix més amics per compartir la vida real junts"
photo_end_1="No més moments d'amics. Fes una foto o afegeix més amics."
photo_copy_2="Afegeix-me a JustUs.El meu DNI:"
photo_tips_2="S'ha penjat correctament! Afegeix més amics per compartir la vida real junts"
photo_end_2="No més moments d'amics. Fes una foto o afegeix més amics."
photo_copy_3="Afegeix-me a JustUs perquè puguem compartir fotos a la nostra pantalla d'inici. El meu DNI:"
photo_tips_3="Enviat a les seves pantalles d'inici! Afegeix més amics per compartir la teva vida real a les teves pantalles d'inici."
photo_end_3="No hi ha més fotos. Afegeix més amics per compartir la teva vida real a les teves pantalles d'inici."
photo_copy_4="Afegeix-me a JustUs, tinc fotos per enviar a la teva pantalla d'inici. El meu DNI:"
photo_tips_4="Enviat a les seves pantalles d'inici! Afegeix més amics per compartir la teva vida real a les teves pantalles d'inici."
photo_end_4="No hi ha més fotos. Afegeix més amics per compartir la teva vida real a les teves pantalles d'inici."
photo_copy_5="Afegeix-me a JustUs, la nova xarxa social de giny! El meu DNI:"
photo_tips_5="Enviat a les seves pantalles d'inici! Afegeix més amics per compartir la teva vida real a les teves pantalles d'inici."
photo_end_5="No hi ha més fotos. Convida més amics a compartir les teves vides reals a les teves pantalles d'inici."
photo_copy_6="Afegeix-me a JustUs - Widget Social Network, tot està llest menys tu!"
photo_tips_6="Enviat a les seves pantalles d'inici! Convida més amics a compartir la teva vida real amb ells."
photo_end_6="No hi ha més fotos. Afegeix més amics per compartir la teva vida real amb ells."
photo_copy_7="Afegeix-me a JustUs, tot està preparat excepte tu! El meu DNI:"
photo_tips_7="Enviat a les seves pantalles d'inici! Convida més amics a compartir la teva vida real amb ells."
photo_end_7="No hi ha més fotos. Afegeix més amics per compartir la teva vida real amb ells."
photo_copy_8="Afegeix-me a JustUs - Widget Social Network, comparteix la vida real amb mi! El meu DNI:"
photo_tips_8="Enviat a les seves pantalles d'inici! Convida més amics a compartir la teva vida real amb ells."
photo_end_8="No hi ha més fotos. Afegeix més amics per compartir la teva vida real amb ells."
photo_copy_9="Accepta el repte fotogràfic de la vida real, Afegeix-me a JustUs. El meu DNI:"
photo_tips_9="Enviat a les seves pantalles d'inici! Convida més amics a compartir la teva vida real amb ells."
photo_end_9="No hi ha més fotos. Afegeix més amics per compartir la teva vida real amb ells."
photo_copy_10="Vull que estiguis a la meva pantalla d'inici, afegeix-me a JustUs. El meu DNI:"
photo_tips_10="Enviat a les seves pantalles d'inici! Seria més divertit si afegiu més amics."
photo_end_10="No hi ha més fotos. Afegeix més amics per compartir la teva vida real junts."
photo_copy_11="Vull que estiguis a la meva pantalla d'inici, afegeix-me a JustUs. El meu DNI:"
photo_tips_11="Enviat a les seves pantalles d'inici! Afegeix més amics per enviar les teves fotos a les seves pantalles d'inici."
photo_end_11="Sembla que t'has quedat sense fotos dels amics! Afegeix més amics per gravar les teves vides reals junts."
photo_copy_12="Sigues el meu amic de la pantalla d'inici, afegeix-me a JustUs. El meu DNI:"
photo_tips_12="Enviat a les seves pantalles d'inici! Convida més amics a la teva pantalla d'inici i envia'ls fotos divertides!"
photo_end_12="Sembla que t'has quedat sense fotos dels amics! Convida més amics a la pantalla d'inici i envia'ls fotos divertides."
photo_copy_13="Sigues el meu amic de la pantalla d'inici, afegeix-me a JustUs. El meu DNI:"
photo_tips_13="Enviat a les seves pantalles d'inici! Seria més divertit si afegiu més amics a la pantalla d'inici."
photo_end_13="Sembla que necessiteu més amics! Convida més amics a la pantalla d'inici i envia'ls fotos divertides."
your_self_visible="Només visible per a mi"
update_new_version="Nova funció de duet, vine a actualitzar-la i experimenta-la!"
