param_error="Błąd parametru"
component_num_limit="Tymczasowo nie możesz tworzyć kolejnych grup."
friend_num_limit="Tymczasowo nie możesz dodać więcej znajomych."
operation_error="Operacja nie powiodła się. Spróbuj ponownie później!"
char_limit="Wprowadzone znaki przekraczają maksymalny limit długości. Maksymalnie :number znaków."
first_name_limit="Wprowadzone „Nazwisko” przekracza maksymalny limit długości. Maksymalnie :number znaków."
last_name_limit="Wpisane „Imię” przekracza maksymalny limit długości. Maksymalnie :number znaków."
first_name_required="Pole „Nazwisko” nie może być puste."
last_name_required="Pole „Imię” nie może być puste."
mobile_error="Błąd formatu numeru telefonu"
mobile_required="Numer telefonu nie może być pusty."
country_code_error="Błąd kodu kraju"
search_key="Wprowadź prawidłowy identyfikator użytkownika lub numer telefonu komórkowego."
is_add_friend="Prośba o dodanie do znajomych została wysłana."
system_error="Błąd systemu"
msg_code_error="Błąd formatu kodu weryfikacyjnego"
first_name_length="„Nazwisko” jest za długie."
friends_exist="Użytkownik nie znaleziony"
last_name_length="„Imię” jest za długie."
content_length="Maksymalnie 200 znaków"
he_friend_num_limit="Liczba znajomych Twoich lub użytkownika osiągnęła limit."
sign_error="Weryfikacja podpisu nieudana"
is_friends="Użytkownik był twoim przyjacielem."
sms_friend_tips="Dodaj mnie na gin-default."
photo_tips="Przesłano pomyślnie! Dodaj więcej znajomych, aby wspólnie dzielić prawdziwe życie"
message_limit="Zbyt często wysyłasz SMS-y. Spróbuj ponownie później."
copy_friend_tips="Dodaj mnie na gin-default."
no_add_friend_self="Nie możesz dodać siebie jako przyjaciela."
gin-default_slogan="Nagrajmy razem prawdziwe życie!"
gin-default_helper="Przewodnik gin-default"
bind_mobile_error="Numer telefonu został powiązany z innym kontem."
bound_mobile="Wiązanie nie powiodło się. Spróbuj ponownie później."
not_add_self_friend="Nie możesz dodać siebie jako przyjaciela."
address_book_tips="Zsynchronizuj swoje kontakty, aby znaleźć znajomych już w gin-default. Twoje dane kontaktowe zostaną wysłane do gin-default, aby poprawić Twoje wrażenia i umożliwić Tobie i innym znalezienie znajomych."
follow_user="za tobą!"
notification_friends=":name został Twoim przyjacielem „Tylko my”! Spróbuj wysłać im zdjęcia!"
notification_like=":name po prostu cię lubi!"
notification_comment=":name właśnie Cię skomentował, sprawdź to!"
notification_friend_apply=":name wysłał Ci zaproszenie do znajomych."
notification_friend_send_picture=":name opublikował nowe zdjęcie."
notification_user_register="Przyjdź i zrób zdjęcie! Nagrywaj prawdziwe życie razem ze znajomymi!"
notification_friend_register=":name jest również na gin-default. Dodać?"
notification_memory=":name, masz nowe wspomnienie."
notification_wait_add_friend=":name, twoi przyjaciele czekają!"
notification_touch=":name dotknął twojego zdjęcia💓"
notification_follow_user=":name za tobą!"
photo_copy_1="Dodałem Cię na (gin-default). Pobierz tę aplikację, aby umożliwić moją prośbę przyjaciela.Mój dokument tożsamości:"
photo_tips_1="Przesłano pomyślnie! Dodaj więcej znajomych, aby wspólnie dzielić prawdziwe życie"
photo_end_1="Żadnych chwil z przyjaciółmi. Zrób zdjęcie lub dodaj więcej znajomych."
photo_copy_2="Dodaj mnie na gin-default. Mój dokument tożsamości:"
photo_tips_2="Przesłano pomyślnie! Dodaj więcej znajomych, aby wspólnie dzielić prawdziwe życie"
photo_end_2="Żadnych chwil z przyjaciółmi. Zrób zdjęcie lub dodaj więcej znajomych."
photo_copy_3="Dodaj mnie do gin-default, abyśmy mogli udostępniać zdjęcia na naszym ekranie głównym. Mój dokument tożsamości:"
photo_tips_3="Wysłane na ich ekrany główne! Dodaj więcej znajomych, aby dzielić się swoim prawdziwym życiem na ekranach głównych."
photo_end_3="Nigdy więcej zdjęć. Dodaj więcej znajomych, aby dzielić się swoim prawdziwym życiem na ekranach głównych."
photo_copy_4="Dodaj mnie w gin-default, mam zdjęcia do wysłania na Twój ekran główny. Mój dokument tożsamości:"
photo_tips_4="Wysłane na ich ekrany główne! Dodaj więcej znajomych, aby dzielić się swoim prawdziwym życiem na ekranach głównych."
photo_end_4="Nigdy więcej zdjęć. Dodaj więcej znajomych, aby dzielić się swoim prawdziwym życiem na ekranach głównych."
photo_copy_5="Dodaj mnie do gin-default, nowej sieci społecznościowej z widżetami! Mój dokument tożsamości:"
photo_tips_5="Wysłane na ich ekrany główne! Dodaj więcej znajomych, aby dzielić się swoim prawdziwym życiem na ekranach głównych."
photo_end_5="Nigdy więcej zdjęć. Zaproś więcej znajomych do dzielenia się Twoim prawdziwym życiem na ekranach głównych."
photo_copy_6="Dodaj mnie do gin-default - Widget Social Network, wszystko jest gotowe oprócz Ciebie!"
photo_tips_6="Wysłane na ich ekrany główne! Zaproś więcej znajomych, aby podzielili się z nimi swoim prawdziwym życiem."
photo_end_6="Nigdy więcej zdjęć. Dodaj więcej znajomych, aby dzielić się z nimi swoim prawdziwym życiem."
photo_copy_7="Dodaj mnie do gin-default, wszystko jest gotowe oprócz Ciebie! Mój dokument tożsamości:"
photo_tips_7="Wysłane na ich ekrany główne! Zaproś więcej znajomych, aby podzielili się z nimi swoim prawdziwym życiem."
photo_end_7="Nigdy więcej zdjęć. Dodaj więcej znajomych, aby dzielić się z nimi swoim prawdziwym życiem."
photo_copy_8="Dodaj mnie do gin-default - Widget Social Network, podziel się ze mną prawdziwym życiem! Mój dokument tożsamości:"
photo_tips_8="Wysłane na ich ekrany główne! Zaproś więcej znajomych, aby podzielili się z nimi swoim prawdziwym życiem."
photo_end_8="Nigdy więcej zdjęć. Dodaj więcej znajomych, aby dzielić się z nimi swoim prawdziwym życiem."
photo_copy_9="Zaakceptuj prawdziwe wyzwanie fotograficzne, Dodaj mnie na gin-default. Mój dokument tożsamości:"
photo_tips_9="Wysłane na ich ekrany główne! Zaproś więcej znajomych, aby podzielili się z nimi swoim prawdziwym życiem."
photo_end_9="Nigdy więcej zdjęć. Dodaj więcej znajomych, aby dzielić się z nimi swoim prawdziwym życiem."
photo_copy_10="Chcę, żebyś był na moim ekranie głównym, dodaj mnie na gin-default. Mój dokument tożsamości:"
photo_tips_10="Wysłane na ich ekrany główne! Byłoby fajniej, gdybyś dodał więcej znajomych."
photo_end_10="Nigdy więcej zdjęć. Dodaj więcej znajomych, aby dzielić się swoim prawdziwym życiem."
photo_copy_11="Chcę, żebyś był na moim ekranie głównym, dodaj mnie na gin-default. Mój dokument tożsamości:"
photo_tips_11="Wysłane na ich ekrany główne! Dodaj więcej znajomych, aby wysyłać zdjęcia na ich ekrany główne."
photo_end_11="Wygląda na to, że zabrakło Ci zdjęć znajomych! Dodaj więcej znajomych, aby nagrać swoje wspólne życie."
photo_copy_12="Zostań moim przyjacielem na ekranie głównym, dodaj mnie w gin-default. Mój dokument tożsamości:"
photo_tips_12="Wysłane na ich ekrany główne! Zaproś więcej znajomych na swój ekran główny i wyślij im zabawne zdjęcia!"
photo_end_12="Wygląda na to, że zabrakło Ci zdjęć znajomych! Zaproś więcej znajomych na ekran główny i wyślij im zabawne zdjęcia."
photo_copy_13="Zostań moim przyjacielem na ekranie głównym, dodaj mnie w gin-default. Mój dokument tożsamości:"
photo_tips_13="Wysłane na ich ekrany główne! Byłoby fajniej, gdybyś dodał więcej znajomych na ekranie głównym."
photo_end_13="Wygląda na to, że potrzebujesz więcej przyjaciół! Zaproś więcej znajomych na ekran główny i wyślij im zabawne zdjęcia."
your_self_visible="Widoczne tylko dla mnie"
update_new_version="Nowa funkcja duetu, przyjdź, aby ją zaktualizować i przeżyć!"
