param_error="पैरामीटर त्रुटि"
component_num_limit="आप अस्थायी रूप से अधिक समूह बनाने में असमर्थ हैं।"
friend_num_limit="आप अस्थायी रूप से अधिक मित्रों को जोड़ने में असमर्थ हैं।"
operation_error="प्रचालन विफल रहा। बाद में पुन: प्रयास करें!"
char_limit="आपके द्वारा दर्ज किए गए वर्ण अधिकतम लंबाई सीमा से अधिक हैं। अधिकतम :number वर्ण।"
first_name_limit="आपके द्वारा दर्ज किया गया \"अंतिम नाम\" अधिकतम लंबाई सीमा से अधिक है। अधिकतम :number वर्ण।"
last_name_limit="आपके द्वारा दर्ज किया गया \"प्रथम नाम\" अधिकतम लंबाई सीमा से अधिक है। अधिकतम :number वर्ण।"
first_name_required="अंतिम नाम खाली नहीं हो सकता।"
last_name_required="प्रथम नाम खाली नहीं हो सकता।"
mobile_error="फ़ोन नंबर प्रारूप त्रुटि"
mobile_required="फ़ोन नंबर खाली नहीं हो सकता."
country_code_error="देश कोड त्रुटि"
search_key="कृपया एक मान्य उपयोगकर्ता आईडी या मोबाइल नंबर दर्ज करें।"
is_add_friend="ऐड फ्रेंड रिक्वेस्ट भेज दी गई है।"
system_error="सिस्टम में गड़बड़ी"
msg_code_error="सत्यापन कोड प्रारूप त्रुटि"
first_name_length="उपनाम बहुत लंबा है।"
friends_exist="उपयोगकर्ता नहीं मिला"
last_name_length="प्रथम नाम बहुत लंबा है."
content_length="अधिकतम 200 वर्ण"
he_friend_num_limit="आपके या उपयोगकर्ता के मित्रों की संख्या सीमा तक पहुंच गई है।"
sign_error="हस्ताक्षर जाँच असफल रही"
is_friends="उपयोगकर्ता आपका मित्र रहा है।"
sms_friend_tips="मुझे gin-default पर जोड़ें।"
photo_tips="सफलतापूर्वक अपलोड किया गया! वास्तविक जीवन को एक साथ साझा करने के लिए और मित्रों को जोड़ें"
message_limit="आप अक्सर पाठ संदेश भेजते हैं। बाद में पुन: प्रयास करें।"
copy_friend_tips="मुझे gin-default पर जोड़ें।"
no_add_friend_self="आप खुद को एक मित्र के रूप में नहीं जोड़ सकते।"
gin-default_slogan="आइए वास्तविक जीवन को एक साथ रिकॉर्ड करें!"
gin-default_helper="gin-default गाइड"
bind_mobile_error="फोन नंबर दूसरे खाते से जुड़ा हुआ है।"
bound_mobile="बंधन विफल। बाद में पुन: प्रयास करें।"
not_add_self_friend="आप अपने आप को एक मित्र के रूप में नहीं जोड़ सकते।"
address_book_tips="gin-default पर पहले से मौजूद मित्रों को खोजने के लिए अपने संपर्कों को सिंक करें। आपके अनुभव को बेहतर बनाने और आपको और अन्य लोगों को मित्र खोजने की अनुमति देने के लिए आपका संपर्क डेटा gin-default को भेजा जाएगा।"
follow_user="तुम्हारा पीछा!"
notification_friends=":name आपका \"बस हमारे\" मित्र बन गया है! उन्हें फ़ोटो भेजने का प्रयास करें!"
notification_like=":name बस आपको पसंद आया!"
notification_comment=":name ने अभी-अभी आप पर टिप्पणी की है, इसे देखें!"
notification_friend_apply=":name ने आपको एक मित्र अनुरोध भेजा है।"
notification_friend_send_picture=":name ने एक नई फ़ोटो पोस्ट की."
notification_user_register="आओ और फोटो खींचो! अपने दोस्तों के साथ वास्तविक जीवन को एक साथ रिकॉर्ड करें!"
notification_friend_register=":name gin-default पर भी है। जोड़ें?"
notification_memory=":name, आपके पास एक नई मेमोरी है।"
notification_wait_add_friend=":name, आपके मित्र प्रतीक्षा कर रहे हैं!"
notification_touch=":name ने आपकी तस्वीर को टैप किया💓"
notification_follow_user=":name तुम्हारा पीछा!"
photo_copy_1="मैंने आपको (gin-default) में जोड़ा है। मेरे मित्र अनुरोध की अनुमति देने के लिए इस ऐप को डाउनलोड करें।मेरी आईडी:"
photo_tips_1="सफलतापूर्वक अपलोड किया गया! वास्तविक जीवन को एक साथ साझा करने के लिए और मित्रों को जोड़ें"
photo_end_1="कोई और दोस्त के क्षण नहीं। फ़ोटो लें या अधिक मित्र जोड़ें।"
photo_copy_2="मुझे gin-default पर जोड़ें। मेरी आईडी:"
photo_tips_2="सफलतापूर्वक अपलोड किया गया! वास्तविक जीवन को एक साथ साझा करने के लिए और मित्रों को जोड़ें"
photo_end_2="कोई और दोस्त के क्षण नहीं। फ़ोटो लें या अधिक मित्र जोड़ें।"
photo_copy_3="मुझे gin-default पर जोड़ें ताकि हम अपने होमस्क्रीन पर तस्वीरें साझा कर सकें। मेरी आईडी:"
photo_tips_3="उनके होमस्क्रीन पर भेजा गया! अपने वास्तविक जीवन को अपने होमस्क्रीन पर साझा करने के लिए और मित्र जोड़ें।"
photo_end_3="कोई और तस्वीरें नहीं। अपने वास्तविक जीवन को अपने होमस्क्रीन पर साझा करने के लिए और मित्र जोड़ें।"
photo_copy_4="मुझे gin-default पर जोड़ें, मेरे पास आपके होमस्क्रीन पर भेजने के लिए तस्वीरें हैं। मेरी आईडी:"
photo_tips_4="उनके होमस्क्रीन पर भेजा गया! अपने वास्तविक जीवन को अपने होमस्क्रीन पर साझा करने के लिए और मित्र जोड़ें।"
photo_end_4="कोई और तस्वीरें नहीं। अपने वास्तविक जीवन को अपने होमस्क्रीन पर साझा करने के लिए और मित्र जोड़ें।"
photo_copy_5="मुझे gin-default पर जोड़ें, नया विजेट सोशल नेटवर्क! मेरी आईडी:"
photo_tips_5="उनके होमस्क्रीन पर भेजा गया! अपने वास्तविक जीवन को अपने होमस्क्रीन पर साझा करने के लिए और मित्र जोड़ें।"
photo_end_5="कोई और तस्वीरें नहीं। अपने वास्तविक जीवन को अपने होमस्क्रीन पर साझा करने के लिए और मित्रों को आमंत्रित करें।"
photo_copy_6="मुझे gin-default - विजेट सोशल नेटवर्क पर जोड़ें, आपके अलावा सब तैयार है!"
photo_tips_6="उनके होमस्क्रीन पर भेजा गया! अपने वास्तविक जीवन को उनके साथ साझा करने के लिए और अधिक मित्रों को आमंत्रित करें।"
photo_end_6="कोई और तस्वीरें नहीं। अपने वास्तविक जीवन को उनके साथ साझा करने के लिए और अधिक मित्र जोड़ें।"
photo_copy_7="मुझे gin-default में जोड़ें, आपके अलावा सब कुछ तैयार है! मेरी आईडी:"
photo_tips_7="उनके होमस्क्रीन पर भेजा गया! अपने वास्तविक जीवन को उनके साथ साझा करने के लिए और अधिक मित्रों को आमंत्रित करें।"
photo_end_7="कोई और तस्वीरें नहीं। अपने वास्तविक जीवन को उनके साथ साझा करने के लिए और अधिक मित्र जोड़ें।"
photo_copy_8="मुझे gin-default - विजेट सोशल नेटवर्क पर जोड़ें, मेरे साथ वास्तविक जीवन साझा करें! मेरी आईडी:"
photo_tips_8="उनके होमस्क्रीन पर भेजा गया! अपने वास्तविक जीवन को उनके साथ साझा करने के लिए और अधिक मित्रों को आमंत्रित करें।"
photo_end_8="कोई और तस्वीरें नहीं। अपने वास्तविक जीवन को उनके साथ साझा करने के लिए और अधिक मित्र जोड़ें।"
photo_copy_9="वास्तविक जीवन फोटो चुनौती स्वीकार करें, मुझे gin-default पर जोड़ें। मेरी आईडी:"
photo_tips_9="उनके होमस्क्रीन पर भेजा गया! अपने वास्तविक जीवन को उनके साथ साझा करने के लिए और अधिक मित्रों को आमंत्रित करें।"
photo_end_9="कोई और तस्वीरें नहीं। अपने वास्तविक जीवन को उनके साथ साझा करने के लिए और अधिक मित्र जोड़ें।"
photo_copy_10="मैं चाहता हूं कि आप मेरे होमस्क्रीन पर हों, मुझे gin-default में जोड़ें। मेरी आईडी:"
photo_tips_10="उनके होमस्क्रीन पर भेजा गया! यदि आप और मित्र जोड़ते हैं तो यह अधिक मजेदार होगा।"
photo_end_10="कोई और तस्वीरें नहीं। अपने वास्तविक जीवन को एक साथ साझा करने के लिए और मित्र जोड़ें।"
photo_copy_11="मैं चाहता हूं कि आप मेरे होमस्क्रीन पर हों, मुझे gin-default में जोड़ें। मेरी आईडी:"
photo_tips_11="उनके होमस्क्रीन पर भेजा गया! अपनी फ़ोटो को उनके होमस्क्रीन पर भेजने के लिए और मित्रों को जोड़ें।"
photo_end_11="ऐसा लगता है कि आपके पास मित्रों की फ़ोटो समाप्त हो गई हैं! अपने वास्तविक जीवन को एक साथ रिकॉर्ड करने के लिए और मित्र जोड़ें।"
photo_copy_12="मेरे होमस्क्रीन दोस्त बनो, मुझे gin-default में शामिल करो। मेरी आईडी:"
photo_tips_12="उनके होमस्क्रीन पर भेजा गया! अपने होमस्क्रीन पर और दोस्तों को आमंत्रित करें और उन्हें मजेदार तस्वीरें भेजें!"
photo_end_12="ऐसा लगता है कि आपके पास मित्रों की फ़ोटो समाप्त हो गई हैं! अपने होमस्क्रीन पर और दोस्तों को आमंत्रित करें और उन्हें मजेदार तस्वीरें भेजें।"
photo_copy_13="मेरे होमस्क्रीन दोस्त बनो, मुझे gin-default में शामिल करो। मेरी आईडी:"
photo_tips_13="उनके होमस्क्रीन पर भेजा गया! यदि आप अधिक होमस्क्रीन मित्र जोड़ते हैं तो यह अधिक मजेदार होगा।"
photo_end_13="लगता है आपको और दोस्तों की जरूरत है! अपने होमस्क्रीन पर और दोस्तों को आमंत्रित करें और उन्हें मजेदार तस्वीरें भेजें।"
your_self_visible="केवल मुझे दिखाई देता है"
update_new_version="नया युगल समारोह, कृपया इसे अपग्रेड करने और इसका अनुभव करने के लिए आएं!"
