param_error="Parameetri viga"
component_num_limit="Te ei saa ajutiselt rohkem gruppe luua."
friend_num_limit="Te ei saa ajutiselt rohkem sõpru lisada."
operation_error="Toiming ebaõnnestus. Palun proovi hiljem uuesti!"
char_limit="Sisestatud märgid ületavad maksimaalse pikkuse. Maksimaalselt :number tähemärki."
first_name_limit="Sisestatud \"Perenimi\" ületab maksimaalse pikkuse. Maksimaalselt :number tähemärki."
last_name_limit="Sisestatud \"eesnimi\" ületab maksimaalse pikkuse. Maksimaalselt :number tähemärki."
first_name_required="Perekonnanimi ei saa olla tühi."
last_name_required="Eesnimi ei saa olla tühi."
mobile_error="Telefoninumbri vormingu viga"
mobile_required="Telefoninumber ei tohi olla tühi."
country_code_error="Riigikoodi viga"
search_key="Sisestage kehtiv kasutaja ID või mobiilinumber."
is_add_friend="Sõbra lisamise taotlus on saadetud."
system_error="Süsteemitõrge"
msg_code_error="Kinnituskoodi vormingu viga"
first_name_length="Perenimi on liiga pikk."
friends_exist="Kasutajat ei leitud"
last_name_length="Eesnimi on liiga pikk."
content_length="Maksimaalselt 200 tähemärki"
he_friend_num_limit="Teie või kasutaja sõprade arv on täis."
sign_error="Allkirja kontroll ebaõnnestus"
is_friends="Kasutaja on olnud teie sõber."
sms_friend_tips="Lisa mind JustUsi."
photo_tips="Üleslaadimine õnnestus! Lisage rohkem sõpru, et koos päriselu jagada"
message_limit="Saadate tekstisõnumeid liiga sageli. Palun proovi hiljem uuesti."
copy_friend_tips="Lisa mind JustUsi."
no_add_friend_self="Te ei saa end sõbraks lisada."
justus_slogan="Jäädvustame koos päriselu!"
justus_helper="JustUsi juhend"
bind_mobile_error="Telefoninumber on seotud teise kontoga."
bound_mobile="Sidumine ebaõnnestus. Palun proovi hiljem uuesti."
not_add_self_friend="Te ei saa end sõbraks lisada."
address_book_tips="Sünkroonige oma kontaktid, et leida sõpru juba JustUsis. Teie kontaktandmed saadetakse JustUsile, et parandada teie kasutuskogemust ja võimaldada teil ja teistel sõpru leida."
follow_user="järgnes sulle!"
notification_friends="Kasutajast :name on saanud teie \"Lihtsalt meie\" sõber! Proovige neile fotosid saata!"
notification_like=":name sa just meeldisid!"
notification_comment=":name just kommenteeris teid, vaadake seda!"
notification_friend_apply=":name saatis teile sõbrakutse."
notification_friend_send_picture=":name postitas uue foto."
notification_user_register="Tule pildistama! Salvestage koos sõpradega päriselu!"
notification_friend_register=":name on ka JustUsis. Lisama?"
notification_memory=":name, teil on uus mälu."
notification_wait_add_friend=":name, teie sõbrad ootavad!"
notification_touch=":name puudutas teie fotot💓"
notification_follow_user=":name järgnes sulle!"
photo_copy_1="Lisasin teid teenusesse (JustUs). Laadige see rakendus alla, et lubada minu sõbrakutse.Minu ID:"
photo_tips_1="Üleslaadimine õnnestus! Lisage rohkem sõpru, et koos päriselu jagada"
photo_end_1="Pole enam sõprade hetki. Tehke foto või lisage rohkem sõpru."
photo_copy_2="Lisa mind JustUsi.Minu ID:"
photo_tips_2="Üleslaadimine õnnestus! Lisage rohkem sõpru, et koos päriselu jagada"
photo_end_2="Pole enam sõprade hetki. Tehke foto või lisage rohkem sõpru."
photo_copy_3="Lisage mind JustUsi, et saaksime oma avaekraanil fotosid jagada. Minu ID:"
photo_tips_3="Saadeti nende avakuvadele! Lisage rohkem sõpru, et jagada oma tõelist elu oma avaekraanidel."
photo_end_3="Rohkem fotosid pole. Lisage rohkem sõpru, et jagada oma tõelist elu oma avaekraanidel."
photo_copy_4="Lisage mind JustUsi, mul on fotod, mida teie avakuvale saata. Minu ID:"
photo_tips_4="Saadeti nende avakuvadele! Lisage rohkem sõpru, et jagada oma tõelist elu oma avaekraanidel."
photo_end_4="Rohkem fotosid pole. Lisage rohkem sõpru, et jagada oma tõelist elu oma avaekraanidel."
photo_copy_5="Lisa mind JustUsi, uue vidina sotsiaalvõrgustikku! Minu ID:"
photo_tips_5="Saadeti nende avakuvadele! Lisage rohkem sõpru, et jagada oma tõelist elu oma avaekraanidel."
photo_end_5="Rohkem fotosid pole. Kutsuge rohkem sõpru jagama oma tõelist elu teie avaekraanidel."
photo_copy_6="Lisa mind JustUs – vidinate sotsiaalvõrgustikus, kõik peale sinu on valmis!"
photo_tips_6="Saadeti nende avakuvadele! Kutsuge rohkem sõpru oma tegelikku elu nendega jagama."
photo_end_6="Rohkem fotosid pole. Lisage rohkem sõpru, et jagada nendega oma päriselu."
photo_copy_7="Lisa mind JustUsi, kõik peale sinu on valmis! Minu ID:"
photo_tips_7="Saadeti nende avakuvadele! Kutsuge rohkem sõpru oma tegelikku elu nendega jagama."
photo_end_7="Rohkem fotosid pole. Lisage rohkem sõpru, et jagada nendega oma päriselu."
photo_copy_8="Lisa mind JustUs – vidinate sotsiaalvõrgustikus, jaga minuga päriselu! Minu ID:"
photo_tips_8="Saadeti nende avakuvadele! Kutsuge rohkem sõpru oma tegelikku elu nendega jagama."
photo_end_8="Rohkem fotosid pole. Lisage rohkem sõpru, et jagada nendega oma päriselu."
photo_copy_9="Võtke vastu päriselu fotoväljakutse, lisage mind JustUsi. Minu ID:"
photo_tips_9="Saadeti nende avakuvadele! Kutsuge rohkem sõpru oma tegelikku elu nendega jagama."
photo_end_9="Rohkem fotosid pole. Lisage rohkem sõpru, et jagada nendega oma päriselu."
photo_copy_10="Ma tahan, et oleksite minu avakuval, lisage mind JustUsi. Minu ID:"
photo_tips_10="Saadeti nende avakuvadele! Oleks lõbusam, kui lisate rohkem sõpru."
photo_end_10="Rohkem fotosid pole. Lisage rohkem sõpru, et koos oma päriselu jagada."
photo_copy_11="Ma tahan, et oleksite minu avakuval, lisage mind JustUsi. Minu ID:"
photo_tips_11="Saadeti nende avakuvadele! Lisage rohkem sõpru, et saata oma fotod nende avakuvale."
photo_end_11="Näib, et sõprade fotod on otsa saanud! Lisage rohkem sõpru, et jäädvustada oma päriselu koos."
photo_copy_12="Olge minu avaekraani sõber, lisage mind JustUsi. Minu ID:"
photo_tips_12="Saadeti nende avakuvadele! Kutsuge oma avakuvale rohkem sõpru ja saatke neile lõbusaid fotosid!"
photo_end_12="Näib, et sõprade fotod on otsa saanud! Kutsuge rohkem sõpru oma avakuvale ja saatke neile lõbusaid fotosid."
photo_copy_13="Olge minu avaekraani sõber, lisage mind JustUsi. Minu ID:"
photo_tips_13="Saadeti nende avakuvadele! Oleks lõbusam, kui lisate rohkem avaekraani sõpru."
photo_end_13="Tundub, et vajate rohkem sõpru! Kutsuge rohkem sõpru oma avakuvale ja saatke neile lõbusaid fotosid."
your_self_visible="Nähtav ainult mulle"
update_new_version="Uus duetifunktsioon, palun tulge uuendama ja kogema seda!"
