param_error="Parametrivirhe"
component_num_limit="Et voi tilapäisesti luoda lisää ryhmiä."
friend_num_limit="Et voi tilapäisesti lisätä uusia ystäviä."
operation_error="Toimenpide epäonnistui. Yritä uudelleen myöhemmin!"
char_limit="Antamasi merkit ylittävät enimmäispituusrajoituksen. Enimmäismäärä :number merkkiä."
first_name_limit="Antamasi \"sukunimi\" ylittää enimmäispituusrajoituksen. Enimmäismäärä :number merkkiä."
last_name_limit="Antamasi \"etunimi\" ylittää enimmäispituusrajoituksen. Enimmäismäärä :number merkkiä."
first_name_required="Sukunimi ei voi olla tyhjä."
last_name_required="Etunimi ei voi olla tyhjä."
mobile_error="Puhelinnumeron muotovirhe"
mobile_required="Puhelinnumero ei voi olla tyhjä."
country_code_error="Maakoodivirhe"
search_key="Anna kelvollinen käyttäjätunnus tai matkapuhelinnumero."
is_add_friend="Lisää kaveripyyntö on lähetetty."
system_error="Järjestelmävirhe"
msg_code_error="Vahvistuskoodin muotovirhe"
first_name_length="Sukunimi on liian pitkä."
friends_exist="Käyttäjää ei löydy"
last_name_length="Etunimi on liian pitkä."
content_length="Enintään 200 merkkiä"
he_friend_num_limit="Sinun tai käyttäjän ystäviesi määrä on saavuttanut rajan."
sign_error="Allekirjoituksen varmistus epäonnistui"
is_friends="Käyttäjä on ollut ystäväsi."
sms_friend_tips="Lisää minut JustUsiin."
photo_tips="Lähetys onnistui! Lisää ystäviä jakaaksesi todellista elämää yhdessä"
message_limit="Lähetät tekstiviestejä liian usein. Yritä uudelleen myöhemmin."
copy_friend_tips="Lisää minut JustUsiin."
no_add_friend_self="Et voi lisätä itseäsi ystäväksi."
justus_slogan="Nauhoitetaan yhdessä oikeaa elämää!"
justus_helper="JustUs-opas"
bind_mobile_error="Puhelinnumero on sidottu toiseen tiliin."
bound_mobile="Sidonta epäonnistui. Yritä uudelleen myöhemmin."
not_add_self_friend="Et voi lisätä itseäsi ystäväksi."
address_book_tips="Synkronoi yhteystietosi löytääksesi ystäviä, jotka ovat jo JustUsissa. Yhteystietosi lähetetään JustUsille parantaakseen käyttökokemustasi ja auttaaksemme sinua ja muita löytämään ystäviä."
follow_user="seurasi sinua!"
notification_friends=":name on tullut \"JustUs\" -ystäväsi! Yritä lähettää heille kuvia!"
notification_like=":name vain pidin sinusta!"
notification_comment=":name kommentoi juuri sinua, katso se!"
notification_friend_apply=":name lähetti sinulle kaveripyynnön."
notification_friend_send_picture=":name julkaisi uuden valokuvan."
notification_user_register="Tule ja ota valokuva! Nauhoita todellista elämää ystäviesi kanssa yhdessä!"
notification_friend_register=":name on myös JustUsissa. Lisätä?"
notification_memory=":name, sinulla on uusi muisti."
notification_wait_add_friend=":name, ystäväsi odottavat!"
notification_touch=":name nappasi valokuvaasi💓"
notification_follow_user=":name seurasi sinua!"
photo_copy_1="Olen lisännyt sinut (JustUs) -palveluun. Lataa tämä sovellus salliaksesi ystäväpyynnön.Minun henkilötietoni:"
photo_tips_1="Lähetys onnistui! Lisää ystäviä jakaaksesi todellista elämää yhdessä"
photo_end_1="Ei enää ystävien hetkiä. Ota valokuva tai lisää ystäviä."
photo_copy_2="Lisää minut JustUsiin.Minun henkilötietoni:"
photo_tips_2="Lähetys onnistui! Lisää ystäviä jakaaksesi todellista elämää yhdessä"
photo_end_2="Ei enää ystävien hetkiä. Ota valokuva tai lisää ystäviä."
photo_copy_3="Lisää minut JustUsiin, jotta voimme jakaa valokuvia aloitusnäytöllemme. Minun henkilötietoni:"
photo_tips_3="Lähetetty heidän aloitusnäytöilleen! Lisää ystäviä jakaaksesi todellista elämääsi aloitusnäytöilläsi."
photo_end_3="Ei enempää kuvia. Lisää ystäviä jakaaksesi todellista elämääsi aloitusnäytöilläsi."
photo_copy_4="Lisää minut JustUsiin, minulla on kuvia lähetettäväksi aloitusnäytöllesi. Minun henkilötietoni:"
photo_tips_4="Lähetetty heidän aloitusnäytöilleen! Lisää ystäviä jakaaksesi todellista elämääsi aloitusnäytöilläsi."
photo_end_4="Ei enempää kuvia. Lisää ystäviä jakaaksesi todellista elämääsi aloitusnäytöilläsi."
photo_copy_5="Lisää minut JustUsiin, uuteen sosiaaliseen widget-verkostoon! Minun henkilötietoni:"
photo_tips_5="Lähetetty heidän aloitusnäytöilleen! Lisää ystäviä jakaaksesi todellista elämääsi aloitusnäytöilläsi."
photo_end_5="Ei enempää kuvia. Kutsu lisää ystäviä jakamaan todellista elämääsi aloitusnäytöilläsi."
photo_copy_6="Lisää minut JustUs - Widget Social Networkiin, kaikki on valmis paitsi sinä!"
photo_tips_6="Lähetetty heidän aloitusnäytöilleen! Kutsu lisää ystäviä jakamaan todellista elämääsi heidän kanssaan."
photo_end_6="Ei enempää kuvia. Lisää ystäviä jaaksesi todellista elämääsi heidän kanssaan."
photo_copy_7="Lisää minut JustUsiin, kaikki on valmis paitsi sinua! Minun henkilötietoni:"
photo_tips_7="Lähetetty heidän aloitusnäytöilleen! Kutsu lisää ystäviä jakamaan todellista elämääsi heidän kanssaan."
photo_end_7="Ei enempää kuvia. Lisää ystäviä jaaksesi todellista elämääsi heidän kanssaan."
photo_copy_8="Lisää minut JustUs - Widget Social Network -palveluun, jaa tosielämä kanssani! Minun henkilötietoni:"
photo_tips_8="Lähetetty heidän aloitusnäytöilleen! Kutsu lisää ystäviä jakamaan todellista elämääsi heidän kanssaan."
photo_end_8="Ei enempää kuvia. Lisää ystäviä jaaksesi todellista elämääsi heidän kanssaan."
photo_copy_9="Hyväksy tosielämän valokuvahaaste, Lisää minut JustUsiin. Minun henkilötietoni:"
photo_tips_9="Lähetetty heidän aloitusnäytöilleen! Kutsu lisää ystäviä jakamaan todellista elämääsi heidän kanssaan."
photo_end_9="Ei enempää kuvia. Lisää ystäviä jaaksesi todellista elämääsi heidän kanssaan."
photo_copy_10="Haluan sinun olevan aloitusnäytölläni, lisää minut JustUsiin. Minun henkilötietoni:"
photo_tips_10="Lähetetty heidän aloitusnäytöilleen! Olisi hauskempaa, jos lisäät ystäviä."
photo_end_10="Ei enempää kuvia. Lisää ystäviä jakaaksesi todellista elämääsi yhdessä."
photo_copy_11="Haluan sinun olevan aloitusnäytölläni, lisää minut JustUsiin. Minun henkilötietoni:"
photo_tips_11="Lähetetty heidän aloitusnäytöilleen! Lisää ystäviä lähettääksesi valokuvasi heidän aloitusnäytölleen."
photo_end_11="Näyttää siltä, ​​että ystävien valokuvat ovat loppuneet! Lisää ystäviä tallentaaksesi todellista elämääsi yhdessä."
photo_copy_12="Ole aloitusruudun ystäväni, lisää minut JustUsiin. Minun henkilötietoni:"
photo_tips_12="Lähetetty heidän aloitusnäytöilleen! Kutsu lisää ystäviä aloitusnäytöllesi ja lähetä heille hauskoja kuvia!"
photo_end_12="Näyttää siltä, ​​että ystävien valokuvat ovat loppuneet! Kutsu lisää ystäviä aloitusnäytöllesi ja lähetä heille hauskoja kuvia."
photo_copy_13="Ole aloitusruudun ystäväni, lisää minut JustUsiin. Minun henkilötietoni:"
photo_tips_13="Lähetetty heidän aloitusnäytöilleen! Olisi hauskempaa, jos lisäät aloitusnäytön ystäviä."
photo_end_13="Tarvitset näköjään lisää ystäviä! Kutsu lisää ystäviä aloitusnäytöllesi ja lähetä heille hauskoja kuvia."
your_self_visible="Näkyy vain minulle"
update_new_version="Uusi duettotoiminto, tule päivittämään ja kokemaan se!"
