param_error="Paraméter hiba"
component_num_limit="Átmenetileg nem tud több csoportot létrehozni."
friend_num_limit="Átmenetileg nem tud több barátot hozzáadni."
operation_error="A művelet nem sikerült. Kérlek, próbáld újra később!"
char_limit="A beírt karakterek túllépik a maximális hosszkorlátot. Maximum :number karakter."
first_name_limit="A megadott \"Vezetéknév\" meghaladja a maximális hosszkorlátot. Maximum :number karakter."
last_name_limit="A megadott \"Utónév\" meghaladja a maximális hosszkorlátot. Maximum :number karakter."
first_name_required="A „Vezetéknév” mező nem lehet üres."
last_name_required="A „Keresztnév” mező nem lehet üres."
mobile_error="Telefonszám formátum hiba"
mobile_required="A telefonszám nem lehet üres."
country_code_error="Országkód hiba"
search_key="Adjon meg egy érvényes felhasználói azonosítót vagy mobilszámot."
is_add_friend="Ismerős felvételi kérés elküldve."
system_error="Rendszer hiba"
msg_code_error="Ellenőrző kód formátum hiba"
first_name_length="A „Vezetéknév” túl hosszú."
friends_exist="Felhasználó nem található"
last_name_length="A „Keresztnév” túl hosszú."
content_length="Maximum 200 karakter"
he_friend_num_limit="Az Ön vagy a felhasználó ismerőseinek száma elérte a korlátot."
sign_error="Aláírás jóváhagyása meghiúsult"
is_friends="A felhasználó a barátod volt."
sms_friend_tips="Adj hozzá a JustUs-hoz."
photo_tips="Sikeresen feltöltve! Vegyen fel több barátot, hogy megosszák együtt a valós életet"
message_limit="Túl gyakran küld szöveges üzeneteket. Kérlek, próbáld újra később."
copy_friend_tips="Adj hozzá a JustUs-hoz."
no_add_friend_self="Nem veheted fel magadat barátként."
justus_slogan="Rögzítsük együtt a valós életet!"
justus_helper="JustUs Guide"
bind_mobile_error="A telefonszám egy másik fiókhoz lett kötve."
bound_mobile="A kötés nem sikerült. Kérlek, próbáld újra később."
not_add_self_friend="Nem veheted fel magadat barátként."
address_book_tips="Szinkronizálja névjegyeit, hogy barátokat találjon a JustUs-on. Névjegyadatait elküldjük a JustUs-nak, hogy javítsa az élményt, és lehetővé tegye Önnek és másoknak, hogy barátokat találjanak."
follow_user="követtelek!"
notification_friends=":name a „Csak mi” barátod lett! Próbálj meg képeket küldeni nekik!"
notification_like=":name pont kedveltél!"
notification_comment=":name most megjegyzést fűzött hozzád, nézd meg!"
notification_friend_apply=":name küldött neked egy baráti kérést."
notification_friend_send_picture=":name új fényképet tett közzé."
notification_user_register="Gyere és fotózd le! Rögzítsen közös életet barátaival!"
notification_friend_register=":name a JustUson is megtalálható. Hozzáad?"
notification_memory=":name, új emléke van."
notification_wait_add_friend=":name, barátaid várnak!"
notification_touch=":name megérintette a fényképét💓"
notification_follow_user=":name követtelek!"
photo_copy_1="Felvettem a (JustUs) oldalra. Töltse le ezt az alkalmazást, hogy engedélyezze a barátkérésemet.Az én személyi azonosítóm:"
photo_tips_1="Sikeresen feltöltve! Vegyen fel több barátot, hogy megosszák együtt a valós életet"
photo_end_1="Nincs több baráti pillanat. Készítsen fényképet, vagy vegyen fel további barátokat."
photo_copy_2="Adj hozzá a JustUs-hoz. Az én személyi azonosítóm:"
photo_tips_2="Sikeresen feltöltve! Vegyen fel több barátot, hogy megosszák együtt a valós életet"
photo_end_2="Nincs több baráti pillanat. Készítsen fényképet, vagy vegyen fel további barátokat."
photo_copy_3="Adj hozzá a JustUshoz, hogy megoszthassunk fotókat a kezdőképernyőn. Az én személyi azonosítóm:"
photo_tips_3="Elküldve a kezdőképernyőjükre! Vegyen fel több barátot, hogy megossza valódi életét a kezdőképernyőjén."
photo_end_3="Nincs több fotó. Vegyen fel több barátot, hogy megossza valódi életét a kezdőképernyőjén."
photo_copy_4="Adjon hozzá a JustUs-hoz, fotóim vannak, amelyeket elküldhetek a kezdőképernyőre. Az én személyi azonosítóm:"
photo_tips_4="Elküldve a kezdőképernyőjükre! Vegyen fel több barátot, hogy megossza valódi életét a kezdőképernyőjén."
photo_end_4="Nincs több fotó. Vegyen fel több barátot, hogy megossza valódi életét a kezdőképernyőjén."
photo_copy_5="Adj hozzá a JustUs-hoz, az új widget közösségi hálózathoz! Az én személyi azonosítóm:"
photo_tips_5="Elküldve a kezdőképernyőjükre! Vegyen fel több barátot, hogy megossza valódi életét a kezdőképernyőjén."
photo_end_5="Nincs több fotó. Hívjon meg több barátot, hogy ossza meg valós életét a kezdőképernyőjén."
photo_copy_6="Adj hozzá a JustUs - Widget közösségi hálózathoz, rajtad kívül minden készen áll!"
photo_tips_6="Elküldve a kezdőképernyőjükre! Hívjon meg több barátot, hogy ossza meg velük valós életét."
photo_end_6="Nincs több fotó. Vegyen fel több barátot, hogy megossza velük valós életét."
photo_copy_7="Adj hozzá a JustUs-hoz, minden készen áll, kivéve téged! Az én személyi azonosítóm:"
photo_tips_7="Elküldve a kezdőképernyőjükre! Hívjon meg több barátot, hogy ossza meg velük valós életét."
photo_end_7="Nincs több fotó. Vegyen fel több barátot, hogy megossza velük valós életét."
photo_copy_8="Adjon hozzá a JustUs - Widget közösségi hálózathoz, ossza meg velem a valós életet! Az én személyi azonosítóm:"
photo_tips_8="Elküldve a kezdőképernyőjükre! Hívjon meg több barátot, hogy ossza meg velük valós életét."
photo_end_8="Nincs több fotó. Vegyen fel több barátot, hogy megossza velük valós életét."
photo_copy_9="Fogadja el a valós életű fotókihívást: Add hozzá a JustUs-hoz. Az én személyi azonosítóm:"
photo_tips_9="Elküldve a kezdőképernyőjükre! Hívjon meg több barátot, hogy ossza meg velük valós életét."
photo_end_9="Nincs több fotó. Vegyen fel több barátot, hogy megossza velük valós életét."
photo_copy_10="Azt akarom, hogy a kezdőképernyőmre kerüljön, és adjon hozzá a JustUs-hoz. Az én személyi azonosítóm:"
photo_tips_10="Elküldve a kezdőképernyőjükre! Szórakoztatóbb lenne, ha több barátot adnál hozzá."
photo_end_10="Nincs több fotó. Vegyen fel több barátot, hogy megosszák együtt valós életét."
photo_copy_11="Azt akarom, hogy a kezdőképernyőmre kerüljön, és adjon hozzá a JustUs-hoz. Az én személyi azonosítóm:"
photo_tips_11="Elküldve a kezdőképernyőjükre! Vegyen fel további barátokat, hogy elküldhesse fotóit a kezdőképernyőjükre."
photo_end_11="Úgy tűnik, kifogytál az ismerőseid fotóiból! Vegyen fel több barátot, hogy közösen rögzítse valódi életét."
photo_copy_12="Legyen a kezdőképernyő barátom, adjon hozzá a JustUshoz. Az én személyi azonosítóm:"
photo_tips_12="Elküldve a kezdőképernyőjükre! Hívjon meg több barátot a kezdőképernyőre, és küldjön nekik szórakoztató fotókat!"
photo_end_12="Úgy tűnik, kifogytál az ismerőseid fotóiból! Hívjon meg több barátot a kezdőképernyőre, és küldjön nekik szórakoztató fotókat."
photo_copy_13="Legyen a kezdőképernyő barátom, adjon hozzá a JustUshoz. Az én személyi azonosítóm:"
photo_tips_13="Elküldve a kezdőképernyőjükre! Szórakoztatóbb lenne, ha több ismerőst adna hozzá a kezdőképernyőről."
photo_end_13="Úgy tűnik, több barátra van szüksége! Hívjon meg több barátot a kezdőképernyőre, és küldjön nekik szórakoztató fotókat."
your_self_visible="Csak nekem látható"
update_new_version="Új duett funkció, kérjük, gyere frissíteni és tapasztalni!"
