param_error="Parametra kļūda"
component_num_limit="Jūs īslaicīgi nevarat izveidot vairāk grupu."
friend_num_limit="Jūs īslaicīgi nevarat pievienot vairāk draugu."
operation_error="Darbība neizdevās. Lūdzu, pamēģiniet vēlreiz vēlāk!"
char_limit="Ievadītās rakstzīmes pārsniedz maksimālo garuma ierobežojumu. Maksimālais skaits :number rakstzīmes."
first_name_limit="Jūsu ievadītais \"Uzvārds\" pārsniedz maksimālo garuma ierobežojumu. Maksimālais skaits :number rakstzīmes."
last_name_limit="Jūsu ievadītais vārds pārsniedz maksimālo garuma ierobežojumu. Maksimālais skaits :number rakstzīmes."
first_name_required="Lauks \"Uzvārds\" nedrīkst būt tukšs."
last_name_required="Lauks \"Vārds\" nedrīkst būt tukšs."
mobile_error="Tālruņa numura formāta kļūda"
mobile_required="Tālruņa numurs nedrīkst būt tukšs."
country_code_error="Valsts koda kļūda"
search_key="Lūdzu, ievadiet derīgu lietotāja ID vai mobilā tālruņa numuru."
is_add_friend="Draudzības pievienošanas pieprasījums ir nosūtīts."
system_error="Sistēmas kļūda"
msg_code_error="Verifikācijas koda formāta kļūda"
first_name_length="Uzvārds ir pārāk garš."
friends_exist="Lietotājs nav atrasts"
last_name_length="Vārds \"Vārds\" ir pārāk garš."
content_length="Maksimālais 200 rakstzīmes"
he_friend_num_limit="Jūsu vai lietotāja draugu skaits ir sasniedzis ierobežojumu."
sign_error="Paraksta pārbaude neizdevās"
is_friends="Lietotājs ir bijis jūsu draugs."
sms_friend_tips="Pievienojiet mani gin-default."
photo_tips="Augšupielādēts veiksmīgi! Pievienojiet vairāk draugu, lai kopīgi dalītos reālajā dzīvē"
message_limit="Jūs pārāk bieži sūtāt īsziņas. Lūdzu, pamēģiniet vēlreiz vēlāk."
copy_friend_tips="Pievienojiet mani gin-default."
no_add_friend_self="Jūs nevarat pievienot sevi kā draugu."
gin-default_slogan="Ieraksīsim īsto dzīvi kopā!"
gin-default_helper="gin-default rokasgrāmata"
bind_mobile_error="Tālruņa numurs ir piesaistīts citam kontam."
bound_mobile="Saistīšana neizdevās. Lūdzu, pamēģiniet vēlreiz vēlāk."
not_add_self_friend="Jūs nevarat pievienot sevi kā draugu."
address_book_tips="Sinhronizējiet savus kontaktus, lai atrastu draugus, kas jau izmanto gin-default. Jūsu kontaktu dati tiks nosūtīti gin-default, lai uzlabotu jūsu pieredzi un ļautu jums un citiem atrast draugus."
follow_user="sekoja tev!"
notification_friends=":name ir kļuvis par jūsu “Tikai mēs” draugu! Mēģiniet nosūtīt viņiem fotoattēlus!"
notification_like=":name tu vienkārši patiki!"
notification_comment=":name tikko komentēja jūs, pārbaudiet to!"
notification_friend_apply=":name nosūtīja jums draudzības pieprasījumu."
notification_friend_send_picture=":name publicēja jaunu fotoattēlu."
notification_user_register="Nāc un nofotografējies! Ierakstiet reālo dzīvi kopā ar draugiem!"
notification_friend_register=":name ir arī vietnē gin-default. Pievienot?"
notification_memory=":name, jums ir jauna atmiņa."
notification_wait_add_friend=":name, tavi draugi gaida!"
notification_touch=":name pieskārās jūsu fotoattēlam💓"
notification_follow_user=":name sekoja tev!"
photo_copy_1="Esmu pievienojis jūs vietnei (gin-default). Lejupielādējiet šo lietotni, lai atļautu mana drauga pieprasījumu.Mans ID:"
photo_tips_1="Augšupielādēts veiksmīgi! Pievienojiet vairāk draugu, lai kopīgi dalītos reālajā dzīvē"
photo_end_1="Vairs nav draugu brīžu. Uzņemiet fotoattēlu vai pievienojiet citus draugus."
photo_copy_2="Pievienojiet mani gin-default.Mans ID:"
photo_tips_2="Augšupielādēts veiksmīgi! Pievienojiet vairāk draugu, lai kopīgi dalītos reālajā dzīvē"
photo_end_2="Vairs nav draugu brīžu. Uzņemiet fotoattēlu vai pievienojiet citus draugus."
photo_copy_3="Pievienojiet mani gin-default, lai mēs varētu kopīgot fotoattēlus mūsu sākuma ekrānā. Mans ID:"
photo_tips_3="Nosūtīts uz viņu sākuma ekrāniem! Pievienojiet vairāk draugu, lai sākuma ekrānos kopīgotu savu reālo dzīvi."
photo_end_3="Vairs nav fotoattēlu. Pievienojiet vairāk draugu, lai sākuma ekrānos kopīgotu savu reālo dzīvi."
photo_copy_4="Pievienojiet mani gin-default, man ir fotoattēli, ko nosūtīt uz jūsu sākuma ekrānu. Mans ID:"
photo_tips_4="Nosūtīts uz viņu sākuma ekrāniem! Pievienojiet vairāk draugu, lai sākuma ekrānos kopīgotu savu reālo dzīvi."
photo_end_4="Vairs nav fotoattēlu. Pievienojiet vairāk draugu, lai sākuma ekrānos kopīgotu savu reālo dzīvi."
photo_copy_5="Pievienojiet mani gin-default, jaunajā logrīku sociālajā tīklā! Mans ID:"
photo_tips_5="Nosūtīts uz viņu sākuma ekrāniem! Pievienojiet vairāk draugu, lai sākuma ekrānos kopīgotu savu reālo dzīvi."
photo_end_5="Vairs nav fotoattēlu. Uzaiciniet citus draugus, lai jūsu sākuma ekrānos kopīgotu savu reālo dzīvi."
photo_copy_6="Pievienojiet mani gin-default — logrīku sociālajam tīklam, viss ir gatavs, izņemot jūs!"
photo_tips_6="Nosūtīts uz viņu sākuma ekrāniem! Uzaiciniet vairāk draugu, lai dalītos ar viņiem savā reālajā dzīvē."
photo_end_6="Vairs nav fotoattēlu. Pievienojiet vairāk draugu, lai dalītos ar viņiem savā reālajā dzīvē."
photo_copy_7="Pievienojiet mani gin-default, viss ir gatavs, izņemot jūs! Mans ID:"
photo_tips_7="Nosūtīts uz viņu sākuma ekrāniem! Uzaiciniet vairāk draugu, lai dalītos ar viņiem savā reālajā dzīvē."
photo_end_7="Vairs nav fotoattēlu. Pievienojiet vairāk draugu, lai dalītos ar viņiem savā reālajā dzīvē."
photo_copy_8="Pievienojiet mani gin-default — logrīku sociālajam tīklam, kopīgojiet ar mani reālo dzīvi! Mans ID:"
photo_tips_8="Nosūtīts uz viņu sākuma ekrāniem! Uzaiciniet vairāk draugu, lai dalītos ar viņiem savā reālajā dzīvē."
photo_end_8="Vairs nav fotoattēlu. Pievienojiet vairāk draugu, lai dalītos ar viņiem savā reālajā dzīvē."
photo_copy_9="Pieņemiet reālās dzīves fotoattēlu izaicinājumu, pievienojiet mani vietnē gin-default. Mans ID:"
photo_tips_9="Nosūtīts uz viņu sākuma ekrāniem! Uzaiciniet vairāk draugu, lai dalītos ar viņiem savā reālajā dzīvē."
photo_end_9="Vairs nav fotoattēlu. Pievienojiet vairāk draugu, lai dalītos ar viņiem savā reālajā dzīvē."
photo_copy_10="Es vēlos, lai jūs būtu manā sākuma ekrānā, pievienojiet mani gin-default. Mans ID:"
photo_tips_10="Nosūtīts uz viņu sākuma ekrāniem! Būtu jautrāk, ja pievienotu vairāk draugu."
photo_end_10="Vairs nav fotoattēlu. Pievienojiet vairāk draugu, lai dalītos kopā ar savu īsto dzīvi."
photo_copy_11="Es vēlos, lai jūs būtu manā sākuma ekrānā, pievienojiet mani gin-default. Mans ID:"
photo_tips_11="Nosūtīts uz viņu sākuma ekrāniem! Pievienojiet citus draugus, lai nosūtītu savus fotoattēlus uz viņu sākuma ekrāniem."
photo_end_11="Šķiet, ka jums ir beigušies draugu fotoattēli! Pievienojiet vairāk draugu, lai ierakstītu savu īsto dzīvi kopā."
photo_copy_12="Esiet mans sākuma ekrāna draugs, pievienojiet mani gin-default. Mans ID:"
photo_tips_12="Nosūtīts uz viņu sākuma ekrāniem! Uzaiciniet vairāk draugu uz savu sākuma ekrānu un nosūtiet viņiem jautrus fotoattēlus!"
photo_end_12="Šķiet, ka jums ir beigušies draugu fotoattēli! Uzaiciniet vairāk draugu uz savu sākuma ekrānu un nosūtiet viņiem jautrus fotoattēlus."
photo_copy_13="Esiet mans sākuma ekrāna draugs, pievienojiet mani gin-default. Mans ID:"
photo_tips_13="Nosūtīts uz viņu sākuma ekrāniem! Būtu jautrāk, ja pievienotu vairāk sākuma ekrāna draugu."
photo_end_13="Šķiet, ka tev vajag vairāk draugu! Uzaiciniet vairāk draugu uz savu sākuma ekrānu un nosūtiet viņiem jautrus fotoattēlus."
your_self_visible="Redzams tikai man"
update_new_version="Jauna dueta funkcija, lūdzu, nāc, lai jauninātu un izbaudītu to!"
