param_error="error de parametro"
component_num_limit="No puedes crear más grupos temporalmente."
friend_num_limit="No puedes agregar más amigos temporalmente."
operation_error="Operación fallida. ¡Por favor, inténtelo de nuevo más tarde!"
char_limit="Los caracteres que ingresó exceden el límite de longitud máxima. El máximo :number  caracteres."
first_name_limit="El \"Apellido\" que ingresó excede el límite máximo de longitud. El máximo :number  caracteres."
last_name_limit="El \"Nombre\" que ingresó excede el límite de longitud máxima. El máximo :number caracteres."
first_name_required="El \"Apellido\" no puede estar vacío."
last_name_required="El \"Nombre\" no puede estar vacío."
mobile_error="Error de formato de número de teléfono"
mobile_required="El número de teléfono no puede estar vacío."
country_code_error="Error de código de país"
search_key="Ingrese una identificación de usuario válida o un número de teléfono móvil."
is_add_friend="Se ha enviado la solicitud de añadir amistad."
system_error="Error del sistema"
msg_code_error="Error de formato del código de verificación"
first_name_length="El \"Apellido\" es demasiado largo."
friends_exist="Usuario no encontrado"
last_name_length="El \"Nombre\" es demasiado largo."
content_length="El máximo de 200 caracteres"
he_friend_num_limit="Tu número de amigos o el del usuario ha alcanzado el límite."
sign_error="Verificación de firma fallida"
is_friends="El usuario ha sido tu amigo."
sms_friend_tips="Agrégame en JustUs."
photo_tips="¡Subido con éxito! Agrega más amigos para compartir la vida real juntos"
message_limit="Envías mensajes de texto con demasiada frecuencia. Por favor, inténtelo de nuevo más tarde."
copy_friend_tips="Agrégame en JustUs."
no_add_friend_self="No puedes agregarte como amigo."
justus_slogan="¡Grabemos la vida real juntos!"
justus_helper="Guía JustUs"
bind_mobile_error="El número de teléfono se ha vinculado a otra cuenta."
bound_mobile="Enlace fallido. Por favor, inténtelo de nuevo más tarde."
not_add_self_friend="No puedes agregarte como amigo."
address_book_tips="Sincronice sus contactos para encontrar amigos que ya estén en JustUs. Los datos de sus contactos se enviarán a JustUs para mejorar su experiencia y permitirle a usted y a otros encontrar amigos."
follow_user="¡te siguió!"
notification_friends="¡:name se ha convertido en tu amigo \"Solo nosotros\"! ¡Intenta enviarles fotos!"
notification_like=":name acaba de gustarle!"
notification_comment=":name acaba de comentarte, ¡échale un vistazo!"
notification_friend_apply=":name te envió una solicitud de amistad."
notification_friend_send_picture=":name publicó una foto nueva."
notification_user_register="¡Ven y toma una foto! ¡Graba la vida real con tus amigos juntos!"
notification_friend_register=":name también está en JustUs. ¿Agregar?"
notification_memory=":name, tienes un nuevo recuerdo."
notification_wait_add_friend=":name, ¡tus amigos te están esperando!"
notification_touch=":name tocó tu foto 💓"
notification_follow_user=":name ¡te siguió!"
photo_copy_1="Te he agregado en (JustUs). Descarga esta aplicación para permitir mi solicitud de amistad.Mi identificación:"
photo_tips_1="¡Subido con éxito! Agrega más amigos para compartir la vida real juntos"
photo_end_1="No más momentos de amigos. Toma una foto o agrega más amigos."
photo_copy_2="Agrégame en JustUs.Mi identificación:"
photo_tips_2="¡Subido con éxito! Agrega más amigos para compartir la vida real juntos"
photo_end_2="No más momentos de amigos. Toma una foto o agrega más amigos."
photo_copy_3="Agrégame en JustUs para que podamos compartir fotos en nuestra pantalla de inicio. Mi identificación:"
photo_tips_3="¡Enviado a sus pantallas de inicio! Agregue más amigos para compartir su vida real en sus pantallas de inicio."
photo_end_3="No mas fotos. Agregue más amigos para compartir su vida real en sus pantallas de inicio."
photo_copy_4="Agrégame en JustUs, tengo fotos para enviar a tu pantalla de inicio. Mi identificación:"
photo_tips_4="¡Enviado a sus pantallas de inicio! Agregue más amigos para compartir su vida real en sus pantallas de inicio."
photo_end_4="No mas fotos. Agregue más amigos para compartir su vida real en sus pantallas de inicio."
photo_copy_5="¡Agrégame en JustUs, la nueva red social de widgets! Mi identificación:"
photo_tips_5="¡Enviado a sus pantallas de inicio! Agregue más amigos para compartir su vida real en sus pantallas de inicio."
photo_end_5="No mas fotos. Invita a más amigos a compartir tu vida real en tus pantallas de inicio."
photo_copy_6="Agrégame en JustUs - Widget Social Network, ¡todo está listo excepto tú!"
photo_tips_6="¡Enviado a sus pantallas de inicio! Invita a más amigos a compartir tu vida real con ellos."
photo_end_6="No mas fotos. Agrega más amigos para compartir tu vida real con ellos."
photo_copy_7="¡Agrégame en JustUs, todo está listo excepto tú! Mi identificación:"
photo_tips_7="¡Enviado a sus pantallas de inicio! Invita a más amigos a compartir tu vida real con ellos."
photo_end_7="No mas fotos. Agrega más amigos para compartir tu vida real con ellos."
photo_copy_8="Agrégame en JustUs - Widget Social Network, ¡comparte la vida real conmigo! Mi identificación:"
photo_tips_8="¡Enviado a sus pantallas de inicio! Invita a más amigos a compartir tu vida real con ellos."
photo_end_8="No mas fotos. Agrega más amigos para compartir tu vida real con ellos."
photo_copy_9="Acepte el desafío fotográfico de la vida real, agrégueme en JustUs. Mi identificación:"
photo_tips_9="¡Enviado a sus pantallas de inicio! Invita a más amigos a compartir tu vida real con ellos."
photo_end_9="No mas fotos. Agrega más amigos para compartir tu vida real con ellos."
photo_copy_10="Quiero que estés en mi pantalla de inicio, agrégame en JustUs. Mi identificación:"
photo_tips_10="¡Enviado a sus pantallas de inicio! Sería más divertido si agregas más amigos."
photo_end_10="No mas fotos. Agregue más amigos para compartir su vida real juntos."
photo_copy_11="Quiero que estés en mi pantalla de inicio, agrégame en JustUs. Mi identificación:"
photo_tips_11="¡Enviado a sus pantallas de inicio! Agrega más amigos para enviar tus fotos a sus pantallas de inicio."
photo_end_11="¡Parece que te has quedado sin fotos de amigos! Agregue más amigos para grabar sus vidas reales juntos."
photo_copy_12="Sé mi amigo en la pantalla de inicio, agrégame en JustUs. Mi identificación:"
photo_tips_12="¡Enviado a sus pantallas de inicio! ¡Invita a más amigos a tu pantalla de inicio y envíales fotos divertidas!"
photo_end_12="¡Parece que te has quedado sin fotos de amigos! Invita a más amigos a tu pantalla de inicio y envíales fotos divertidas."
photo_copy_13="Sé mi amigo en la pantalla de inicio, agrégame en JustUs. Mi identificación:"
photo_tips_13="¡Enviado a sus pantallas de inicio! Sería más divertido si agregas más amigos en la pantalla de inicio."
photo_end_13="¡Parece que necesitas más amigos! Invita a más amigos a tu pantalla de inicio y envíales fotos divertidas."
your_self_visible="solo visible para mi"
update_new_version="Nueva función de dúo, ¡venga a actualizar y experimentarla!"
