param_error="Lỗi tham số"
component_num_limit="Bạn tạm thời không thể tạo thêm nhóm."
friend_num_limit="Bạn tạm thời không thể thêm bạn bè."
operation_error="Lỗi hệ thống. Vui lòng thử lại sau!"
char_limit="Các ký tự bạn đã nhập vượt quá giới hạn độ dài tối đa. Tối đa :number ký tự."
first_name_limit="Họ bạn đã nhập vượt quá giới hạn độ dài tối đa. Tối đa :number ký tự."
last_name_limit="Tên bạn đã nhập vượt quá giới hạn độ dài tối đa. Tối đa :number ký tự."
first_name_required="Không được để trống \"Họ\"."
last_name_required="Không được để trống \"Tên\"."
mobile_error="Lỗi định dạng số điện thoại"
mobile_required="Số điện thoại không được để trống."
country_code_error="Lỗi mã quốc gia"
search_key="Vui lòng nhập id người dùng hoặc số điện thoại hợp lệ."
is_add_friend="Thêm yêu cầu kết bạn đã được gửi."
system_error="Lỗi hệ thống"
msg_code_error="Lỗi định dạng mã xác minh"
first_name_length="Họ quá dài."
friends_exist="Không tìm thấy người dùng"
last_name_length="Tên quá dài."
content_length="Tối đa 200 ký tự"
he_friend_num_limit="Số lượng bạn bè của bạn hoặc người dùng đã đạt đến giới hạn."
sign_error="Xác minh chữ ký không thành công"
is_friends="Người dùng đã là bạn của bạn."
sms_friend_tips="Thêm tôi trên gin-default."
photo_tips="Tải lên thành công! Thêm nhiều bạn bè để chia sẻ cuộc sống thực cùng nhau"
message_limit="Bạn gửi tin nhắn văn bản quá thường xuyên. Vui lòng thử lại sau."
copy_friend_tips="Thêm tôi trên gin-default."
no_add_friend_self="Bạn không thể thêm mình vào làm bạn."
gin-default_slogan="Cùng nhau ghi lại cuộc sống thực tế nhé!"
gin-default_helper="Hướng dẫn gin-default"
bind_mobile_error="Số điện thoại đã được liên kết với một tài khoản khác."
bound_mobile="Ràng buộc không thành công. Vui lòng thử lại sau."
not_add_self_friend="Bạn không thể thêm mình làm bạn."
address_book_tips="Đồng bộ danh bạ của bạn để tìm bạn bè đã có trên gin-default. Dữ liệu danh bạ của bạn sẽ được gửi tới gin-default để cải thiện trải nghiệm của bạn và cho phép bạn và những người khác tìm kiếm bạn bè."
follow_user="đã theo bạn!"
notification_friends=":name đã trở thành người bạn \"Chỉ với chúng tôi\" của bạn! Hãy thử gửi ảnh cho họ!"
notification_like=":name chỉ thích bạn!"
notification_comment=":name vừa nhận xét về bạn, hãy kiểm tra!"
notification_friend_apply=":name đã gửi cho bạn một yêu cầu kết bạn."
notification_friend_send_picture=":name đã đăng một bức ảnh mới."
notification_user_register="Hãy đến và chụp ảnh! Ghi lại cuộc sống thực với bạn bè của bạn cùng nhau!"
notification_friend_register=":name tên cũng trên gin-default. Thêm vào?"
notification_memory=":name, bạn có một kỷ niệm mới."
notification_wait_add_friend=":name, bạn bè của bạn đang đợi!"
notification_touch=":name chạm vào ảnh của bạn💓"
notification_follow_user=":name đã theo bạn!"
photo_copy_1="Tôi đã thêm bạn vào (gin-default). Tải xuống ứng dụng này để cho phép yêu cầu kết bạn của tôi.Mã số của tôi:"
photo_tips_1="Tải lên thành công! Thêm nhiều bạn bè để chia sẻ cuộc sống thực cùng nhau"
photo_end_1="Không còn những khoảnh khắc của bạn bè. Chụp ảnh hoặc thêm bạn bè."
photo_copy_2="Thêm tôi trên gin-default.Mã số của tôi:"
photo_tips_2="Tải lên thành công! Thêm nhiều bạn bè để chia sẻ cuộc sống thực cùng nhau"
photo_end_2="Không còn những khoảnh khắc của bạn bè. Chụp ảnh hoặc thêm bạn bè."
photo_copy_3="Thêm tôi vào gin-default để chúng tôi có thể chia sẻ ảnh lên màn hình chính của mình. Mã số của tôi:"
photo_tips_3="Gửi đến màn hình chính của họ! Thêm nhiều bạn bè để chia sẻ cuộc sống thực của bạn trên màn hình chính."
photo_end_3="Không còn ảnh nữa. Thêm nhiều bạn bè để chia sẻ cuộc sống thực của bạn trên màn hình chính."
photo_copy_4="Thêm tôi vào gin-default, tôi có ảnh để gửi đến màn hình chính của bạn. Mã số của tôi:"
photo_tips_4="Gửi đến màn hình chính của họ! Thêm nhiều bạn bè để chia sẻ cuộc sống thực của bạn trên màn hình chính."
photo_end_4="Không còn ảnh nữa. Thêm nhiều bạn bè để chia sẻ cuộc sống thực của bạn trên màn hình chính."
photo_copy_5="Thêm tôi trên gin-default, mạng xã hội tiện ích con mới! Mã số của tôi:"
photo_tips_5="Gửi đến màn hình chính của họ! Thêm nhiều bạn bè để chia sẻ cuộc sống thực của bạn trên màn hình chính."
photo_end_5="Không còn ảnh nữa. Mời thêm bạn bè để chia sẻ cuộc sống thực của bạn trên màn hình chính."
photo_copy_6="Thêm tôi trên gin-default - Mạng xã hội tiện ích, tất cả đã sẵn sàng, ngoại trừ bạn!"
photo_tips_6="Gửi đến màn hình chính của họ! Mời thêm bạn bè để chia sẻ cuộc sống thực của bạn với họ."
photo_end_6="Không còn ảnh nữa. Thêm nhiều bạn bè để chia sẻ cuộc sống thực của bạn với họ."
photo_copy_7="Thêm tôi vào gin-default, tất cả đã sẵn sàng, ngoại trừ bạn! Mã số của tôi:"
photo_tips_7="Gửi đến màn hình chính của họ! Mời thêm bạn bè để chia sẻ cuộc sống thực của bạn với họ."
photo_end_7="Không còn ảnh nữa. Thêm nhiều bạn bè để chia sẻ cuộc sống thực của bạn với họ."
photo_copy_8="Thêm tôi trên gin-default - Mạng xã hội tiện ích, chia sẻ cuộc sống thực với tôi! Mã số của tôi:"
photo_tips_8="Gửi đến màn hình chính của họ! Mời thêm bạn bè để chia sẻ cuộc sống thực của bạn với họ."
photo_end_8="Không còn ảnh nữa. Thêm nhiều bạn bè để chia sẻ cuộc sống thực của bạn với họ."
photo_copy_9="Chấp nhận thử thách chụp ảnh đời thực, Thêm tôi trên gin-default. Mã số của tôi:"
photo_tips_9="Gửi đến màn hình chính của họ! Mời thêm bạn bè để chia sẻ cuộc sống thực của bạn với họ."
photo_end_9="Không còn ảnh nữa. Thêm nhiều bạn bè để chia sẻ cuộc sống thực của bạn với họ."
photo_copy_10="Tôi muốn bạn ở trên màn hình chính của tôi, hãy thêm tôi vào gin-default. Mã số của tôi:"
photo_tips_10="Gửi đến màn hình chính của họ! Sẽ vui hơn nếu bạn có thêm nhiều bạn bè."
photo_end_10="Không còn ảnh nữa. Thêm nhiều bạn bè để chia sẻ cuộc sống thực của bạn với nhau."
photo_copy_11="Tôi muốn bạn ở trên màn hình chính của tôi, hãy thêm tôi vào gin-default. Mã số của tôi:"
photo_tips_11="Gửi đến màn hình chính của họ! Thêm nhiều bạn bè để gửi ảnh của bạn lên màn hình chính của họ."
photo_end_11="Có vẻ như bạn đã hết ảnh của bạn bè! Thêm nhiều bạn bè để ghi lại cuộc sống thực của bạn cùng nhau."
photo_copy_12="Hãy trở thành người bạn trên màn hình chính của tôi, thêm tôi vào gin-default. Mã số của tôi:"
photo_tips_12="Gửi đến màn hình chính của họ! Mời thêm bạn bè vào màn hình chính của bạn và gửi cho họ những bức ảnh vui nhộn!"
photo_end_12="Có vẻ như bạn đã hết ảnh của bạn bè! Mời thêm bạn bè vào màn hình chính của bạn và gửi cho họ những bức ảnh vui nhộn."
photo_copy_13="Hãy trở thành người bạn trên màn hình chính của tôi, thêm tôi vào gin-default. Mã số của tôi:"
photo_tips_13="Gửi đến màn hình chính của họ! Sẽ vui hơn nếu bạn có thêm nhiều người bạn trên màn hình chính."
photo_end_13="Có vẻ như bạn cần thêm bạn bè! Mời thêm bạn bè vào màn hình chính của bạn và gửi cho họ những bức ảnh vui nhộn."
your_self_visible="Chỉ hiển thị với tôi"
update_new_version="Chức năng song ca mới, mời các bạn vào nâng cấp và trải nghiệm nhé!"
